### ISSUE TITLE
Factored Neural Machine Translation

### ISSUE THREAD

**Issue by patrick-wilken** [rwth-i6/returnn#102]
I am in the process of implementing (Target-)[Factored Neural Machine Translation](https://arxiv.org/abs/1609.04621). This is what I've got so far: https://github.com/patrick-wilken/returnn-examples/blob/master/factored-nmt

I have problems creating a config that works for both training and search. I have to comment line 126 of https://github.com/patrick-wilken/returnn-examples/blob/master/factored-nmt/config to make it work in training (and uncomment it to make it work in search).

This has to do with the ChoiceLayer in line 124, which provides the true label In training instead of being evaluated. The true label seems to have a time axis, so a shape of `()` is invalid (as it should include the time axis).
In search however, the choice layer is evaluated in each step, so its output has no time dimension. Therefore `"shape": ()` should be correct. But by default it is set to `(None,)`, which causes the following error: https://gist.github.com/patrick-wilken/5eba7a3d209f7a1e470b6082fef2dd6d. Looking at `get_out_data_from_opts` of ChoiceLayer it looks like the time dimension is always included, as we're just getting the shape from data. Is this correct? What would be the proper way to fix it?

**Comment by patrick-wilken** [comment]
Also, it would be nice to discuss, whether parts of the config should become dedicated layers in the end instead of using that many EvalLayers. As you see I'm using an outer product (DotLayer) + reshapes (MergeDimsLayer) to combine the two softmaxes. After that I use div and mod to get back the indices of the different factors. Beam pruning after the two softmaxes is still missing.

**Comment by albertz** [comment]
Setting `shape` explicitly is problematic for the reasons you describe.
But not setting `shape` should work I think in both cases, or maybe there is a bug somewhere. Not setting the shape should then by default take the shape from the first source layer (i.e. `output` here). And this is the right thing, right? I would debug where that goes wrong. Maybe you can create a reduced test case, and then fix it.

About creating dedicated layers: Not sure if that really makes it simpler. Maybe you safe one line in your config, but then imagine someone else reading your config who is not familiar with your very special new layer. He would not understand what the config is doing without also looking at the code of your special layer. That is why I try to only have very generic layers which are more or less clear/straightforward about what they do. If you want to discuss further, maybe independent from the GitHub issue here. I talked with Julian today and we plan to have a meeting together early next year.

**Comment by patrick-wilken** [comment]
I was able to dig deeper into this:
In `_SubnetworkRecCell._construct_template()` we start the template construction by calling `get_templated_layer("output")` (line 906). In my case this recursively calls `get_templated_layer` (through `construct _layer` in line 885) for all the layers in the recurrent unit (output_prob_combined, output_prob_combined_matrix, ..., target_embed, output_de) and ends up back at "output". Here, `construct_layer` fails (for all variants of `get_layer`) with the exception `There is a dependency loop on layer 'output'`, which is caught by the try statements.
After that the previous layer in the recursion "output_de" is created. For the get_layer variants with `allow_uninitialized_template=False` it fails with `'NoneType' object has no attribute 'output'` in TFNetworkLayer.py line 268, because the source layer, which is "output", was not created yet. So the layer is created with allow_uninitialized_template=True. Because of this, the default shape (None,) of "dummy_initial_template_data" is kept (line 2172). This is the wrong shape, but it is never changed afterwards and the end layer inherits this wrong shape, therefore the assertion error I get.

I realize, this is exactly what is described in the comment in line 877. But I don't know what would be the intended solution. Is the failure to create the "output" layer in the first try expected behaviour?

By the way, doesn't the `construct_layer` call in line 893 do the exact same thing as the one in the first loop? Also, I think the beginning of the comment still refers to the old order of get_layer variants which was changed in c4545b9, right?

**Comment by patrick-wilken** [comment]
I found one way to solve it, see the pull request in a few minutes 😄

**Comment by patrick-wilken** [comment]
Setting out_type solves the problem, yes. But I need a different out_type for training and search, as the layer is moved out of the loop in training. That's the original problem.

In `LayerBase._post_init_output()` the line 
`if sources and sources[0].output.matches_var_dim_pattern(output):`
should be
`if sources[0] and sources[0].output.matches_var_dim_pattern(output):`
or maybe even:
`if sources and sources[0] and sources[0].output.matches_var_dim_pattern(output):`
Then it throws no error. However, still in that case the default shape (None,) is used, as there is neither a source nor a target available for the "output_de" layer. Maybe I could set a target for it and make the "TODO" work for search. But this does not seem to be the intended solution, as it is specific to layers which use `_base_get_out_data_from_opts`.

**Comment by patrick-wilken** [comment]
Also this can be closed, I think, at least under this heading. There is still the general issue that moving a layer out of the loop can make explicit shapes invalid, but I can open a separate issue when I run into this again.

**Comment by albertz** [comment]
Ok.
