### ISSUE TITLE
Dim tag derived_from_tag/same_as cycle due to conv+padding

### ISSUE THREAD

**Issue by dierkes-j** [rwth-i6/returnn#1054]
I have the following exemplary config reproducing the problem:
```
#!returnn.py
# kate: syntax python;

use_tensorflow = True

task = "initialize_model"
train = {"class": "Task12AXDataset", "num_seqs": 1000}

network = {
        "Conv1": {'class': 'conv', 'from': 'data', 'activation': None, 'with_bias': True, 'n_out': 9, 'filter_size': (4,), 'padding': 'same', 'in_spatial_dims': ['T'], 'strides': (2,)},
        "ConstantPad": {'class': 'pad', 'mode': 'constant', 'axes': ['T'], 'padding': [(1, 1)], 'from': 'Conv1', 'value': 0},
        "Conv2": {'class': 'conv', 'from': 'ConstantPad', 'activation': None, 'with_bias': True, 'n_out': 9, 'filter_size': (3,), 'padding': 'valid', 'in_spatial_dims': ['T'], 'groups': 9},
        "add": {'class': 'combine', 'kind': 'add', 'from': ['Conv1', 'Conv2']},
        "output": {"class": "softmax", "loss": "ce", "from": ["add"]},
}

log_verbosity = 5
```

This config gives the error:
```
  File "/u/dierkes/returnn/returnn/tf/util/data.py", line 870, in Dim.undefined
    line: assert id(base) not in visited  # should not have cycles. normally this should never be triggered
    locals:
      id = <builtin> <built-in function id>
      base = <local> Dim{'Conv2:conv:s0'[B]}
      visited = <local> {140193235905552: Dim{'Conv2:conv:s0'[B]}, 140193235855968: Dim{'Conv2:conv:s0'[B]}, 140193235561152: Dim{'Conv2:conv:s0'[B]}, 140193235534224: Dim{'1+Conv1:conv:s0+1'[B]}, 140193235535712: Dim{'1+Conv1:conv:s0+1'[?]}}
AssertionError
```

Full stack-trace is posted below. 

Apparently the problem is that there is a circle in the dimension ancestry of the time output dimension of `Conv2`. This is problematic in `Dim.undefined` where the problem is detected. The circle is the following: `Conv2` time dimension links to `ConstantPad` time dimension which links back to `Conv2` time dimension. I think the problem is created in when for the layer `Conv2` the function `get_out_data_from_opts` is called:
In `Conv2.get_out_data_from_opts` the function `set_output_dim_tag` is called https://github.com/rwth-i6/returnn/blob/ae42d2473e44f8bce4fe04f88b021b4d0bffea7b/returnn/tf/layers/basic.py#L5300
In the function `set_output_dim_tag` we then calculate the out tag in https://github.com/rwth-i6/returnn/blob/ae42d2473e44f8bce4fe04f88b021b4d0bffea7b/returnn/tf/layers/basic.py#L5043
and finally set the calculated output tag to be `same_as` the `out_tag` in https://github.com/rwth-i6/returnn/blob/ae42d2473e44f8bce4fe04f88b021b4d0bffea7b/returnn/tf/layers/basic.py#L5048
Apparently because of the structure of our network the calculated output tag is the time dimension of `Conv1` and then appears to be overwritten to the out tag of `Conv2`. Thus the time dimension ancestor of `ConstantPad` is linking now to `Conv2` time dimension instead of `Conv1` creating the circle.

This problem is also relevant to the issue in the pytorch-to-returnn converter https://github.com/rwth-i6/pytorch-to-returnn/issues/124

A proposed solution to the problem you can find in the PR draft #1055

**Comment by albertz** [comment]
Can you post the output when you run it?

**Comment by dierkes-j** [comment]
Full stack-trace:
```
Hello, experiment: demo-tf-native-lstm.12ax
RETURNN starting up, version 1.20220406.130159+git.d6e71e29.dirty, date/time 2022-06-02-15-24-25 (UTC+0200), pid 30634, cwd /u/dierkes/debugging/residual_debug, Python /work/tools/asr/python/3.8.0_tf_1.15-generic+cuda10.1/bin/python3
TensorFlow: 1.15.0 (v1.15.0-0-g590d6eef7e) (<site-package> in /work/tools/asr/python/3.8.0_tf_1.15-generic+cuda10.1/lib/python3.8/site-packages/tensorflow)
Use num_threads=1 (but min 2) via OMP_NUM_THREADS.
Setup TF inter and intra global thread pools, num_threads 2, session opts {'log_device_placement': False, 'device_count': {'GPU': 0}, 'intra_op_parallelism_threads': 2, 'inter_op_parallelism_threads': 2}.
CUDA_VISIBLE_DEVICES is not set.
Collecting TensorFlow device list...
Local devices available to TensorFlow:
  1/2: name: "/device:CPU:0"
       device_type: "CPU"
       memory_limit: 268435456
       locality {
       }
       incarnation: 16818851830520872332
  2/2: name: "/device:XLA_CPU:0"
       device_type: "XLA_CPU"
       memory_limit: 17179869184
       locality {
       }
       incarnation: 8076534450557308922
       physical_device_desc: "device: XLA_CPU device"
Train data:
  input: 9 x 1
  output: {'classes': (2, 1), 'data': (9, 2)}
  Task12AXDataset, sequences: 1000, frames: unknown
Dev data:
  Task12AXDataset, sequences: 100, frames: unknown
Device not set explicitly, and no GPU found.
Setup TF session with options {'log_device_placement': False, 'device_count': {'GPU': 0}} ...
DEPRECATION WARNING: Using num_inputs/num_ouputs instead of extern_data is deprecated and might be removed in future versions
This might be disallowed with a future behavior_version.
layer /'data': [B,T|'time:var:extern_data:data'[B],F|F'feature:data'(9)] float32
layer /'Resize': [B,T|'time:var:extern_data:data*2'[?],F|F'feature:data'(9)] float32
layer /'Conv1': [B,T|'Conv1:conv:s0'[B],F|F'Conv1:channel'(9)] float32
layer /'ConstantPad': [B,T|'1+Conv1:conv:s0+1'[?],F|F'Conv1:channel'(9)] float32
layer /'Conv2': [B,T|'Conv2:conv:s0'[B],F|F'Conv2:channel'(9)] float32
Exception creating layer /'add' of class CombineLayer with opts:
{'_name': 'add',
 '_network': <TFNetwork '' train=<tf.Tensor 'globals/train_flag:0' shape=() dtype=bool>>,
 'kind': 'add',
 'name': 'add',
 'network': <TFNetwork '' train=<tf.Tensor 'globals/train_flag:0' shape=() dtype=bool>>,
 'sources': [<ConvLayer 'Conv1' out_type=Data{[B,T|'Conv2:conv:s0'[B],F|F'Conv1:channel'(9)]}>,
             <ConvLayer 'Conv2' out_type=Data{[B,T|'Conv2:conv:s0'[B],F|F'Conv2:channel'(9)]}>]}
Unhandled exception <class 'AssertionError'> in thread <_MainThread(MainThread, started 140381654517504)>, proc 30634.

Thread current, main, <_MainThread(MainThread, started 140381654517504)>:
(Excluded thread.)
```

and 

```
EXCEPTION
Traceback (most recent call last):
  File "../../returnn/rnn.py", line 11, in <module>
    line: main()
    locals:
      main = <local> <function main at 0x7f6bf671b9d0>
  File "/u/dierkes/returnn/returnn/__main__.py", line 656, in main
    line: init(command_line_options=argv[1:])
    locals:
      init = <global> <function init at 0x7f6bf671b700>
      command_line_options = <not found>
      argv = <local> ['../../returnn/rnn.py', 'demo-tf-native-lstm.12ax.config'], _[0]: {len = 20}
  File "/u/dierkes/returnn/returnn/__main__.py", line 383, in init
    line: init_config(config_filename=config_filename, command_line_options=command_line_options, extra_updates=config_updates)
    locals:
      init_config = <global> <function init_config at 0x7f6bf6785e50>
      config_filename = <local> None
      command_line_options = <local> ['demo-tf-native-lstm.12ax.config'], _[0]: {len = 31}
      extra_updates = <not found>
      config_updates = <local> None
  File "/u/dierkes/returnn/returnn/__main__.py", line 109, in init_config
    line: config.load_file(fn)
    locals:
      config = <global> <returnn.config.Config object at 0x7f6c01f02220>
      config.load_file = <global> <bound method Config.load_file of <returnn.config.Config object at 0x7f6c01f02220>>
      fn = <local> 'demo-tf-native-lstm.12ax.config', len = 31
  File "/u/dierkes/returnn/returnn/config.py", line 74, in Config.load_file
    line: custom_exec(content, filename, user_ns, user_ns)
    locals:
      custom_exec = <local> <function custom_exec at 0x7f6bf6781a60>
      content = <local> '#!returnn.py\n# kate: syntax python;\n\nuse_tensorflow = True\n\nimport os\ndemo_name, _ = os.path.splitext(__file__)\nprint("Hello, experiment: %s" % demo_name)\n\ntask = "train"\ntrain = {"class": "Task12AXDataset", "num_seqs": 1000}\ndev = {"class": "Task12AXDataset", "num_seqs": 100, "fixed_..., len = 1372
      filename = <local> 'demo-tf-native-lstm.12ax.config', len = 31
      user_ns = <local> {'config': <returnn.config.Config object at 0x7f6c01f02220>, '__file__': 'demo-tf-native-lstm.12ax.config', '__name__': '__returnn_config__', '__package__': 'returnn', '__builtins__': {'__name__': 'builtins', '__doc__': "Built-in functions, exceptions, and other objects.\n\nNoteworthy: None is th..., len = 21
  File "/u/dierkes/returnn/returnn/util/basic.py", line 2171, in custom_exec
    line: eval(co, user_global_ns, user_ns)
    locals:
      eval = <builtin> <built-in function eval>
      co = <local> <code object <module> at 0x7f6bf6728f50, file "demo-tf-native-lstm.12ax.config", line 4>
      user_global_ns = <local> {'config': <returnn.config.Config object at 0x7f6c01f02220>, '__file__': 'demo-tf-native-lstm.12ax.config', '__name__': '__returnn_config__', '__package__': 'returnn', '__builtins__': {'__name__': 'builtins', '__doc__': "Built-in functions, exceptions, and other objects.\n\nNoteworthy: None is th..., len = 21
      user_ns = <local> {'config': <returnn.config.Config object at 0x7f6c01f02220>, '__file__': 'demo-tf-native-lstm.12ax.config', '__name__': '__returnn_config__', '__package__': 'returnn', '__builtins__': {'__name__': 'builtins', '__doc__': "Built-in functions, exceptions, and other objects.\n\nNoteworthy: None is th..., len = 21
  File "demo-tf-native-lstm.12ax.config", line 33, in <module>
    line: model = "/tmp/%s/returnn/%s/model" % (os.getlogin(), demo_name)  # https://github.com/tensorflow/tensorflow/issues/6537
    locals:
      model = <not found>
      os = <local> <module 'os' from '/work/tools/asr/python/3.8.0_tf_1.15-generic+cuda10.1/lib/python3.8/os.py'>
      os.getlogin = <local> <built-in function getlogin>
      demo_name = <local> 'demo-tf-native-lstm.12ax', len = 24
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by albertz** [comment]
I think we should detect this in `declare_same_as` and fix it there.

**Comment by albertz** [comment]
> > Is this the most simple reproduction case? Do you actually need Resize to reproduce the error? Or Conv1?
> 
> `resize` can be excluded, but then the dimensions at the softmax output layer are not correct anymore.

You mean for your specific test, for training. The test is anyway way too complicated. See other simple test cases. You don't need a full config. You don't need training. Just the net construction itself already triggers the problem.

**Comment by dierkes-j** [comment]
>I think we should detect this in declare_same_as and fix it there.

So I should try to check if `self` is an already existing dimension tag we don't overwrite it in `declare_same_as`?

**Comment by albertz** [comment]
If it is already the same, it should do nothing.

**Comment by dierkes-j** [comment]
Yes, but the problem is that in our case `self` is an existing dimension tag (the out dimension tag of `Conv1`) but not the same as `other`. So it doesn't do nothing

**Comment by albertz** [comment]
I just noticed, the exception stacktrace you provided above does not seem to be the correct one.

I also noticed, the log is not correct anymore for the exampe.

I also noticed, the test is still too complicated. You don't need any dataset (Task12AXDataset). You don't need a full config.

Can you provide more details on what the actual dim tags are?

From the log:

* `data`: 'time:var:extern_data:data'[B] = T1
* `Resize`: 'time:var:extern_data:data*2'[?] = T * 2 = T2
* `Conv1`: 'Conv1:conv:s0'[B] = ceildiv(T2, 2) = T3
* `ConstantPad`: '1+Conv1:conv:s0+1'[?] = 1 + T3 + 1
* `Conv2`: 'Conv2:conv:s0'[B] = -1 + 1 + T3 + 1 -1 = T3

The `declare_same_as` you mentioned, for which of those tags is it exactly executed?

**Comment by dierkes-j** [comment]
>I just noticed, the exception stacktrace you provided above does not seem to be the correct one.
I also noticed, the log is not correct anymore for the exampe.

Sorry for that. Should be fixed now.

The actual dim tags are:
- `data`: 'time:var:extern_data:data'[B] = T1
- `Conv1`: Conv1:conv:s0'[?] = T2
- `ConstantPad`: T|'1+Conv1:conv:s0+1'[?] = 1 + T2 + 1
- `Conv2`: Conv2:conv:s0'[B] = -1 + 1 + T2 + 1 - 1 = T2

The `declare_same_as` called in `get_out_data_from_opts` for the layer `Conv2` is called on the dimension  tag `Conv1:conv:s0` with input `Conv2:conv:s0'[?]`. E.g. `out_tag_calc.declare_same_as(out_tag)` with `out_tag_calc = Dim{'Conv1:conv:s0'[?]}` and `out_tag = Dim{'Conv2:conv:s0'[B]}`. As a result of this operation `calc_out_tag = Dim{'Conv2:conv:s0'[B]}`. I think this introduces the circle at the dim tag ancestry of  `Conv2:conv:s0'[?]` because now `Dim{'1+Conv1:conv:s0+1'[?]}.derived_from_tag` is `Dim{'Conv2:conv:s0'[B]}` again and not `Dim{'Conv1:conv:s0'[?]}` anymore as it was before `declare_same_as`

**Comment by albertz** [comment]
> * `Conv1`: Conv1:conv:s0'[?] = T2

More specifically, it should be T2 = ceildiv(T1, 2) != T1, right? Due to the striding.

> * `Dim{'Conv2:conv:s0'[B]}`.same_as is `Dim{'Conv2:conv:s0'[B]}`

Is this a typo?

Actually, now I realize this is not a circle for same_as but a circle due to derived_from_tag (or both combined).

We should first clarify how it should be.

* `'1+Conv1:conv:s0+1'[B]` should be derived from `Conv1:conv:s0`.

What we have:

* First `Conv2:conv:s0` is a new undefined dim (set as derived from `'1+Conv1:conv:s0+1'`), via `ConvLayer.get_out_data_from_opts`.
* Then we calculate `-1 + Dim{'1+Conv1:conv:s0+1'} - 1` which resolves to `Conv1:conv:s0`.
* Then we call `Dim{Conv1:conv:s0}.declare_same_as(Dim{Conv2:conv:s0})`. I think this introduces the problem.

We should understand and know exactly at what point the circle is introduced. I think as I described but we should verify that.

If it is indeed as I assumed, `Dim{Conv1:conv:s0}.declare_same_as(Dim{Conv2:conv:s0})`, then the problem is in `declare_same_as` because all other logic before was reasonable (there is no reason why this would have been wrong, right?).

So, what should `declare_same_as` do?

It should detect the circle already and then actually do the inverse for this case here, set `Dim{Conv2:conv:s0}.same_as` to `Dim{Conv1:conv:s0}`.

Or more generally, if the argument `other` is derived from `self`, it should do the reverse. However, if `self` is also derived from `other`, we should throw an exception. If we ever get to that exception, we can also handle it but this is not needed now.

**Comment by dierkes-j** [comment]
>>Dim{'Conv2:conv:s0'[B]}.same_as is Dim{'Conv2:conv:s0'[B]}

>Is this a typo?

No. `Dim{'Conv2:conv:s0'[B]}` and `Dim{'Conv2:conv:s0'[B]}.same_as` seem to have the same description but are different objects (their ids are also different). `Dim{'Conv2:conv:s0'[B]}.same_as` has the attribute `derived_from_tag` instead of the attribute `same_as`. I just checked the actual circle that is traversed in the method `Dim{'Conv2:conv:s0'[B]}.undefined()` (which throws the assertion) and it looks as follows:

1. `Dim{'Conv2:conv:s0'[B]}`
2. `Dim{'Conv2:conv:s0'[B]}.same_as` is `Dim{'Conv2:conv:s0'[B]}` (with different id than 1)
3. `Dim{'Conv2:conv:s0'[B]}.same_as` is `Dim{'Conv2:conv:s0'[B]}` (with different id than 1 and 2)
4. `Dim{'Conv2:conv:s0'[B]}.derived_from_tag` is `Dim{'1+Conv1:conv:s0+1'[B]}`base
5. `Dim{'1+Conv1:conv:s0+1'[B]}.same_as` is `Dim{'1+Conv1:conv:s0+1'[?]}`
6. `Dim{'1+Conv1:conv:s0+1'[?]}.derived_from_tag` is `Dim{'Conv2:conv:s0'[B]}` (same id as 2)

The dimension tag in 2. has both attributes `same_as` and also `derived_from_tag` which is `Dim{'time:var:extern_data:data'[B]}`. Due to the implementation of `Dim.undefined` we follow `same_as` however.

> More specifically, it should be T2 = ceildiv(T1, 2) != T1, right? Due to the striding.

Yes, I agree

>We should first clarify how it should be.
 '1+Conv1:conv:s0+1'[B] should be derived from Conv1:conv:s0.

I also agree

>If it is indeed as I assumed, Dim{Conv1:conv:s0}.declare_same_as(Dim{Conv2:conv:s0}), then the problem is in declare_same_as because all other logic before was reasonable (there is no reason why this would have been wrong, right?).

I am not exactly sure, but I think so as well.

>We should understand and know exactly at what point the circle is introduced. I think as I described but we should verify that.
Or more generally, if the argument other is derived from self, it should do the reverse.

Ok, sounds good. I will try to pinpoint where in `declare_same_as` this circle is introduced and will try to make such a dependency check between `self` and `other` and handle this case correctly. I will propose my solution via a PR so that we can discuss it again then.

**Comment by albertz** [comment]
> `Dim{'Conv2:conv:s0'[B]}` and `Dim{'Conv2:conv:s0'[B]}.same_as` seem to have the same description but are different objects (their ids are also different).

Ok, the way we refer to these objects here is then maybe misleading. I think when you refer to the `Dim.description` attrib, it should be more helpful. Because the `__repr__` will derive `same_as` and then uses that `description`. So when you want to differentiate between object instances, directly use the `description`, or sth else, so that we really can differentiate them here.

But also, I think the `same_as` logic is not really the problem, right? So we actually don't really need to differentiate different objects and it's fine when we always talk about the `same_as_base`, or what the `__repr__` shows. However, this could differ at different points in time. E.g. `Conv2:conv:s0` initially is different from `Conv1:conv:s0` but then after `declare_same_as` it becomes the same.

> > We should understand and know exactly at what point the circle is introduced. I think as I described but we should verify that.
> > Or more generally, if the argument `other` is derived from `self`, it should do the reverse.
> 
> Ok, sounds good. I will try to pinpoint where in `declare_same_as` this circle is introduced and will try to make such a dependency check between `self` and `other` and handle this case correctly. I will propose my solution via a PR so that we can discuss it again then.

Yes, but also see my next sentences, i.e. to check both ways, i.e. if `self` is also derived from `other`, we should throw an exception. If we ever get to that exception, we can also handle it but this is not needed now.

We might need to have a generic function which determines the order of `derived_from_tag`:

* if this is well defined, then potentially reverse the `declare_same_as` if needed, or if already fine, just go on in `declare_same_as`
* if not related to each other, just go on in `declare_same_as`
* if not well-defined but circular, throw exception for now

**Comment by albertz** [comment]
> We might need to have a generic function which determines the order of `derived_from_tag`:
> 
> * if this is well defined, then potentially reverse the `declare_same_as` if needed, or if already fine, just go on in `declare_same_as`
> * if not related to each other, just go on in `declare_same_as`
> * if not well-defined but circular, throw exception for now

Such function/algorithm could look like this:

Build up the set of tags you end up when you follow `same_as` + `derived_from_tag` (similar as in `Dim.undefined`). Maybe make that a function `Dim.get_derived_bases()` or so.

Now, in `declare_same_as`:
```python
self_derived_bases = self.get_derived_bases()
other_derived_bases = other.get_derived_bases()
if self_derived_bases.issubset(other_derived_bases):
  pass  # pass on
elif self_derived_bases.issuperset(other_derived_bases):
  # reverse
  return other.declare_same_as(self)
elif self_derived_bases.isdisjoint(other_derived_bases):
  pass  # pass on
else:
  raise Exception("%s declare_same_as %s: invalid derived bases" % (self, other))
```

**Comment by albertz** [comment]
Our change was to handle and fix the case `Dim{Conv1:conv:s0}.declare_same_as(Dim{Conv2:conv:s0})`, which should actually do the reverse, to not introduce a cycle for `derived_from_tag`.

Or in general, this change is to avoid the introduction of such a cycle on `derived_from_tag`. This is the main issue here. Cycles must not be introduced.

Now you talk about a different case, which is `Dim{'ceildiv_right(time:var:extern_data:data, 2)'[?]}.declare_same_as(Dim{'Conv1:conv:s0'[?]})`, which is called when `Conv1` is created.

But you are right that this case now highlights that we need to change or extend the logic.

I think you are also right that the `isdisjoint` check is not generic enough here.

Maybe actually we don't need to check `isdisjoint`? So simplify it to:
```python
self_derived_bases = self.get_derived_bases()
other_derived_bases = other.get_derived_bases()
if self_derived_bases.issubset(other_derived_bases):
  # Avoid cycles on derived_from_tag. https://github.com/rwth-i6/returnn/issues/1054
  return other.declare_same_as(self)  # reverse
  # In all other cases, this should not introduce a cycle, so pass on.
```

**Comment by dierkes-j** [comment]
Yes, this seems to work fine. I adjusted my PR #1055. This also fixes the issue https://github.com/rwth-i6/pytorch-to-returnn/issues/124
