### ISSUE TITLE
ctc alignment outputs are all zeros

### ISSUE THREAD

**Issue by jiangj-dc** [rwth-i6/returnn#1064]
When using "fast_bw" (FastBaumWelchLayer) to do the alignment, the outputs are all zeros. Here is the network config:

network = {
"lstm1_fw" : { "class" : "rec", "unit" : "lstmp", "n_out" : 512, "direction": 1, "from": "data" },
"lstm1_bw" : { "class" : "rec", "unit" : "lstmp", "n_out" : 512, "direction": -1, "from": "data" },

"lstm2_fw" : { "class" : "rec", "unit" : "lstmp", "n_out" : 512, "direction" : 1, "from" : [ "lstm1_fw", "lstm1_bw" ] },
"lstm2_bw" : { "class" : "rec", "unit" : "lstmp", "n_out" : 512, "direction" : -1, "from" : [ "lstm1_fw", "lstm1_bw" ] },

"lstm3_fw" : { "class" : "rec", "unit" : "lstmp", "n_out" : 512, "direction" : 1, "from" : [ "lstm2_fw", "lstm2_bw" ] },
"lstm3_bw" : { "class" : "rec", "unit" : "lstmp", "n_out" : 512, "direction" : -1, "from" : [ "lstm2_fw", "lstm2_bw" ] },

"lstm4_fw" : { "class" : "rec", "unit" : "lstmp", "n_out" : 512, "direction" : 1, "from" : [ "lstm3_fw", "lstm3_bw" ] },
"lstm4_bw" : { "class" : "rec", "unit" : "lstmp", "n_out" : 512, "direction" : -1, "from" : [ "lstm3_fw", "lstm3_bw" ] },

"output" : { "class" : "softmax", "loss" : "ctc", "from" : [ "lstm4_fw", "lstm4_bw" ], "loss_opts": {"beam_width": 1, "use_native": True} },

"align" : { "class" : "fast_bw", "align_target" : "ctc", "align_target_key" : "classes", "ctc_opts" : None, "input_type" : "prob", "from" : "output" },

"dumpout" : { "class" : "hdf_dump", "filename" : "results/alignment.hdf5", "from" : [ "align" ], "is_output_layer": True }
}

**Comment by albertz** [comment]
Why was this closed?

**Comment by jiangj-dc** [comment]
When I tried/debugged again, the fwdbwd outputs appeared to be correct. But I have no clue of what made the difference.

**Comment by albertz** [comment]
Btw, one reason that they can be all zero: When there is no possible alignment at all, e.g. when the target sequence is longer than the input sequence.
