### ISSUE TITLE
Remove dependency on Theano when running with TF

### ISSUE THREAD

**Issue by pavelgolik** [rwth-i6/returnn#107]
Right now we need to have Theano installed even if we want to use TF only. It would be nice to make this dependency optional so that we only need one of the two frameworks. Might be a simple matter of guarding some imports with `if BackendEngine.is_theano_selected()`, but may be I'm missing some larger context.

**Comment by JackTemaki** [comment]
I tried to check once where the dependencies are set. The first issue i came across (when just moving every theano import behind a guard) is that the Tensorflow variant uses functions of Network.py, which need NetworkBaseLayer.py, and there Theano is a necessary requirement. So i think the first way to go is to check which Network.py functions are needed for tensorflow, and move this to a separate file.

**Comment by albertz** [comment]
I guess you mean in `rnn.py`, right? We should maybe not globally import it there.

**Comment by albertz** [comment]
I think I removed all deps in `rnn.py`. But probably we have some more elsewhere.

**Comment by albertz** [comment]
Ok, it should now be removed. Please check. Reopen if there are other problems.
