### ISSUE TITLE
Suppress interactive progress bar during multi gpu batch training

### ISSUE THREAD

**Issue by michelwi** [rwth-i6/returnn#1080]
In the `Runner` class  in `tf/engine.py` the terminal width is used to determine whether or not an interactive progress bar should be displayed.
https://github.com/rwth-i6/returnn/blob/570a047372f8b5be978d7d3fd68077f57706fd2e/returnn/tf/engine.py#L127

For a single GPU batch job, the terminal_width evaluates to -1 and for an interactive run it is a finite positive number.
However, if a multi GPU job with Horovod and mpirun is started, both interactive and batch processing return a terminal_width of exactly 0. This means I get broken logs with progress par fragments inside.

We could change this line to check for `terminal_width > 0` and disable progress bars for all multi GPU trainings, or we change the logic that determines if we have an interactive session or not.

**Comment by albertz** [comment]
> However, if a multi GPU job with Horovod and mpirun is started, both interactive and batch processing return a terminal_width of exactly 0.

I wonder why that is. `terminal_size` seems to fail. But how does it fail? Is this our fault, or maybe some external things are wrong, like you have set the environment var `COLUMNS=0`?

> We could change this line to check for `terminal_width > 0`

I think this is anyway a good idea, as a width of 0 does not really make sense.

Our `is_tty` function already does this.

> we change the logic that determines if we have an interactive session or not.

How do you suggest to change it?

But anyway, for the progress bar, we need to know the terminal width, otherwise we can not really do it.

**Comment by michelwi** [comment]
>> we change the logic that determines if we have an interactive session or not.

> How do you suggest to change it?

I have no idea. A quick online search pointed me to https://docs.python.org/3/library/io.html#io.IOBase.isatty but idk if this is smarter then our function.

Anyway, #1082 already solved my major problem of unreadable log files for multi gpu training. Thanks.

**Comment by albertz** [comment]
> I have no idea. A quick online search pointed me to https://docs.python.org/3/library/io.html#io.IOBase.isatty but idk if this is smarter then our function.

We already have sth similar inside `terminal_size`, using `os.isatty` (I assume the same as `IOBase.isatty`).

But anyway, not so important if it works now.
