### ISSUE TITLE
Detect Horovod deadlocks

### ISSUE THREAD

**Issue by michelwi** [rwth-i6/returnn#1084]
During horovod multi gpu training, sometimes one of the workers crashes which makes the other workers/manager think a deadlock has happened. The training will then stop but the process continues to run and print error messages, e.g.
```
[2022-07-20 04:51:42.894382: W horovod/common/stall_inspector.cc:105] One or more tensors were submitted to be reduced, gathered or broadcasted by subset of ranks and are waiting for remainder of ranks for more than 60 seconds. This may indicate that different ranks are trying to submit different tensors or that only subset of ranks is submitting tensors, which will cause deadlock.
Stalled ranks:
2: [global_tensor_horovod_sum_have_data/HorovodAllreduce_globals_horovod_have_more_data_placeholder_0, global_tensor_horovod_sum_have_error/HorovodAllreduce_globals_horovod_have_error_placeholder_0]
```
This is related to / the same as https://github.com/rwth-i6/returnn/issues/323 but here I don't even want to fix the bug.
My problem is that the user has to manually check the logs from time to time to verify that such a situation has not happened and the training is progressing as expected.

Can we somehow detect within returnn that this situation has occurred and then (e.g. after a timeout) terminate the whole process so that the error may be detected by the SGE / sisyphus / or the user automatically?

**Comment by albertz** [comment]
> Can we somehow detect within returnn that this situation has occurred and then (e.g. after a timeout) terminate the whole process so that the error may be detected by the SGE / sisyphus / or the user automatically?

In principle, everything can be done. Surely this can be done. The obvious problem is, I'm not sure how easy it is to detect, and how reliable the detection would be.

**Comment by albertz** [comment]
Is the crashing process really exiting or hanging? Normally the MPI handler should detect if some process exited and then Horovod should notice and quit with an error. But here it sounds like sth got wrong. Either the crashing process is still hanging, or MPI somehow did not notice, or sth else.

**Comment by michelwi** [comment]
> Is this related to https://github.com/rwth-i6/returnn/issues/314?

yes, looks exactly the same. Some reasons I encountered were file server instabilities or a single GPU in the node breaking/having a hickup.

> The obvious problem is, I'm not sure how easy it is to detect, and how reliable the detection would be. Also, e.g. using a timeout is tricky, as I had cases where startup time was multiple minutes, while some other nodes where much faster.

yes.. the current situation is that we submit a training to the queue that we expect to take 2-3 weeks to complete. When we come back to check the progress we find that after e.g. 1 day of training some fileserver problem occurred and the training was stalled since then without progress.
Even a ridiculously long timeout (1h, 1day) would have made us aware of the situation earlier s owe could have restarted the training.

> Is the crashing process really exiting or hanging? Normally [...]

not sure. Sorry that I am not very specific here.

**Comment by albertz** [comment]
> > Is this related to #314?
> 
> yes, looks exactly the same.

Maybe we should then either close either this here or close #314 to have the information collected in one place.

> > Is the crashing process really exiting or hanging? Normally [...]
> 
> not sure. Sorry that I am not very specific here.

It would be helpful to find out. E.g. log on to the crashed node, and check the running processes, if that is still alive or not.

If there is a hanging process, the C stacktrace would also always be helpful (attach with GDB), and maybe also the Python stacktrace (send SIGUSR1 to it, via our signal handler, that should print it).

See also the documentation on debugging.

If it is not exiting but hanging, and we understand where and why it hangs, we should directly fix that, or do such hang detection in there. It is probably easier to detect this hang from within the process, and then just kill itself, and that exit should trigger also the other nodes to stop.

Btw, this Horovod stall check already has an option for timeout. I think you can set the environment variable `HOROVOD_STALL_SHUTDOWN_TIME_SECONDS`. So basically this is what you asked for here?
