### ISSUE TITLE
Change indentation to 4 spaces?

### ISSUE THREAD

**Issue by albertz** [rwth-i6/returnn#1156]
This was basically decided now for returnn-common: https://github.com/rwth-i6/returnn_common/issues/208

It probably also makes sense here.

Or are there any good arguments not to do this?

**Comment by albertz** [comment]
@JackTemaki @christophmluscher @curufinwe @michelwi @mmz33 opinions?

**Comment by JackTemaki** [comment]
Sounds good! Would be more standard, and then one less RETURNN specific setting in PyCharm compared to other projects.

**Comment by michelwi** [comment]
I don't have a strong opinion, but would vote for consistency to other projects. -> 4 spaces.

**Comment by braddockcg** [comment]
4 spaces, definitely.
