### ISSUE TITLE
Apply black?

### ISSUE THREAD

**Issue by albertz** [rwth-i6/returnn#1158]
Related to 4 space indent (#1156) is the question whether we want to have [Black](https://github.com/psf/black) applied (as a requirement) to the code, similar as in i6_core or i6_experiments ([i6_core CI test](https://github.com/rwth-i6/i6_core/blob/main/.github/workflows/black.yml)).

Use 120 character limit.

Same issue for returnn-common: https://github.com/rwth-i6/returnn_common/issues/230
And the PR for returnn-common: https://github.com/rwth-i6/returnn_common/pull/251

Once we do this, we should also update the wiki: https://github.com/rwth-i6/returnn/wiki/PyCharm-Configuration
https://black.readthedocs.io/en/stable/integrations/editors.html
Ignore E203: https://black.readthedocs.io/en/stable/faq.html#why-are-flake8-s-e203-and-w503-violated

**Comment by JackTemaki** [comment]
I think it makes life easier, but I also see it disadvantages in certain formatting cases. So from my experience with other projects:

Pro: 
 - never have style discussions again
 
 Contra:
  - Needed strict requirements for a fixed version to not cause test mismatches
  - There are (but very rare) cases where the enforced black style does not look good 
  
Also if we consider it, we definitely should go with the 120 character limit, everything shorter is a little annoying.

**Comment by albertz** [comment]
I was never such a big fan of Black but I also see this as a big advantage to remove some of the discussion on formatting, as it is annoying to always keep reminding people that they should stay consistent in formatting.

But it should be noted, this will not completely get rid of such discussions, as there are many aspects not covered by Black. E.g. variable names, but there are probably many other things.

**Comment by albertz** [comment]
> Also if we consider it, we definitely should go with the 120 character limit, everything shorter is a little annoying.

Yes sure.

**Comment by christophmluscher** [comment]
I would support black.
I agree. It does not get rid of all discussions but it reduces the discussions at least.

**Comment by albertz** [comment]
So I'm thinking now to just apply Black, which also fixes 4 spaces (#1156). Then also the same for returnn-common (https://github.com/rwth-i6/returnn_common/issues/230).

We can overtake the [CI action from i6_core for checking](https://github.com/rwth-i6/i6_core/blob/main/.github/workflows/black.yml), probably slightly adapted for the paths.

I wonder if there are any specific things we should take care before doing this?

**Comment by albertz** [comment]
This was done for returnn_common now. See https://github.com/rwth-i6/returnn_common/pull/251 for what changes were needed.
