### ISSUE TITLE
Collecting potentially unused code

### ISSUE THREAD

**Issue by JackTemaki** [rwth-i6/returnn#1172]
With the removal of Theano #1164 there is probably a lot of unnecessary code still remaining. I want to use this issue to collect all instance of code that need a closer look, and maybe start discussions about it. The overview list can be extended by altering this initial posting.

Potentially unused code:
 - [SprintInterface.py demo()](https://github.com/rwth-i6/returnn/blob/master/returnn/sprint/interface.py#L1025)
   - Probably has some Theano dependency, unclear if it needs rewrite or can be removed
 - https://github.com/rwth-i6/returnn/blob/master/returnn/native_op.py#L72
   - `destroy_map` is currently marked as unused
 - https://github.com/rwth-i6/returnn/blob/master/returnn/util/task_system.py
   - Probably many functions/classes are unused  
 - The `analyize_data` task has minimal Theano dependencies but was not removed yet.
   
Code already in discussion:
 - #1170 
 - #1171

**Comment by albertz** [comment]
I don't think it's helpful to have one issue to collect this. Instead, can you open separate issues on each individual separate aspect of things which can be removed?
