### ISSUE TITLE
`analyze_data` task has theano dependencies.

### ISSUE THREAD

**Issue by JackTemaki** [rwth-i6/returnn#1175]
It is currently unclear if there are more dependencies, but there at least was a Theano dependency via `inplace_increment`.

https://github.com/rwth-i6/returnn/blob/master/returnn/util/basic.py#L1540

Maybe we can completely remove this task? I am also not sure what the difference between the tasks `analyze`and `analyze_data` is, it is quite confusing to have both.

**Comment by albertz** [comment]
This dependency was removed.
