### ISSUE TITLE
Remove MDLSTM demo

### ISSUE THREAD

**Issue by JackTemaki** [rwth-i6/returnn#1181]
In #1164 all Theano dependent demos were removed except this one, as I did not notice it right away. I guess this can also be removed?

https://github.com/rwth-i6/returnn/tree/master/demos/mdlstm

**Comment by albertz** [comment]
I think some paper referred to this demo. I would keep it. Maybe add a README saying that this used the old Theano backend, and linking to the issue about dropping Theano.

**Comment by JackTemaki** [comment]
Resolved with https://github.com/rwth-i6/returnn/commit/67fda694eac7c10ff05a098690548dbcfc9ceef3
