### ISSUE TITLE
Remove `enforce_min_len1` parameter

### ISSUE THREAD

**Issue by JackTemaki** [rwth-i6/returnn#1188]
It seems this parameter and related code were only needed for Theano, and it has no effect with Tensorflow.

See:
https://github.com/rwth-i6/returnn/blob/master/returnn/datasets/basic.py#L1359

**Comment by albertz** [comment]
It has an effect for TF. It's all implemented for that as well.

It depends on your network. I think it's not really well tested for size 0 and likely will break, so the option might be useful.

But then I think it never happens in practice. I'm not sure. For AED models, we always append EOS. Maybe for transducer models and full-sum training.

I'm not sure if there are users who use this.

**Comment by JackTemaki** [comment]
> It has an effect for TF

Ah I read `if not extern_data or enforce_min_len1` as `if not extern_data and enforce_min_len1`, never mind.
