### ISSUE TITLE
LMDataset output size

### ISSUE THREAD

**Issue by JackTemaki** [rwth-i6/returnn#1245]
I found a small nuisance while working on the LM pipeline. In the `LmDataset` we define the number of outputs based on the length of label list (`num_labels = len(self.labels["data"])`) instead of the length of the indices. But our LM vocabularies usually start like:

```
<sb> 0
<s> 0
</s> 0
THE 1
AND 2
OF 3
[...]
```

So in this case the output size will be too large by 2 entries. Kazuki did just remove `<s>` and `</s>` from the vocab for RETURNN training and set start and end token to `<sb>` instead of `<s>` and `</s>`  as a workaround, but I consider this to be quite ugly making the pipeline more inconsistent.

Any idea how this can be fixed without breaking the behavior?

**Comment by albertz** [comment]
We always have `labels` as a list, with `len(labels) == num_labels`. If this is not the case, there is a bug in `labels`. We must have this, as we often use `labels[label_idx]`, e.g. for serialization.

This implies that there can only be one label in `labels` per index. However, in the vocab you can have multiple.

So the bug rather seems to be this:
```python
self.labels["data"] = list(self.orth_symbols)
```
And related code.

**Comment by JackTemaki** [comment]
I got the point. For the `Vocabulary` class we do:

```python
 labels = {idx: label for (label, idx) in sorted(d.items())}
 [...]
  self._labels = [label for (idx, label) in sorted(labels.items())]
```
which is making the mapping bijective...

Will do the same for the LM dataset.
