### ISSUE TITLE
layer.output.placeholder is suddenly `None`

### ISSUE THREAD

**Issue by JackTemaki** [rwth-i6/returnn#1252]
I have a case where during network construction the placeholder of a layer that was correctly constructed suddenly is `None` when another layer wants to access it during construction.

I am not providing the full stacktrace yet as I am still debugging. I confirmed with the PyCharm debugger that the source layer is initialized correctly, and that it is really the same Data object that gets accessed in the layer where the placeholder is None. Unfortunately PyCharm allows only for variable watches (which confirms it is the same placeholder variable I am looking at), but does not support automatically detecting changes. 

I will write updates here once I find more.

A short depiction of the case is:
```python
[...]
  File "/u/rossenbach/src/returnn/returnn/tf/network.py", line 1206, in TFNetwork._create_layer
    line: layer = layer_class(**layer_desc)
    locals:
      layer = <not found>
      layer_class = <local> <class 'returnn.tf.layers.basic.RangeFromLengthLayer'>
      layer_desc = <local> {'out_spatial_dim': Dim{'stft:conv:s0'[B]}, 'out_shape': {ImplicitDynSizeDim(Dim{B}), Dim{'stft:conv:s0'[B]}}, '_network': <TFNetwork '/upsamling' parent_layer=<InternalLayer 'upsamlin
g' out_type=Data{[B]}> train=<tf.Tensor 'globals/train_flag:0' shape=() dtype=bool>>, '_name': 'range_from_length..., len = 8
  File "/u/rossenbach/src/returnn/returnn/tf/layers/basic.py", line 2986, in RangeFromLengthLayer.__init__
    line: out = tf.range(0, tf.reduce_max(source.placeholder), dtype=dtype)
    locals:
      out = <not found>
      tf = <global> <module 'tensorflow' from '/work/tools/asr/python/3.8.0_tf_2.3.4-haswell+cuda10.1+mkl/lib/python3.8/site-packages/tensorflow/__init__.py'>
      tf.range = <global> <function range at 0x7fa0750935e0>
      tf.reduce_max = <global> <function reduce_max at 0x7fa07509e160>
      source = <local> Data{'cast_0_output', [B], dtype='int32'}
      source.placeholder = <local> None
      dtype = <local> 'int32'
[...]
```

**Comment by albertz** [comment]
I guess you can systematically bisect this (finding places where it is still set and where it is None, and then surround it more and more).

Some assumption: `RangeFromLengthLayer` (or some other related layer) probably makes this also a dimension tag. Esp the output dim tag of that layer will be the dim tag from the source. And that dim tag will have the `dyn_size_ext` set exactly to this `Data` instance (or a copy of it -- but maybe not a copy but really this instance). Then there is some logic in `Dim` which updates or maybe resets some of the `dyn_size_ext` under certain conditions. This might have reset `placeholder` to None.

If this assumption is true, there are maybe/probably two bugs:

* It should not be the instance itself when it is used as `dyn_size_ext`, but a copy of it. This should be changed in any case. Such bugs with such strange side effects are really annoying.
* The reset logic might be incorrect here. I'm not sure why `placeholder` is reset to None here.

**Comment by JackTemaki** [comment]
Yes your assumption is true, I already progressed a little bit and found the placeholder is resetted at:
```python3
    if out_spatial_dim:
      dim_tag.declare_same_as(out_spatial_dim)
```

Of the ` get_out_data_from_opts` function of the affected `RangeFromLengthLayer`

I used the exact same model before (generated via returnn-common), but the spatial dim in question now comes from another layer and not extern_data, so I guess this is how this bug appears now.

I am checking now for both of your possible bugs.

**Comment by JackTemaki** [comment]
Okay yes, looking at the code it is quite obvious:

```python3
    if not dim_tag:
      dim_tag = Dim(
        kind=Dim.Types.Spatial, description="%s_input_len" % name, auto_generated=True,
        batch=source.batch, control_flow_ctx=source.control_flow_ctx,
        dyn_size_ext=source)  # <- here we are setting the source as dyn_size_ext
      if source.placeholder is not None:
        dim_tag.set_tag_on_size_tensor(source.placeholder)
    if out_spatial_dim:
      dim_tag.declare_same_as(out_spatial_dim) # <- here we set dyn_size_ext.placeholder = None
 ```

**Comment by albertz** [comment]
```python
      dim_tag = Dim(
        kind=Dim.Types.Spatial, description="%s_input_len" % name, auto_generated=True,
        batch=source.batch, control_flow_ctx=source.control_flow_ctx,
        dyn_size_ext=source)
```
Here it should be `dyn_size_ext=source.copy()` instead.
You might want to check similar wrong usages of the `Dim` constructor. I think rightclick on `dyn_size_ext` -> Find usages should give you all relevant usages.
Or maybe, we actually also could change the `Dim` constructor itself, that it always makes a copy inside.

**Comment by albertz** [comment]
Changing this to copy, this will fix my first point.

For the second point, you need to debug step through `declare_same_as` and find the problem.

**Comment by JackTemaki** [comment]
> Changing this to copy, this will fix my first point.
> 
> For the second point, you need to debug step through `declare_same_as` and find the problem.

Already did, this is:
```python3
    if other_same_base.derived_from_op:
      # Cleanup everything, esp potential already computed sizes, as these might be invalid.
      for dim_ in [self_same_as, self] + list(self._same_for_batch_ctx.values()):
        if dim_.dyn_size_ext:
          dim_.dyn_size_ext.placeholder = None
```

**Comment by albertz** [comment]
I see. `declare_same_as` further should reset it again though, I think? I mean that `dim_tag.dyn_size_ext.placeholder` is set again? Not sure.

Well, in any case, maybe my second point is not really a bug. I would say this is more this problem: #975

**Comment by JackTemaki** [comment]
For me this poses no direct problem now, as I can simply replace:
```python3
t, _ = nn.range_from_length(l, out_spatial_dim=out_time_axis)  # [B,T]
```
with 
```python3
t, temp_out_time_axis = nn.range_from_length(l)
t, _ = nn.reinterpret_new_dim(t, in_dim=temp_out_time_axis, out_dim=out_time_axis)
```
in my model code.

What would you suggest to do now with this issue? Waiting for #975?

**Comment by albertz** [comment]
I don't understand? Why do you want to put any workaround into your code, instead of just fixing this here? You can anyway fix my first point, as I described, which should fix the problem for you, and leave the second point to #975.

**Comment by JackTemaki** [comment]
>  You can anyway fix my first point, as I described

I can fix this, but this did not fix the problem that then this placeholder ist still `None`.

It will then fail at the init with:
```python3
    if not self.output.dim_tags[0].is_batch_dim():
      assert source.placeholder is self.output.dim_tags[0].dyn_size_ext.placeholder
 ```
 
 The only way I got it to work was:
  - not passing `dyn_size_ext` at all so that `declare_same_as` builds it new.
  - removing the assert
  
 And I was quite sure this is not the intended solution.

**Comment by albertz** [comment]
> > You can anyway fix my first point, as I described
> 
> I can fix this, but this did not fix the problem that then this placeholder ist still `None`.

How? What exactly did you change? This can't be. Or there is yet another bug somewhere else.


> It will then fail at the init with:
> 
> ```python
>     if not self.output.dim_tags[0].is_batch_dim():
>       assert source.placeholder is self.output.dim_tags[0].dyn_size_ext.placeholder
> ```

But this is another thing. It is not `None` here, right? So it's yet another problem here.

> removing the assert. And I was quite sure this is not the intended solution.

Why? I'm actually thinking now, maybe this is a valid case where the assert does not make sense?

I wonder a bit, why exactly do you get different placeholders here? Maybe it shouldn't be the case. Again yet another problem. I think there are (might be) valid cases where `declare_same_as` results in a different placeholder.


Btw, in your code, why do you actually explicitly provide `out_spatial_dim=out_time_axis`? If you already have the dim (`out_time_axis`), there is `RangeInAxisLayer`/`nn.range_over_dim` for this instead.

**Comment by JackTemaki** [comment]
> > > You can anyway fix my first point, as I described
> > 
> > 
> > I can fix this, but this did not fix the problem that then this placeholder ist still `None`.
> 
> How? What exactly did you change? This can't be. Or there is yet another bug somewhere else.
> 
> > It will then fail at the init with:
> > ```python
> >     if not self.output.dim_tags[0].is_batch_dim():
> >       assert source.placeholder is self.output.dim_tags[0].dyn_size_ext.placeholder
> > ```
> 
> But this is another thing. It is not `None` here, right? So it's yet another problem here.
> 

`source.placeholder` is correct when fixing the copy issue, but `self.output.dim_tags[0].dyn_size_ext.placeholder` is still `None` then.

> > removing the assert. And I was quite sure this is not the intended solution.
> 
> Why? I'm actually thinking now, maybe this is a valid case where the assert does not make sense?
> 

I can not sufficiently evaluate this.

> I wonder a bit, why exactly do you get different placeholders here? Maybe it shouldn't be the case. Again yet another problem. I think there are (might be) valid cases where `declare_same_as` results in a different placeholder.
> 

I do not understand the reason for the `declare_same_as` logic so I can not answer this question.

> Btw, in your code, why do you actually explicitly provide `out_spatial_dim=out_time_axis`? If you already have the dim (`out_time_axis`), there is `RangeInAxisLayer`/`nn.range_over_dim` for this instead.

The original code was:
```python3
        l = nn.reduce(durations, mode="sum", axis=time_dim, use_time_mask=True)  # [B]
        l = nn.cast(l, dtype="int32")

        out_time_axis = target_time_dim if target_time_dim else nn.SpatialDim("upsampling_time")
        t, _ = nn.range_from_length(l, out_spatial_dim=out_time_axis)  # [B,T]
```
Where `target_time_dim` was the true external data time during training and `None` during generation. I think it makes sense to write it like this then.

**Comment by albertz** [comment]
> > > > You can anyway fix my first point, as I described
> > > 
> > > 
> > > I can fix this, but this did not fix the problem that then this placeholder ist still `None`.
> > 
> > 
> > How? What exactly did you change? This can't be. Or there is yet another bug somewhere else.
> > > It will then fail at the init with:
> > > ```python
> > >     if not self.output.dim_tags[0].is_batch_dim():
> > >       assert source.placeholder is self.output.dim_tags[0].dyn_size_ext.placeholder
> > > ```
> > 
> > 
> > But this is another thing. It is not `None` here, right? So it's yet another problem here.
> 
> `source.placeholder` is correct when fixing the copy issue, but `self.output.dim_tags[0].dyn_size_ext.placeholder` is still `None` then.

But this is not a problem in principle. `dyn_size_ext.placeholder` is allowed to be `None`. There is some logic (via `complete_dyn_size`) to automatically generate it when needed.

(Unfortunately, all of this is not really properly well defined, e.g. whether it really can be None in all cases. Because in practice, it rarely is None, I think. Unless in template construction... See #975.)

> > > removing the assert. And I was quite sure this is not the intended solution.
> > 
> > Why? I'm actually thinking now, maybe this is a valid case where the assert does not make sense?
> 
> I can not sufficiently evaluate this.

Well, I'm also not sure.

I'm just a bit confused that the `declare_same_as` results in `dyn_size_ext.placeholder` being None. This is unexpected to me.

> > I wonder a bit, why exactly do you get different placeholders here? Maybe it shouldn't be the case. Again yet another problem. I think there are (might be) valid cases where `declare_same_as` results in a different placeholder.
> 
> I do not understand the reason for the `declare_same_as` logic so I can not answer this question.

What don't you understand about the logic? `a.declare_same_as(b)` just makes that `a == b`. That's all. There shouldn't be any complicated logic. (You might argue, but there is, and I think that there does not need to be, and the current implementation should be fixed and simplified. It's like it is because of historical reasons. It evolved this way. But that's why we have #975. It really should not be complicated.)

Let's ignore the current actual implementation of `declare_same_as` in any case. Just think about, what would you expect? If this is not clear (ambiguous) in some case, then this is a problem. We should avoid having any possible ambiguity. It should always be unambiguous.

> > Btw, in your code, why do you actually explicitly provide `out_spatial_dim=out_time_axis`? If you already have the dim (`out_time_axis`), there is `RangeInAxisLayer`/`nn.range_over_dim` for this instead.
> 
> The original code was:
> 
> ```python
>         l = nn.reduce(durations, mode="sum", axis=time_dim, use_time_mask=True)  # [B]
>         l = nn.cast(l, dtype="int32")
> 
>         out_time_axis = target_time_dim if target_time_dim else nn.SpatialDim("upsampling_time")
>         t, _ = nn.range_from_length(l, out_spatial_dim=out_time_axis)  # [B,T]
> ```
> 
> Where `target_time_dim` was the true external data time during training and `None` during generation. I think it makes sense to write it like this then.

I would write it this way:
```python
if target_time_dim:
  out_time_axis = target_time_dim
else:
  l = nn.reduce(durations, mode="sum", axis=time_dim)  # [B]
  l = nn.cast(l, dtype="int32")
  out_time_axis = nn.make_dim_from_length(l)
t = nn.range_over_dim(out_time_axis)  # [B,T]
```

In your code, you have a problem:
`l` is now defined via those other layers, but `target_time_dim` probably also has some sizes, coming from the dataset. So what behavior do you actually expect?

* Should it check that `l` and `target_time_dim` are the same? If not, throw an error? Do this in every mini batch?
* Should it use `l` or the sizes from `target_time_dim`?
* Should it overwrite the sizes of `target_time_dim` with those by `l`?

Maybe you have some opinion that there is a clear unambiguous behavior which you would expect here. I would argue, at the very least this is a bit ambiguous. Note that this is actually #1141.

I think what the current RETURNN behavior does for your code is: It will ignore `l` and just use `target_time_dim`. This should be handled in `dim_tag.declare_same_as(out_spatial_dim)`. This is for the resulting dim tag of `range_from_length`. However, the actual tensor `t` might use `l`, I think. This is even a bit inconsistent.

But I would not really trust this, but rather say this is undefined behavior of RETURNN. Because we never really properly defined this. (This is somewhat also what #975 is about.)

I would maybe argue, we either should make this unambiguous, such that the user must be explicit about it. Or otherwise just disallow such ambiguity. I.e. disallow `nn.range_from_length` for any dim tag which is not already the same as the length. I.e. not have any implicit or automatic `declare_same_as`.

**Comment by JackTemaki** [comment]
> > > > > You can anyway fix my first point, as I described
> > > > 
> > > > 
> > > > I can fix this, but this did not fix the problem that then this placeholder ist still `None`.
> > > 
> > > 
> > > How? What exactly did you change? This can't be. Or there is yet another bug somewhere else.
> > > > It will then fail at the init with:
> > > > ```python
> > > >     if not self.output.dim_tags[0].is_batch_dim():
> > > >       assert source.placeholder is self.output.dim_tags[0].dyn_size_ext.placeholder
> > > > ```
> > > 
> > > 
> > > But this is another thing. It is not `None` here, right? So it's yet another problem here.
> > 
> > 
> > `source.placeholder` is correct when fixing the copy issue, but `self.output.dim_tags[0].dyn_size_ext.placeholder` is still `None` then.
> 
> But this is not a problem in principle. `dyn_size_ext.placeholder` is allowed to be `None`. There is some logic (via `complete_dyn_size`) to automatically generate it when needed.
> 
> (Unfortunately, all of this is not really properly well defined, e.g. whether it really can be None in all cases. Because in practice, it rarely is None, I think. Unless in template construction... See #975.)
> 
> > > > removing the assert. And I was quite sure this is not the intended solution.
> > > 
> > > 
> > > Why? I'm actually thinking now, maybe this is a valid case where the assert does not make sense?
> > 
> > 
> > I can not sufficiently evaluate this.
> 
> Well, I'm also not sure.
> 
> I'm just a bit confused that the `declare_same_as` results in `dyn_size_ext.placeholder` being None. This is unexpected to me.

Okay lets keep this aside because it seems we should redefine `declare_same_as` anyways.

> 
> > > I wonder a bit, why exactly do you get different placeholders here? Maybe it shouldn't be the case. Again yet another problem. I think there are (might be) valid cases where `declare_same_as` results in a different placeholder.
> > 
> > 
> > I do not understand the reason for the `declare_same_as` logic so I can not answer this question.
> 
> What don't you understand about the logic? `a.declare_same_as(b)` just makes that `a == b`. That's all. There shouldn't be any complicated logic. (You might argue, but there is, and I think that there does not need to be, and the current implementation should be fixed and simplified. It's like it is because of historical reasons. It evolved this way. But that's why we have #975. It really should not be complicated.)
> 
> Let's ignore the current actual implementation of `declare_same_as` in any case. Just think about, what would you expect? If this is not clear (ambiguous) in some case, then this is a problem. We should avoid having any possible ambiguity. It should always be unambiguous.

I would expect that as you say, after `a.declare_same_as(b)` we have a == b.  The question is if the actual compatibility should be checked or not. In my code case I wanted to tell RETURNN that the shapes are actually matching, and if this can not be verified statically this should also be verified by a runtime check. Then it also does not matter if the size_placeholder comes from a or b, because they should be equivalent. I think this is the most typical use-case, where as user you want to say "I know those two are matching, so please treat them as equal".

> 
> > > Btw, in your code, why do you actually explicitly provide `out_spatial_dim=out_time_axis`? If you already have the dim (`out_time_axis`), there is `RangeInAxisLayer`/`nn.range_over_dim` for this instead.
> > 
> > 
> > The original code was:
> > ```python
> >         l = nn.reduce(durations, mode="sum", axis=time_dim, use_time_mask=True)  # [B]
> >         l = nn.cast(l, dtype="int32")
> > 
> >         out_time_axis = target_time_dim if target_time_dim else nn.SpatialDim("upsampling_time")
> >         t, _ = nn.range_from_length(l, out_spatial_dim=out_time_axis)  # [B,T]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Where `target_time_dim` was the true external data time during training and `None` during generation. I think it makes sense to write it like this then.
> 
> I would write it this way:
> 
> ```python
> if target_time_dim:
>   out_time_axis = target_time_dim
> else:
>   l = nn.reduce(durations, mode="sum", axis=time_dim)  # [B]
>   l = nn.cast(l, dtype="int32")
>   out_time_axis = nn.make_dim_from_length(l)
> t = nn.range_over_dim(out_time_axis)  # [B,T]
> ```
> 
> In your code, you have a problem: `l` is now defined via those other layers, but `target_time_dim` probably also has some sizes, coming from the dataset. So what behavior do you actually expect?

This case:

>     * Should it check that `l` and `target_time_dim` are the same? If not, throw an error? Do this in every mini batch?

Those should be done very explicitly if you really want that:

>     * Should it use `l` or the sizes from `target_time_dim`?
> 
>     * Should it overwrite the sizes of `target_time_dim` with those by `l`?
> 
> 
> Maybe you have some opinion that there is a clear unambiguous behavior which you would expect here. I would argue, at the very least this is a bit ambiguous. Note that this is actually #1141.
> 
> I think what the current RETURNN behavior does for your code is: It will ignore `l` and just use `target_time_dim`. This should be handled in `dim_tag.declare_same_as(out_spatial_dim)`. This is for the resulting dim tag of `range_from_length`. However, the actual tensor `t` might use `l`, I think. This is even a bit inconsistent.
> 
> But I would not really trust this, but rather say this is undefined behavior of RETURNN. Because we never really properly defined this. (This is somewhat also what #975 is about.)
> 
> I would maybe argue, we either should make this unambiguous, such that the user must be explicit about it. Or otherwise just disallow such ambiguity. I.e. disallow `nn.range_from_length` for any dim tag which is not already the same as the length. I.e. not have any implicit or automatic `declare_same_as`.

If the default `declare_same_as` assumes equality and does a full runtime check it would be okay to still use that. I wrote my code with the though "I just want to tell this function I already know its output dim, so take the existing one". This was my understanding on how it works, so the most intuitive way to reach my goal.

**Comment by albertz** [comment]
> > Let's ignore the current actual implementation of `declare_same_as` in any case. Just think about, what would you expect? If this is not clear (ambiguous) in some case, then this is a problem. We should avoid having any possible ambiguity. It should always be unambiguous.
> 
> I would expect that as you say, after `a.declare_same_as(b)` we have a == b.

But you have to realize this leaves a lot of relevant details undefined.

This simple rule, that we have `a == b` afterwards, is trivially true. This is via the `same_as` flag, which is set afterwards.

However, there are many details inside of the `Dim` object. E.g. `a.dyn_size_ext` does not need to be the same as `b.dyn_size_ext`, or the placeholders don't need to be the same, etc. Also the `batch` flag, or the control flow context.

> The question is if the actual compatibility should be checked or not. In my code case I wanted to tell RETURNN that the shapes are actually matching, and if this can not be verified statically this should also be verified by a runtime check. Then it also does not matter if the size_placeholder comes from a or b, because they should be equivalent. I think this is the most typical use-case, where as user you want to say "I know those two are matching, so please treat them as equal".

But a runtime checks means some overhead in each single step. The overhead should be small (but I don't really know, maybe it triggers some GPU->CPU copy, which is slow, even if it is only for a few integers), but nevertheless, there is a small overhead, and I'm not sure if this is obvious to the user, that a call to `declare_same_as` will add such a runtime check and thus adds some small overhead. I think I would not really expect this.

Also, in most cases when `declare_same_as` is called, we don't really have this case. We have that either `a` or `b` or even both are still completely undefined. It's actually quite rare (and thus also not well tested) that both `a` and `b` are set. Btw, #1141 is exactly about that case, even though I think the current warning is not triggered in all cases. And in #1141, the conclusion was to just simply disallow this.

I still prefer to make this more explicit. But not really sure how or where. Those `declare_same_as` are often not directly called by the user but somewhere inside of RETURNN, e.g. in `get_out_data_from_opts`.

Maybe I would simply disallow it (as argued in #1141), and the user simply is not allowed to merge two different dim tags. And if the user wishes to add some explicit runtime check, the user just can do so by himself. Sth like:
```python
nn.assert(nn.length(out_time_axis) == nn.length(target_time_dim))
```

**Comment by JackTemaki** [comment]
> Maybe I would simply disallow it (as argued in #1141), and the user simply is not allowed to merge two different dim tags. And if the user wishes to add some explicit runtime check, the user just can do so by himself. Sth like:
> 
> ```python
> nn.assert(nn.length(out_time_axis) == nn.length(target_time_dim))
> ```

Okay to keep this discussion short: This would be a viable option for me, meaning that you always have to use a `nn.reinterpret_new_dim` to actually replace the dimension tag with the one wanted, instead of declaring them the same. I currently have only one single `nn.declare_same_as` in my RC code, which can easily be replaced. So if there is the possibility to remove`declare_same_as` from RETURNN altogether, this would be good.

**Comment by albertz** [comment]
I think my code makes more sense, but you could also use `reinterpret_new_dim`.

**Comment by JackTemaki** [comment]
> I think my code makes more sense, but you could also use `reinterpret_new_dim`.

I meant this in general, not for my specific case here.

**Comment by albertz** [comment]
Yes I also mean in general. There is only very very rare use for `reinterpret_new_dim`. Almost in all cases, you would use sth like my code.

**Comment by albertz** [comment]
Btw, `declare_same_as` runtime checks, this is #1200.
But as discussed in #975, maybe we should remove `declare_same_as`.
