### ISSUE TITLE
Batch dim not defined for PyTorch backend

### ISSUE THREAD

**Issue by JackTemaki** [rwth-i6/returnn#1303]
I tried to solve some error related to an unset Batch Dimension, but it is unclear what should actually be set. Currently neither `.dimension` or `.dyn_size_ext` is set.

So for a single update step, should this be static (an integer) or marked as dynamic (and then set e.g. from `TorchSize`)? It is unclear to me if this was intentionally left out (I do not see a reason why though), or if this is an error and should be set to one of those two variants. I would say `dyn_size_ext` should be a torch tensor on the target device, but I wanted to confirm beforehand.

**Comment by JackTemaki** [comment]
I will first go with setting a static `.dimension` and we can check better options later.

**Comment by albertz** [comment]
I'm not really sure I understand the problem. Can you give some example, some code which leads to an error?

Is this about the RF? If not, if this is about pure PT code, why do you even care?

The batch dim was unfortunately often treated in a special way, with different behavior to other dims. We also have this `batch` attrib, and the `BatchInfo` object, to give more meta information about the batch-dim (and potential extended variants, including beam or whatever). That's why the batch dim originally did not had a `dyn_size_ext` but accessing its value (e.g. `Dim.get_dim_value()`) had a special case for the batch dim.

In case of the RF, I don't want to use this really. We probably would set `dyn_size_ext` in all cases to have some consistent logic. I already do that in some cases now.

**Comment by JackTemaki** [comment]
> I'm not really sure I understand the problem. Can you give some example, some code which leads to an error?
> 
I think the actual problem is not at all relevant/helpful here. In `_run_step`  in `extern_data` for any `Tensor` and `batch_dim` both `.dimension` and `dyn_size_ext` are not set, this is what is relevant.

> Is this about the RF? If not, if this is about pure PT code, why do you even care?
> 

Lets for simplicity assume this is for RF. But as RF is now a core part of the engine, also for pure PT code this now became unfortunately relevant.

> The batch dim was unfortunately often treated in a special way, with different behavior to other dims. We also have this `batch` attrib, and the `BatchInfo` object, to give more meta information about the batch-dim (and potential extended variants, including beam or whatever). That's why the batch dim originally did not had a `dyn_size_ext` but accessing its value (e.g. `Dim.get_dim_value()`) had a special case for the batch dim.
> 

Seems to me this special treatement is not really relevant for the PyTorch Backend or RF in general then.

> In case of the RF, I don't want to use this really. We probably would set `dyn_size_ext` in all cases to have some consistent logic. I already do that in some cases now.

Okay, this answers my question.

**Comment by albertz** [comment]
> But as RF is now a core part of the engine, also for pure PT code this now became unfortunately relevant.

No, this is not true. RF is not a core part in case you use pure PT code. Sth is wrong then. RF is actually totally irrelevant for pure PT code. I'm not really sure why you think it is relevant.

> In `_run_step` in `extern_data` for any `Tensor` and `batch_dim` both `.dimension` and `dyn_size_ext` are not set, this is what is relevant.

I don't really see how that is relevant, depending on what you do. It should not be relevant for pure PT code. It sounds like there is actually another underlying problem, but I cannot really say that when you do not want to share details.

I think we should rather fix the underlying, maybe unrelated problem. Whatever you do here sounds more like a wrong workaround.

As usual, it would be good to have an actual test case which currently breaks. Pure PT code should not be affected by any of that logic, so sth sounds wrong/buggy/broken when this is not the case.

**Comment by JackTemaki** [comment]
> No, this is not true. RF is not a core part in case you use pure PT code. Sth is wrong then. RF is actually totally irrelevant for pure PT code. I'm not really sure why you think it is relevant.

Okay, maybe this is a terminology issue. This is not about RF, but about `TensorDict`, `Tensor` and `Dim`.

> Whatever you do here sounds more like a wrong workaround

As I am not able to even create a `Tensor` that has no dimensions in order to set `dyn_size_ext` for a batch_dimension, yes I give up. But this exactly what I complained about in #1120, why not keep it simple? It is really annoying when we can not solve one simple bug without your help, because we do not understand either the code or what is actually intended.

Now to the actual error:

```python
  File "/u/rossenbach/src/returnn/returnn/torch/engine.py", line 268, in Engine._run_step
    line: self._train_step_func(model=self._model, extern_data=extern_data, **sentinel_kw)
    locals:
      self = <local> <returnn.torch.engine.Engine object at 0x7f9c749178e0>
      self._train_step_func = <local> <function train_step at 0x7f9d381293f0>
      model = <not found>
      self._model = <local> Model(
                              (blstm1): LSTM(50, 1024, bidirectional=True)
                              (blstm_stack): LSTM(2048, 1024, num_layers=7, bidirectional=True)
                              (final_linear): Linear(in_features=2048, out_features=12001, bias=True)
                            )
      extern_data = <local> TensorDict({'data': Tensor{'data', [B?,T|'time:var-unk:data'[B?],F|F'feature:data'(50)]}, 'classes': Tensor{'classes', [B?,T|'time:var-unk:classes'[B?]], dtype='int64', sparse_dim=Dim{F'classes:sparse-dim'(12001)}}})
      sentinel_kw = <local> {'__fwd_compatible_random_arg_72': None}
  File "/u/rossenbach/experiments/tts_asr_2023/recipe/i6_experiments/users/rossenbach/experiments/librispeech/librispeech_100_hybrid/pytorch_networks/blstm8x1024_custom_engine.py", line 102, in train_step
    line: data = extern_data.as_raw_tensor_dict()
    locals:
      data = <not found>
      extern_data = <local> TensorDict({'data': Tensor{'data', [B?,T|'time:var-unk:data'[B?],F|F'feature:data'(50)]}, 'classes': Tensor{'classes', [B?,T|'time:var-unk:classes'[B?]], dtype='int64', sparse_dim=Dim{F'classes:sparse-dim'(12001)}}})
      extern_data.as_raw_tensor_dict = <local> <bound method TensorDict.as_raw_tensor_dict of TensorDict({'data': Tensor{'data', [B?,T|'time:var-unk:data'[B?],F|F'feature:data'(50)]}, 'classes': Tensor{'classes', [B?,T|'time:var-unk:classes'[B?]], dtype='int64', sparse_dim=Dim{F'classes:sparse-dim'(12001)}}})>
  File "/u/rossenbach/src/returnn/returnn/tensor/tensor_dict.py", line 73, in TensorDict.as_raw_tensor_dict
    line: out[key_] = dim.get_dim_value()
    locals:
      out = <local> {'data': tensor([[[-1.3392,  0.1613, -0.5338,  ..., -1.1736, -0.2358,  1.0485],
                             [-1.2489,  0.2953, -0.5599,  ..., -1.5901, -0.9944,  0.0320],
                             [-1.3596,  0.2531, -0.5303,  ..., -2.1433, -1.0030,  0.0344],
                             ...,
                             [ 1.2479,  0.2570, -0.6881,  ...,  0.2707,  0.1164, ...
      key_ = <local> 'data:size0', len = 10
      dim = <local> Dim{B}
      dim.get_dim_value = <local> <bound method _DimMixin.get_dim_value of Dim{B}>
  File "/u/rossenbach/src/returnn/returnn/tensor/_dim_extra.py", line 1552, in _DimMixin.get_dim_value
    line: raise Exception("%s: need placeholder, self.dimension or self.dyn_size for dim value" % self)
    locals:
      Exception = <builtin> <class 'Exception'>
      self = <local> Dim{B}
Exception: Dim{B}: need placeholder, self.dimension or self.dyn_size for dim value
```

I will now in detail explain my thought process and how I tried to solve it, maybe this gives you some insights of my issues when working with RETURNN:

1. First I have a look at `TorchDict.as_raw_tensor_dict`. Here it is written:
```python
            for i, dim in enumerate(value.dims):
                key_ = f"{key}:size{i}"
                assert key_ not in out
                if dim.is_batch_dim() and (not dim.dyn_size_ext or dim.dyn_size_ext.raw_tensor is None):
                    out[key_] = dim.get_dim_value()
                elif dim.dyn_size_ext:
                    out[key_] = dim.dyn_size_ext.raw_tensor
```
And I got the impression: okay, here is a clear extra case for the batch dim, so this means it was intended that this should exist.
2. Then I looked at `dim.get_dim_value()`, and it seems clear that none of the paths will trigger, as `.size`  (`.dimension`)is not set, `.dyn_size_ext` is not set (we checked that already), `._extra` or `.batch` are not set (and not relevant for PyTorch), so obviously the Exception will be raised.
3. Now I am asking myself again, should batch dim be properly defined? I think again yes.
4. Now I thought: okay how and where could I set the batch axis. First idea, next to where the time axis is set in `_run_step` I can also set the batch axis. But then I though, okay how should this be, as `.size`/`.dimension` or as `.dyn_size_ext`? 
5. I tried to set `.dyn_size_ext`, but then I could not figure out how to actually create a `Tensor` for a scalar.
6. Then I raised this issue.
7. I figure just setting `.size` solves the issue, but you said you would prefer `.dyn_size_ext`.

So for the current code, see #1305.

I can add a test case for the engine, but as we do not have this yet (at least I did not see it) this would require some extra work another day.

**Comment by albertz** [comment]
Why do you call `as_raw_tensor_dict()`? I don't see any reason for that. Maybe I should have made it private. But even if not private, it doesn't make sense to call this. The current use case for `as_raw_tensor_dict()` is TF specific. We might add other backend support at some point when needed. But this is mostly for RETURNN internal code. At least I don't see any useful usage of this outside of RETURNN internal code.

Yes, it would be nice if `Dim.get_dim_value()` always works, but that's again sth which you should never need to use in pure PT code.

I still don't understand what you are trying to do. If you want to write pure PT code, why do you need any of that? Just ignore all that.

**Comment by JackTemaki** [comment]
> I still don't understand what you are trying to do.

`as_raw_tensor_dict` is currently the cleanest way to get the raw tensors in the step without touching any other code.

**Comment by albertz** [comment]
I think this is already fixed. Although the code could be cleaned up a bit.
