### ISSUE TITLE
ZoneoutLSTMCell incorrect output

### ISSUE THREAD

**Issue by albertz** [rwth-i6/returnn#1313]
[Paper](https://arxiv.org/pdf/1606.01305.pdf).

We currently have this code:
```python
# Apply vanilla LSTM
output, new_state = self._cell(inputs, state, scope)

(prev_c, prev_h) = state
(new_c, new_h) = new_state

# apply zoneout
c = ...
h = ...

new_state = rnn_cell.LSTMStateTuple(c, h)

return output, new_state
```

`output` is the original output, and `h` the zoneout-transformed output.

But actually it should not return `output` but it should return `h` instead. At least this is my understanding of the paper.

Can someone confirm?

So, what do we do now? I think there are many existing setups using this. And just changing this would change the behavior and do sth different then, so it is not really compatible.

We could introduce a new option to switch between the incorrect and correct behavior. This flag default would use the correct behavior with a new behavior version.

**Comment by michelwi** [comment]
> Can someone confirm?

If the h's are the same as the output's, then I agree that the current behavior is not the same as described in the paper. As described in the paper `h` should be the output which is a combination of `prev_h` and `new_h` according to a random binary mask.
