### ISSUE TITLE
TF Nest alternative

### ISSUE THREAD

**Issue by albertz** [rwth-i6/returnn#1314]
For some code, it is useful to have functions like what TF `nest` (`from tensorflow.python.util import nest`) provides, such as `nest.map_structure`, `nest.flatten`, `nest.pack_sequence_as`, and others.

So far, it was not really a problem to use just the TF `nest`, as we anyway have TF as dependency (although for RC, this was debatable: https://github.com/rwth-i6/returnn_common/issues/27).

Now, as we support different backends again (https://github.com/rwth-i6/returnn/issues/1120), we don't want to have this in code which should be independent of TF.

So, what are the alternatives:

- Create a simple implementation ourselves. It's not really so hard. But it's kind of reinventing the wheel.
- Copy over some existing implementation (e.g. TF `nest`) and keep our own copy.
- Use some other alternative package, i.e. add a new dependency.

(Similar discussion here: https://github.com/rwth-i6/returnn_common/issues/27#issuecomment-929974584)

Some known implementations:

- TF `nest`. No own package, thus depends on whole TF.
- [Pytrees from JAX](https://jax.readthedocs.io/en/latest/pytrees.html). No own package, depends on whole JAX.
- [Tree from DeepMind](https://github.com/deepmind/tree). Independent package. Last commit Jan 2023. `pip install dm-tree`
- [iteration-utilities](https://iteration-utilities.readthedocs.io/en/latest/generated/deepflatten.html) ([GitHub 60 stars](https://github.com/MSeifert04/iteration_utilities)). Last commit Dec 2020. So basically unmaintained.
- [more-itertools](https://more-itertools.readthedocs.io/en/latest/api.html#more_itertools.collapse) ([GitHub >2k stars](https://github.com/more-itertools/more-itertools)). Last commit Apr 2023.

I did not really looked into them in detail whether they really exactly provide what we need (which is mostly exactly what TF `nest` provides).

**Comment by albertz** [comment]
I'm currently leaning towards those two options:

- Copy over TF `nest` to RETURNN. Just because I'm familiar with it.
- Use Tree from DeepMind. Seems well-maintained and exactly what we need (in contrast to the other packages which provide other stuff).

**Comment by curufinwe** [comment]
From these last 2 options I think I would prefer to add the dependency to tree. This will keep the RETURNN code small and more approachable to new developers.

**Comment by albertz** [comment]
Ok then it's decided: we use Tree from DeepMind.

**Comment by albertz** [comment]
Getting back to this, for completeness, some new alternatives:

* PyTorch PyTree: `torch.utils._pytree`, part of PyTorch, slow, hidden, but might be made public, and speed might improve (https://github.com/pytorch/pytorch/issues/65761)
* OpTree: https://github.com/metaopt/optree
