### ISSUE TITLE
PyTorch search interface

### ISSUE THREAD

**Issue by albertz** [rwth-i6/returnn#1336]
This is for doing beam search inside RETURNN, e.g. for end-to-end models, e.g. AED.
This is when using the PyTorch engine (#1120).

Currently when the user uses `task = "search"`, our `main` would call `engine.search(...)`. This function is not implemented for the PT engine.

Do we want to implement it?

In #1120, currently we discussed to have a very generic `forward_step` function, which can have any number of outputs. But we don't really have discussed how they would be used. Dumped to HDF? Dumped to a Python file similar as what we get via TF `engine.search`? How would that be configured?

The TF `engine.search` is more specific. Either the search output is behind `DecideLayer`, so no beam anymore, then it will create a Python file with a dict seq_tag -> hyp. Or it is with beam, then it is a Python file with a dict seq_tag -> list of tuple hyp and score.

Do we want to have sth as specific as that? So the user defines a `search_step` or so in the config?

Or how exactly would we define in the config what would happen with the outputs from `forward_step`? All dumped to file? But this should be flexible enough to allow for a format exactly like the TF format. I.e. Python file with a dict seq_tag -> list of tuple hyp and score.

**Comment by JackTemaki** [comment]
For me it would be fine to have nothing implemented, I prefer to take care of any processing and dumping myself in the forward_step, I would not even require a "search" task.

**Comment by albertz** [comment]
Currently when the user puts `task = "forward"`, RETURNN calls `engine.forward_to_hdf(...)`. So as the name says, it is already somewhat specific to HDF. And it is expecting a single output.

Maybe to have it more distinct, we just introduce a new more generic `task = "forward_generic"` or so.

But then still the question remains, how would the output(s) from `forward_step` ends up in a file. How would the user specify this in the config? Ideally this should be generic enough that it is possible to generate a file with the same format as what we get via TF `engine.search`. I.e. Python file with a dict seq_tag -> list of tuple hyp and score.

**Comment by albertz** [comment]
Maybe the user can define some `forward_step_callback(seq_tag, outputs)` or so which is executed after the `forward_step`, where we pass the final outputs. Maybe this is called already per each sequence, no batch dim anymore. Then the user could implement the file saving by hand in there. Maybe an initial `forward_initial_callback` to open the files. Or maybe directly the user passes in some object derived from interface:
```python
class ForwardStepCallbackIntf:
  def init(self): pass
  def step(self, seq_tag, outputs): pass
  def finish(self): pass
```
Or so. Then the user specifies `forward_step_callback = MyForwardStepCallbackIntf` in the config.

If `forward_step_callback` is callable (it is here because of class), it will call it (then it gets `MyForwardStepCallbackIntf()`, i.e. an instance of `MyForwardStepCallbackIntf` in this example).

`MyForwardStepCallbackIntf` could look like this:
```python
class MyForwardStepCallbackIntf(ForwardStepCallbackIntf):
  def __init__(self):
    self.out_file = None
  def init(self):
    self.out_file = open("recog.out.py", "w")
    self.out_file.write("{\n")
  def step(self, seq_tag, outputs):
    self.out_file.write(repr(seq_tag) + ": [%s],\n" % ...)
  def finish(self):
    self.out_file.write("}\n")
    self.out_file.close()
```

**Comment by albertz** [comment]
As there is no other suggestion, and we already waited here for almost a week, I'm going to implement those now. If you want to have anything different, please respond as soon as possible.
