### ISSUE TITLE
batch size in tf compute priors

### ISSUE THREAD

**Issue by vieting** [rwth-i6/returnn#1337]
In the tf engine in `compute_priors()`, we currently have `batch_size = config.int("batch_size", 1)`. In my config, `batch_size` is a `NumbersDict` which crashes. Right now, I mitigate this in my setup by replacing the batch size in the config before computing the priors, but we could easily allow `NumbersDict` here as well, right?

**Comment by albertz** [comment]
Yes sure. It's just that way because this code is very old.
