### ISSUE TITLE
PyTorch data pipeline broken with chunking due to `seq_tag`

### ISSUE THREAD

**Issue by Judyxujj** [rwth-i6/returnn#1341]
In the commit [738b091](https://github.com/rwth-i6/returnn/commit/738b0910ee35d3d8ec3328a23a21eb9f3a249956) , `seq_tag` is added to the dataset key, when used with chunking, it will cause:
```
TypeError: len() of unsized object in __iter__ of ChunkingIterDataPipe()
```
in https://github.com/rwth-i6/returnn/blob/6e147f06793f93598fe94b1d82f92c4babb36d19/returnn/torch/data/pipeline.py#L122

**Comment by albertz** [comment]
I pushed sth which should fix it. Can you test?

**Comment by Judyxujj** [comment]
Thanks for fixing! I have tested, it works!
