### ISSUE TITLE
CUDA out of memory issue when resuming Torch model training

### ISSUE THREAD

**Issue by Judyxujj** [rwth-i6/returnn#1345]
When running with multi-gpu, once the training job is interrupted, when restarting, when it loads the existing checkpoint, I always get` OutOfMemoryError: CUDA out of memory` at the first training step (the same GPUs are used). But such error does not happen when I run training with single GPU.

The possible reason could be that with multi-GPU training, we save the checkpoint when `rank==0`. Thus when loading the checkpoint, instead of loading the checkpoints to each device respectively, they are all loaded to device 0.

**Comment by Judyxujj** [comment]
when running with multi-gpu, once the training job is interrupted, I always get` OutOfMemoryError: CUDA out of memory` at the first training step (the same GPUs are used). But such error does not happen when I run training with single GPU. The possible reason could be that with multi-GPU training, we save the checkpoint when `rank==0`. Thus when loading the checkpoint, instead of loading the checkpoints to each device respectively, they are all loaded to device 0.

**Comment by albertz** [comment]
(*Note* I extended your post a bit, to add the context that the actual relevant difference is the model loading from checkpoint.)

**Comment by albertz** [comment]
> When running with multi-gpu, once the training job is interrupted, when restarting, when it loads the existing checkpoint, I always get` OutOfMemoryError: CUDA out of memory` at the first training step (the same GPUs are used). But such error does not happen when I run training with single GPU.

When you say the error does not happen with single GPU, what do you mean exactly by that? If you just don't get this exception, this does not say that you do not have the same problem there, right? It could still be that you have the same problem, but it just needs more memory overall, so still it does not trigger the OOM. Did you actually measure the memory consumption in both cases, i.e. randomly initializing the parameters vs loading the checkpoint, for the case of single GPU? Is this the same?

**Comment by albertz** [comment]
> The possible reason could be that with multi-GPU training, we save the checkpoint when `rank==0`. Thus when loading the checkpoint, instead of loading the checkpoints to each device respectively, they are all loaded to device 0.

That could explain the problem. You can easily verify that, e.g. by printing the device of some of the parameters to stdout. So did you check that?

**Comment by Judyxujj** [comment]
> 

Thanks for the hint. Now I can verify that the model in all checkpoints are loaded to `device cuda:0`

**Comment by Judyxujj** [comment]
>
