### ISSUE TITLE
PyTorch engine memory stats

### ISSUE THREAD

**Issue by vieting** [rwth-i6/returnn#1365]
In TF, we had the option `tf_log_memory_usage`. I think it would be nice to add something similar for the PyTorch engine. We could also print it by default. There's functions available like `torch.coda.memory_stats()` (see [here](https://pytorch.org/docs/stable/generated/torch.cuda.memory_stats.html)). Do you have preferences on how to integrate this?

**Comment by albertz** [comment]
Whether it would be printed by default or not (or just always without option) is sth to be discussed. In TF, we did not.

I'm not sure how much overhead there is by calling this function.

It would be nice if the format in our log could stay consistent, if this is possible easily.

In general, I think it's a good idea to have such stats.

**Comment by albertz** [comment]
This is implemented now.
