### ISSUE TITLE
Resume training from specific epoch

### ISSUE THREAD

**Issue by lucgeo** [rwth-i6/returnn#139]
Hi,

I was training using the full Librispeech dataset (960 h) for 250 epochs, but it crashed after the first 122 epochs. I took a look to the logs, but I can't find any reason, I got only the "killed" message in console. Is it possible to resume training starting from epoch no. 122?

Thanks!

**Comment by patrick-wilken** [comment]
Simply try to restart the training, it should load the the most recently saved model automatically.

**Comment by albertz** [comment]
Hard to tell from the report whether this was a RETURNN problem. Closing now. Please provide further information if you think something in RETURNN needs to be fixed.
