### ISSUE TITLE
LM config for Librispeech text corpus

### ISSUE THREAD

**Issue by deep-speech** [rwth-i6/returnn#141]
Have you followed any specific paper for the LM config used in LM fusion experiment? Can I use this config for training on much bigger dataset (~ 1 billion lines) or can you suggest some modifications or alternate models?

**Comment by kazuki-irie** [comment]
We did not follow any specific configuration from other papers, but we followed the spirit of scaling up the models from "Exploring the Limits of Language Modeling" paper https://arxiv.org/abs/1602.02410 .

You could possibly try to use the same model for your larger dataset, although it is hard to tell if that configuration will directly work well.

For your information, we might release improved LM configs for Librispeech in the next few weeks (likely in April, if that happens).

**Comment by deep-speech** [comment]
Thanks a lot for quick reply,  will be looking forward to new LM configs.

**Comment by deep-speech** [comment]
Are the new LM configs released yet ?

**Comment by albertz** [comment]
Which do you mean? Maybe @kazuki-irie can upload them.

**Comment by kazuki-irie** [comment]
Sorry for a late reply. We have very recently released some configs and models in our repository for experiments: https://github.com/rwth-i6/returnn-experiments/tree/master/2019-lm-transformers
A few more are still to come but most important ones are already available at this link.

**Comment by deep-speech** [comment]
Thanks for the reply. I have a couple of queries - a) are these models based on vanilla transformer or on some later updates(like Transformer-XL) b) Are these configs good to go for bpe based models or will it require tuning hyper-parameters?

**Comment by kazuki-irie** [comment]
Sorry (again!) for a late reply.
>  a) are these models based on vanilla transformer or some later version(like Transformer-XL)

These are standard Transformers.

>  b) Are these configs good to go for bpe based models or will it require tuning hyper-parameters?

Please take a look at the config files for the BPE level models which are now also available in the repository for the experiments. They are almost similar to the word level ones.

> c) Have you published any baseline results for these models?

There is an arXiv preprint available online: https://arxiv.org/abs/1905.04226 .
We also mention this now on the readme file in the same repository.

**Comment by deep-speech** [comment]
I have read your paper, congratulations for your fine work!
I have a couple of queries - a) How does inference time of Transformer LM compare to LSTM based LM b) I was trying the bpe config on a bigger dataset. I did apply bpe using only the bpe-codes, during training it shows a lot of out of vocab words. There are two ways to apply bpe - with only bpe codes and with both bpe-codes and bpe-vocab. Which of the two ways should be followed ?

**Comment by kazuki-irie** [comment]
Thank you.

> a) How does inference time of Transformer LM compare to LSTM based LM

Our Transformer models are roughly 60% slower than our LSTM models during decoding with shallow fusion.

> b) I did apply bpe using only the bpe-codes, during training it shows a lot of out of vocab words. 

The `subword-nmt/apply_bpe.py` must be applied using both `-c` flag to provide your BPE code and `--vocabulary` flag to specify your vocabulary. If you do so, you will only get OOVs for unknown characters.
