### ISSUE TITLE
Torch distributed: attribute num_iterations doesn't exist in torch version 2.1.0 anymore

### ISSUE THREAD

**Issue by kuacakuaca** [rwth-i6/returnn#1451]
- returnn code: https://github.com/rwth-i6/returnn/blob/c49cdf7970f45a9614cd4b1efe043190495d0f1c/returnn/torch/distributed.py#L135
- torch.nn.parallel.DistributedDataParallel class: https://pytorch.org/docs/2.1/_modules/torch/nn/parallel/distributed.html#DistributedDataParallel

**Comment by albertz** [comment]
You implemented that. But I think you copied this code from somewhere. Where does this come from? You just copied it from `DistributedDataParallel.forward`? So how does `DistributedDataParallel.forward` look now?

**Comment by kuacakuaca** [comment]
> You implemented that. But I think you copied this code from somewhere. Where does this come from? You just copied it from `DistributedDataParallel.forward`? So how does `DistributedDataParallel.forward` look now?

not me, maybe @Judyxujj ?

**Comment by albertz** [comment]
@kuacakuaca what is your current solution? Downgrade PyTorch? What PyTorch version do you use?

**Comment by kuacakuaca** [comment]
> @kuacakuaca what is your current solution? Downgrade PyTorch? What PyTorch version do you use?

yes, i'm using torch version 2.0.1 for now.

**Comment by kuacakuaca** [comment]
> @kuacakuaca: So, again, to clarify: What is the error you got? The same as what I posted? Sth different? (Please always post the error.)
My error message was exactly like yours.

**Comment by albertz** [comment]
So I pushed https://github.com/rwth-i6/returnn/commit/90c7548370d75196b9cbe851cb8345abcf8825bc to fix this as I described. Can you check?
