### ISSUE TITLE
TF 2.14 compatibility issues for tf util `cond()`

### ISSUE THREAD

**Issue by vieting** [rwth-i6/returnn#1459]
In tf util [`cond()`](https://github.com/rwth-i6/returnn/blob/master/returnn/tf/util/basic.py#L3698), we have

```
from tensorflow.python.ops import control_flow_ops

return control_flow_ops.cond(pred, true_fn, false_fn, name=name)
```

With TF 2.14, this seems to face compatibility issues.

```
AttributeError: module 'tensorflow.python.ops.control_flow_ops' has no attribute 'cond'
```

**Comment by vieting** [comment]
See https://github.com/tensorflow/models/issues/11099#issuecomment-1775351071 which points to this commit https://github.com/tensorflow/tensorflow/commit/8d0ac689ff65c0f0bf0dbb1add84e1c7d4baabe0.

**Comment by vieting** [comment]
Based on the proposed solution there, we could do
```
    from tensorflow.python.ops import cond as control_flow_ops_cond                                                          
                                                                                                                         
    return control_flow_ops_cond.cond(pred, true_fn, false_fn, name=name)
```
instead of the current import. This seems to work here as well and I also tested it for TF 2.8, but I'm not sure if it breaks things for other versions.

**Comment by albertz** [comment]
Why don't we just use `tf.cond`?

**Comment by vieting** [comment]
With TF 2.8, `tf.cond` is the function `cond_for_tf_v2` which is different from what is currently used. Not sure if this is a problem though.
```
>>> import tensorflow as tf
>>> tf.__version__
'2.8.0'
>>> from tensorflow.python.ops import control_flow_ops
>>> control_flow_ops.cond
<function cond at 0x7f5f8bfc9ca0>
>>> tf.cond
<function cond_for_tf_v2 at 0x7f5f8bfc9dc0>
```

**Comment by albertz** [comment]
But what is the difference? I think `tf.cond` makes in any case more sense here. I don't really know why we did not use that?

**Comment by albertz** [comment]
Note, we have the `TF_ENABLE_COND_V2` env var to control whether it should use V1 or V2 control flow (including `cond`). Maybe `control_flow_ops.cond` is always V1? If that is not the difference, then I would assume, if you follow the code, they probably end up in the same code.

**Comment by vieting** [comment]
My training is running fine with `tf.cond`. In fact, in all other places of RETURNN, we already use `tf.cond()`. If you have no objections, I would also use it here then.
