### ISSUE TITLE
Compile native op: native signal handler

### ISSUE THREAD

**Issue by Gerstenberger** [rwth-i6/returnn#1463]
When running `tools/compile_native_op.py` for example for `NativeLstm2` op, if the output file is specified it now looks like this:
```
/var/tmp/agerstenberger/returnn_native/native_signal_handler/3eb0034669/native_signal_handler.so
/var/tmp/agerstenberger/returnn_tf_cache/ops/NativeLstm2/8c9954fa8e/NativeLstm2.so
/var/tmp/agerstenberger/returnn_tf_cache/ops/GradOfNativeLstm2/d1a9d7605d/GradOfNativeLstm2.so
```

You would not expect to find native_signal_handler.so here. 
Also the `i6_core` job `CompileNativeOpJob` does not check names of the op but just copies the first entry and the second entry as gradient .so., which is now wrong.

So now i'm asking, should we fix it here or do a more robust check in `i6_core`?

A fix here is very simply just moving the line
```python
NativeCodeCompiler.CollectedCompilers = []
```
after the init function is called.

**Comment by albertz** [comment]
The script is about collecting compiled native ops, and native signal handler is not a native op, so this is the bug that it was collected here. It should only collect outputs from the TF native op compiler, I guess.
