### ISSUE TITLE
Memory reserved for whole dataset in HDFDataset (when using cached)

### ISSUE THREAD

**Issue by ArneNx** [rwth-i6/returnn#148]
The following line is executed when HDFDataset is used with cache activated:
https://github.com/rwth-i6/returnn/blob/f66e4d71bc997fd218282667d36751e5c0231b72/HDFDataset.py#L206-L207

As far as I can see, this would lead to memory being allocated for the whole training set.
I think this is an important issue, since this would be counteracting the desired effect of HDFDataset.

I will try to limit this to ``self.cache_byte_size_total_limit``, but I'm also open to other suggestions.

**Comment by albertz** [comment]
Please discuss with @doetsch-apptek / @doetsch before you plan to do any changes there.
I personally would very much recommend to not use the cache of the `HDFDataset`. Our TF Engine has an own small cache (in general, for any dataset; this is the `FeedDictDataProvider`) which should work fine. In general, if you can read the data faster from disc than the model training takes time, you don't need any more caching than that.

**Comment by doetsch** [comment]
The assumption is that the target values do not take much memory compared to the feature values, that's why they aren't cached. But it certainly can make sense to cache them as well. Caching data has fundamental advantages on slow file systems (like AWS nodes) in proper test scenarios so I am strictly against removing the caching feature entirely.

**Comment by albertz** [comment]
Yes sure, but I guess this is about changing the code in case of caching.
Although, I would say, just try it out first without caching, and if this already works fine for you, I would say that we do not need to make this code more complicated.

**Comment by ArneNx** [comment]
In my case (and also in general in MT) the target values take at least as much space as the input. 
I am implementing a special dataset as subclass of HDFDataset and just assumed caching would be faster, so I first focused on this. I will try without caching for now and see if it is fast enough for me. 
In that case I would be fine with leaving it like this.

**Comment by albertz** [comment]
Why do you implement a special dataset as a subclass of `HDFDataset`? `HDFDataset` is not a good base class. You should use sth like `CachedDataset2` instead. But probably you don't need a custom dataset in any case, and you can use `MetaDataset` instead. But maybe let's discuss offline, I guess this is a bit off topic here.

I'm closing this for now. Reopen if this is still an issue (i.e. disabling the cache is not a good solution for your case).
