### ISSUE TITLE
Returnn Native after using different apptainer uses old compilation

### ISSUE THREAD

**Issue by Atticus1806** [rwth-i6/returnn#1502]
I currently have 2 images in use. One of them is Ubuntu 22, the other is Ubuntu 20. What happens from time to time is, that Returnn crashes on start with the following error:
```
OSError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /var/tmp/hilmes/returnn_native/pytopickle/0816b8b1eb/pytopickle.so)
```
I assume this is due to the version being compiled with one image and then ran by the other (later). Can we do something to either catch this or rerun the compilation? When deleting the folder manually on the node it works.

**Comment by albertz** [comment]
This should have been fixed already since a while, since we include uname in the hash, which also includes the glibc version, or not?

**Comment by Atticus1806** [comment]
My current used commit is from ~2 weeks ago, do you think this is too old? 
When the error occurs the next time I will check the latest commit.

**Comment by albertz** [comment]
No that change is older.

What goes into the hash?

**Comment by albertz** [comment]
https://github.com/rwth-i6/returnn/blob/master/returnn%2Futil%2Fnative_code_compiler.py#L176

**Comment by albertz** [comment]
Can you check what's on that platform? Maybe it misses the glibc version. Then we need to extend this.

**Comment by Atticus1806** [comment]
Actually I realized that due to some hash_overwrite it used an older commit. I just updated to the newest commit, if all jobs pass now I would close this and reopen if necessary.
