### ISSUE TITLE
Log GPU device for torch backend

### ISSUE THREAD

**Issue by vieting** [rwth-i6/returnn#1516]
With the TF backend, RETURNN printed some information about the GPU device into the log, e.g.
> Using gpu device 0: NVIDIA GeForce RTX 2080 Ti

For torch, this does not seem to be the case. Should we add this?

**Comment by albertz** [comment]
It does print exactly that information?
```
        if self._device == "cuda" or self._device.startswith("cuda:"):
            # Theano and TensorFlow print sth like: Using gpu device 2: GeForce GTX 980 (...)
            # Print in a similar format so that some scripts which grep our stdout work just as before.
            diagnose_gpu.print_using_cuda_device_report(self._device, file=log.v2)
```
That prints for example:
```
Using gpu device 2: NVIDIA GeForce RTX 2080 Ti
```

**Comment by vieting** [comment]
You're right, my bad. I checked the log from an outdated version.
