### ISSUE TITLE
torch.onnx.export requires input_names and output_names to be in order

### ISSUE THREAD

**Issue by kuacakuaca** [rwth-i6/returnn#1517]
I encountered an issue when exporting a torch model to onnx. I have multiple input and outputs defined in the torch model. Because of the reformatting of `returnn.config` within the `TorchOnnxExportJob`, the output names I defined through `model_outputs` got reordered and thus assigned to the wrong output tensors in the output resulting model.
Per documentation `torch.onnx.export` requires `input_names` and `output_names` to be in order while `extern_data` and `model_outputs` are dicts and doesn't necessarily preserve orders.
https://github.com/rwth-i6/returnn/blob/c066ef9c66e14a3804e7d194173fe58f5a03dd30/tools/torch_export_to_onnx.py#L262

[torch.onnx.export](https://pytorch.org/docs/stable/_modules/torch/onnx/utils.html#export)

> input_names (list of str, default empty list): names to assign to the input nodes of the graph, in order.
> output_names (list of str, default empty list): names to assign to the output nodes of the graph, in order.

**Comment by albertz** [comment]
In `ReturnnConfig`, can you try `sort_config=False`? That should keep your original order. Otherwise (with the default `sort_config=True`), I think both input_names and output_names will be ordered by name.

**Comment by albertz** [comment]
However, I think you are definitely right that this is an issue. `sort_config` for example does not influence the hash, but it influences the outcome, as we see here. I would blame i6_core `ReturnnConfig` serialization behavior and/or i6_core `TorchOnnxExportJob` here though for being wrong.

**Comment by albertz** [comment]
Btw, what exactly do you want to get? The original order as you defined the keys in `extern_data` and `model_outputs`? Or do you want to explicitly define the order in `TorchOnnxExportJob`?

**Comment by kuacakuaca** [comment]
> In `ReturnnConfig`, can you try `sort_config=False`? That should keep your original order. Otherwise (with the default `sort_config=True`), I think both input_names and output_names will be ordered by name.

thanks for the hint! I'm not aware of that flag. In my case, only the extra sorting is to blame not the `TorchOnnxExportJob`. And yes, I want to keep the order of names as in `extern_data` and `model_outputs`.

**Comment by albertz** [comment]
> In my case, only the extra sorting is to blame not the `TorchOnnxExportJob`.

Well, the `TorchOnnxExportJob` controls this. The `TorchOnnxExportJob` could just dump the config without the sorting. Or the `TorchOnnxExportJob` could explicitly pass the right order to the torch-export script.

I just added the args `--input_names` and `--output_names` to the torch-export script which allows this explicit passing of the order.

So now we should fix `TorchOnnxExportJob` that it uses those. Then it doesn't matter if you set `sort_config=True` or not in the `ReturnnConfig`.

**Comment by kuacakuaca** [comment]
thanks for the fixing! I can update the `TorchOnnxExportJob`.

**Comment by albertz** [comment]
> thanks for the fixing! I can update the `TorchOnnxExportJob`.

Ok. So make a new PR then for this for i6_core. And reference the issue here.

I would add `input_names: Optional[Sequence[str]] = None` and `output_names: Optional[Sequence[str]] = None` as arguments to the job, and use `__sis_hash_exclude__ = {"input_names": None, "output_names": None}` so that the hash does not change.

In case they are specified, they would just be used as-is and passed to the torch-export script.

In case they are not specified, you can get them from the config, like so:
```python
input_names = list(returnn_config.config["extern_data"].keys()) if input_names is None else input_names
output_names = list(returnn_config.config["model_outputs"].keys()) if output_names is None else output_names
```
Although there are some cases where this does not work, e.g. when `extern_data`/`model_outputs` are defined via the `python_epilog`. So the code should be extended like so:
```python
input_names = list(returnn_config.config["extern_data"].keys()) if ("extern_data" in returnn_config.config and input_names is None) else input_names
output_names = list(returnn_config.config["model_outputs"].keys()) if ("model_outputs" in returnn_config.config and output_names is None) else output_names
```
And then for the args when calling the script:
```python
    def run(self):

        returnn_config_path = self.out_returnn_config.get_path()
        self.returnn_config.write(returnn_config_path)

        cmd = [
            self.returnn_python_exe.get_path(),
            self.returnn_root.join_right("tools/torch_export_to_onnx.py").get_path(),
            returnn_config_path,
            str(self.checkpoint),
            self.out_onnx_model.get_path(),
            "--device",
            self.device,
            "--verbosity",
            "5",
        ]
        if self.input_names is not None:
            cmd += ["--input_names", ",".join(self.input_names)]
        if self.output_names is not None:
            cmd += ["--output_names", ",".join(self.output_names)]

        util.create_executable("compile.sh", cmd)  # convenience file for manual execution
        sp.run(cmd, check=True)
```

**Comment by kuacakuaca** [comment]
but isn't the None case already be covered by Returnn? We should be able to leave `self.input_names` and `self.output_names` unset.

**Comment by albertz** [comment]
> but isn't the None case already be covered by Returnn? We should be able to leave `self.input_names` and `self.output_names` unset.

But that's exactly what I wrote? I wrote:

> I would add `input_names: Optional[Sequence[str]] = None` and `output_names: Optional[Sequence[str]] = None` as arguments to the job, and use `__sis_hash_exclude__ = {"input_names": None, "output_names": None}` so that the hash does not change.

**Comment by kuacakuaca** [comment]
> input_names = list(returnn_config.config["extern_data"].keys()) if input_names is None else input_names
> output_names = list(returnn_config.config["model_outputs"].keys()) if output_names is None else output_names

I misunderstood you, I thought the code above was for the class.

**Comment by albertz** [comment]
> > input_names = list(returnn_config.config["extern_data"].keys()) if input_names is None else input_names
> > output_names = list(returnn_config.config["model_outputs"].keys()) if output_names is None else output_names
> 
> Why can't we leave them `None`?

Then you get the order wrong, as you reported here in this issue. (`TorchOnnxExportJob` should get deterministic behavior, no matter if `sort_config=True` or not, because `sort_config` does not influence the hash.)

**Comment by albertz** [comment]
Now via the recent fix in the script and with https://github.com/rwth-i6/i6_core/pull/510, I think this here can be closed.
