### ISSUE TITLE
RecursionError when construction a network

### ISSUE THREAD

**Issue by squarenabla** [rwth-i6/returnn#152]
I get the following error, when constructing a deep net. 
`RecursionError: maximum recursion depth exceeded while calling a Python object`
This is caused by recursive construction of the net layers:
https://github.com/rwth-i6/returnn/blob/ee12b4ef7c71c956f7d8a265b831136788a5c2d8/TFNetwork.py#L436
Is there a way out? E.g. constructing layers one by one starting from the input layer s.t. the recursion is avoided.

**Comment by albertz** [comment]
Which Python version? Try Python 3.
As another workaround, you might want to try [`sys.setrecursionlimit`](https://docs.python.org/3/library/sys.html#sys.setrecursionlimit) (e.g. in your config).
But how deep is your network really?

**Comment by squarenabla** [comment]
I use Python3. The depth is about 100 conv layers.

**Comment by squarenabla** [comment]
sys.setrecursionlimit seems to solve the problem
