### ISSUE TITLE
Depthwise convolution

### ISSUE THREAD

**Issue by squarenabla** [rwth-i6/returnn#153]
Is there a layer which implements the depthwise convolution? I need this:
https://www.tensorflow.org/api_docs/python/tf/nn/depthwise_conv2d
If not, I'll make a pull request with a new returnn layer, which encapsulates the tf layer.
I need this to implement a MobileNet for ASR (https://arxiv.org/pdf/1704.04861.pdf).

**Comment by albertz** [comment]
First, do you really think it's worth it? The motivation in that paper is for efficiency. But we are (for now) mostly interested in final performance. I would say that we should focus on some other more interesting architectures first.

Then, I think this might be better as an additional option for the existing `ConvLayer`.

**Comment by albertz** [comment]
And btw, for just trying out how the performance is, ignoring the speed, you can do that without using this kernel, just via all the already existing layers. Before you are implementing this, I think it should be checked first if we really want that. (But again, anyway, I think we should focus on other architectures anyway for now.)

**Comment by albertz** [comment]
I'm closing this for now. Reopen if there are any updates.
