### ISSUE TITLE
Use "analyze" task

### ISSUE THREAD

**Issue by lucgeo** [rwth-i6/returnn#154]
Hi, 

I want to load my trained network and to run a profiling on it. I run this command " ./returnn/rnn.py --load=data/exp-returnn-full-train/model.250.data-00000-of-00001 --task=analyze", but I get this error: "OSError: Unable to open file (file signature not found)".

What is the proper way to load a model and to analyze it?
Thanks,
Lucian

**Comment by albertz** [comment]
You should leave out the extension `data-00000-of-00001`. That should work. Can you try?

**Comment by lucgeo** [comment]
Hi,

I tried like that: 
./returnn/rnn.py --load=data/exp-returnn-full-train/model.250 --task=analyse
and I got this error:
 Unable to open file (unable to open file: name = 'data/exp-returnn-full-train/model.250', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

Then I tried to provide only the folder path of the models, indicating the specific model using the --epoch argument:
./returnn/rnn.py --load=data/exp-returnn-full-train --epoch 250 --task=analyse
But I got another error:
./returnn/rnn.py --load=data/exp-returnn-full-train --epoch 250 --task=analyse

Thanks!

**Comment by albertz** [comment]
Ah, I just realized, you do not provide any config here. Just pass in the same config you used in training. There are many further settings it need from there (e.g. TensorFlow, dataset, etc).

**Comment by lucgeo** [comment]
It works now, thanks!
