### ISSUE TITLE
`DistributeFilesDataset`: copying files blocks `init_seq_order`

### ISSUE THREAD

**Issue by albertz** [rwth-i6/returnn#1549]
When `DistributeFilesDataset.init_seq_order` is called, it will schedule the copying (in the sub proc `_FileCacheProc`), but it will wait for this to complete, thus this will block. But there is no reason for this to block. `init_seq_order` could directly return. Even the `init_seq_order` on the sub dataset can run async.

PR #1546 actually partially fixes this.

**Comment by NeoLegends** [comment]
What about `num_seqs`? This is currently initialized within `init_seq_order` and used from `_collect_single_seq`. What are the contracts here wrt. async loading? Should we just block in `_collect_single_seq` until the sub datasets have been loaded and `num_seqs` is available?

**Comment by albertz** [comment]
The contract for the `num_seqs` property is that this doesn't need to be available. After `init_seq_order`, the only things which must be available is `is_less_than_num_seqs` and `load_seqs`. But it's totally fine when `is_less_than_num_seqs` or `load_seqs` are blocking. (`num_seqs` could also be blocking though.)

Although, in practice, usually right after `init_seq_order`, you would start iterating through the dataset, so not sure if it is worth the effort for the current epoch to do this async.

So it's mostly important that everything which is not needed for the current epoch is done async, i.e. anything related to the preloading of further epochs.
