### ISSUE TITLE
Network visualize

### ISSUE THREAD

**Issue by lucgeo** [rwth-i6/returnn#159]
Hi,

Could be the model visualized? I mean if it could be used Tensorboard or other kind of profiler in order to get more details about the network.

Thanks!

**Comment by albertz** [comment]
Yes. Returnn will already by default print out TF event files, so you can just open Tensorboard and see the network topology. It will by default dump it to the same directory of your model.
In addition, you can also add profiling info, by setting `store_metadata_mod_step > 0` in your config. Take a look at the `TFEngine.Runner.run` code for further details.

**Comment by albertz** [comment]
I'm closing now. I think there is no issue with RETURNN; it should be already well prepared for the task.
