### ISSUE TITLE
Training dropped due to keyboard interrupt

### ISSUE THREAD

**Issue by sharmaannapurna** [rwth-i6/returnn#16]
Hi, I tried running training on IAM handwriting dataset. Training dropped after half an hour or so with following messages:

`
Using cuDNN version 5110 on context None
Mapped name None to device cuda0: GeForce GTX 1080 (0000:01:00.0)
CRNN starting up, version 20170921.193339--git-9f9dd5d-dirty, pid 12964, cwd /home/mpl2/Annapurna/returnn_IAM/demos/mdlstm/IAM
CRNN command line options: ['config_real']
Theano: 0.9.0 (<site-package> in /home/mpl2/anaconda2/envs/theano/lib/python2.7/site-packages/theano)
faulthandler import error. No module named faulthandler
pynvml not available, memory information missing
WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next release (v0.10).  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

Using gpu device 0: GeForce GTX 1080 (CNMeM is enabled with initial size: 20.0% of memory, cuDNN 5110)
Device gpuX proc starting up, pid 13015
Device gpuX proc: THEANO_FLAGS = 'compiledir_format=compiledir_%(platform)s-%(processor)s-%(python_version)s-%(python_bitwidth)s--dev-gpuZ,device=gpu,force_device=True'
faulthandler import error. No module named faulthandler
Device train-network: Used data keys: ['classes', 'data', 'sizes']
using adam with nag and momentum schedule                                                                                                                                                                   
Device gpu0 proc, pid 13015 is ready for commands.
Devices: Used in multiprocessing mode.
loading file features/raw/train_valid.h5
cached 616 seqs 1.88295629248 GB (fully loaded, 40.7837103745 GB left over)
loading file features/raw/train.1.h5
loading file features/raw/train.2.h5
cached 5545 seqs 16.9867935553 GB (fully loaded, 39.2744432362 GB left over)
Train data:
  input: 1 x 1
  output: {u'classes': [79, 1], 'data': [1, 2], u'sizes': [2, 1]}
  HDF dataset, sequences: 5545, frames: 1519952558
Dev data:
  HDF dataset, sequences: 616, frames: 168484077
Devices:
  gpu0: GeForce GTX 1080 (units: 1000 clock: 1.00Ghz memory: 2.0GB) working on 1 batch (update on device)
Learning-rate-control: no file specified, not saving history (no proper restart possible)
using adam with nag and momentum schedule
CUDA.use gpu in proc 12964
WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next release (v0.10).  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

Using gpu device 0: GeForce GTX 1080 (CNMeM is enabled with initial size: 20.0% of memory, cuDNN 5110)
Network layer topology:
  input #: 1
  hidden 1Dto2D '1Dto2D' #: 1
  hidden source 'classes_source' #: 2
  hidden conv2 'conv0' #: 15
  hidden conv2 'conv1' #: 45
  hidden conv2 'conv2' #: 75
  hidden conv2 'conv3' #: 105
  hidden conv2 'conv4' #: 105
  hidden mdlstm 'mdlstm0' #: 30
  hidden mdlstm 'mdlstm1' #: 60
  hidden mdlstm 'mdlstm2' #: 90
  hidden mdlstm 'mdlstm3' #: 120
  hidden mdlstm 'mdlstm4' #: 120
  output softmax 'output' #: 80
net params #: 2627660
net trainable params: [W_conv0, b_conv0, W_conv1, b_conv1, W_conv2, b_conv2, W_conv3, b_conv3, W_conv4, b_conv4, U1_mdlstm0, U2_mdlstm0, U3_mdlstm0, U4_mdlstm0, V1_mdlstm0, V2_mdlstm0, V3_mdlstm0, V4_mdlstm0, W1_mdlstm0, W2_mdlstm0, W3_mdlstm0, W4_mdlstm0, b1_mdlstm0, b2_mdlstm0, b3_mdlstm0, b4_mdlstm0, U1_mdlstm1, U2_mdlstm1, U3_mdlstm1, U4_mdlstm1, V1_mdlstm1, V2_mdlstm1, V3_mdlstm1, V4_mdlstm1, W1_mdlstm1, W2_mdlstm1, W3_mdlstm1, W4_mdlstm1, b1_mdlstm1, b2_mdlstm1, b3_mdlstm1, b4_mdlstm1, U1_mdlstm2, U2_mdlstm2, U3_mdlstm2, U4_mdlstm2, V1_mdlstm2, V2_mdlstm2, V3_mdlstm2, V4_mdlstm2, W1_mdlstm2, W2_mdlstm2, W3_mdlstm2, W4_mdlstm2, b1_mdlstm2, b2_mdlstm2, b3_mdlstm2, b4_mdlstm2, U1_mdlstm3, U2_mdlstm3, U3_mdlstm3, U4_mdlstm3, V1_mdlstm3, V2_mdlstm3, V3_mdlstm3, V4_mdlstm3, W1_mdlstm3, W2_mdlstm3, W3_mdlstm3, W4_mdlstm3, b1_mdlstm3, b2_mdlstm3, b3_mdlstm3, b4_mdlstm3, U1_mdlstm4, U2_mdlstm4, U3_mdlstm4, U4_mdlstm4, V1_mdlstm4, V2_mdlstm4, V3_mdlstm4, V4_mdlstm4, W1_mdlstm4, W2_mdlstm4, W3_mdlstm4, W4_mdlstm4, b1_mdlstm4, b2_mdlstm4, b3_mdlstm4, b4_mdlstm4, W_in_mdlstm4_output, b_output]
start training at epoch 1 and batch 0
using batch size: 600000, max seqs: 10
learning rate control: ConstantLearningRate(defaultLearningRate=0.0005, minLearningRate=0.0, defaultLearningRates={1: 0.0005, 25: 0.0003, 35: 0.0001}, errorMeasureKey=None, relativeErrorAlsoRelativeToLearningRate=False, minNumEpochsPerNewLearningRate=0, filename=None), epoch data: 1: EpochData(learningRate=0.0005, error={}), 25: EpochData(learningRate=0.0003, error={}), 35: EpochData(learningRate=0.0001, error={}), error key: None
pretrain: None
start epoch 1 with learning rate 0.0005 ...
TaskThread train failed
EXCEPTION
Traceback (most recent call last):
  File "/home/mpl2/Annapurna/returnn_IAM/EngineTask.py", line 376, in run
    line: self.run_inner()
    locals:
      self = <local> <TrainTaskThread(TaskThread train, started daemon 140227476027136)>
      self.run_inner = <local> <bound method TrainTaskThread.run_inner of <TrainTaskThread(TaskThread train, started daemon 140227476027136)>>
  File "/home/mpl2/Annapurna/returnn_IAM/EngineTask.py", line 401, in run_inner
    line: device.prepare(epoch=self.epoch, **self.get_device_prepare_args())
    locals:
      device = <local> <Device.Device object at 0x7f8940e7a8d0>
      device.prepare = <local> <bound method Device.prepare of <Device.Device object at 0x7f8940e7a8d0>>
      epoch = <not found>
      self = <local> <TrainTaskThread(TaskThread train, started daemon 140227476027136)>
      self.epoch = <local> 1
      self.get_device_prepare_args = <local> <bound method TrainTaskThread.get_device_prepare_args of <TrainTaskThread(TaskThread train, started daemon 140227476027136)>>
  File "/home/mpl2/Annapurna/returnn_IAM/Device.py", line 1374, in prepare
    line: self.set_net_params(network)
    locals:
      self = <local> <Device.Device object at 0x7f8940e7a8d0>
      self.set_net_params = <local> <bound method Device.set_net_params of <Device.Device object at 0x7f8940e7a8d0>>
      network = <local> <Network.LayerNetwork object at 0x7f89572804d0>
  File "/home/mpl2/Annapurna/returnn_IAM/Device.py", line 1193, in set_net_params
    line: self.set_net_encoded_params([
            numpy.asarray(p.get_value()) for p in network.get_all_params_vars()])
    locals:
      self = <local> <Device.Device object at 0x7f8940e7a8d0>
      self.set_net_encoded_params = <local> <bound method Device.set_net_encoded_params of <Device.Device object at 0x7f8940e7a8d0>>
      numpy = <global> <module 'numpy' from '/home/mpl2/anaconda2/envs/theano/lib/python2.7/site-packages/numpy/__init__.pyc'>
      numpy.asarray = <global> <function asarray at 0x7f89691f37d0>
      p = <local> W_conv0
      p.get_value = <local> <bound method GpuArraySharedVariable.get_value of W_conv0>
      network = <local> <Network.LayerNetwork object at 0x7f89572804d0>
      network.get_all_params_vars = <local> <bound method LayerNetwork.get_all_params_vars of <Network.LayerNetwork object at 0x7f89572804d0>>
  File "/home/mpl2/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gpuarray/type.py", line 602, in get_value
    line: return np.asarray(self.container.value)
    locals:
      np = <global> <module 'numpy' from '/home/mpl2/anaconda2/envs/theano/lib/python2.7/site-packages/numpy/__init__.pyc'>
      np.asarray = <global> <function asarray at 0x7f89691f37d0>
      self = <local> W_conv0
      self.container = <local> <gpuarray.array(<content not available>)>
      self.container.value = <local> gpuarray.array(<content not available>), len = 15, _[0]: {len = 1, _[0]: {len = 3, _[0]: {len = 3}}}
  File "/home/mpl2/anaconda2/envs/theano/lib/python2.7/site-packages/numpy/core/numeric.py", line 531, in asarray
    line: return array(a, dtype, copy=False, order=order)
    locals:
      array = <global> <built-in function array>
      a = <local> gpuarray.array(<content not available>), len = 15, _[0]: {len = 1, _[0]: {len = 3, _[0]: {len = 3}}}
      dtype = <local> None
      copy = <not found>
      order = <local> None
  File "pygpu/gpuarray.pyx", line 1734, in pygpu.gpuarray.GpuArray.__array__
    -- code not available --
  File "pygpu/gpuarray.pyx", line 1407, in pygpu.gpuarray._pygpu_as_ndarray
    -- code not available --
  File "pygpu/gpuarray.pyx", line 394, in pygpu.gpuarray.array_read
    -- code not available --
GpuArrayException: cuMemcpyDtoHAsync(dst, src->ptr + srcoff, sz, ctx->mem_s): CUDA_ERROR_INVALID_VALUE: invalid argument

KeyboardInterrupt
EXCEPTION
Traceback (most recent call last):
  File "../../../rnn.py", line 521, in main
    line: executeMainTask()
    locals:
      executeMainTask = <global> <function executeMainTask at 0x7f8940e76ed8>
  File "../../../rnn.py", line 375, in executeMainTask
    line: engine.train()
    locals:
      engine = <global> <Engine.Engine instance at 0x7f8940e93560>
      engine.train = <global> <bound method Engine.train of <Engine.Engine instance at 0x7f8940e93560>>
  File "/home/mpl2/Annapurna/returnn_IAM/Engine.py", line 378, in train
    line: self.train_epoch()
    locals:
      self = <local> <Engine.Engine instance at 0x7f8940e93560>
      self.train_epoch = <local> <bound method Engine.train_epoch of <Engine.Engine instance at 0x7f8940e93560>>
  File "/home/mpl2/Annapurna/returnn_IAM/Engine.py", line 494, in train_epoch
    line: trainer.join()
    locals:
      trainer = <local> <TrainTaskThread(TaskThread train, stopped daemon 140227476027136)>
      trainer.join = <local> <bound method TrainTaskThread.join_hacked of <TrainTaskThread(TaskThread train, stopped daemon 140227476027136)>>
  File "/home/mpl2/Annapurna/returnn_IAM/Util.py", line 559, in join_hacked
    line: join_orig(threadObj, timeout=0.1)
    locals:
      join_orig = <local> <unbound method Thread.join>
      threadObj = <local> <TrainTaskThread(TaskThread train, stopped daemon 140227476027136)>
      timeout = <local> None
  File "/home/mpl2/anaconda2/envs/theano/lib/python2.7/threading.py", line 951, in join
    line: self.__block.wait(delay)
    locals:
      self = <local> <TrainTaskThread(TaskThread train, stopped daemon 140227476027136)>
      self.__block = <local> !AttributeError: 'TrainTaskThread' object has no attribute '__block'
      self.__block.wait = <local> !AttributeError: 'TrainTaskThread' object has no attribute '__block'
      delay = <local> 0.09999895095825195
  File "/home/mpl2/Annapurna/returnn_IAM/Util.py", line 572, in cond_wait_hacked
    line: cond_wait_orig(cond, timeout=timeout)
    locals:
      cond_wait_orig = <local> <unbound method _Condition.wait>
      cond = <local> <Condition(<thread.lock object at 0x7f8957563dd0>, 0)>
      timeout = <local> 0.09999895095825195
  File "/home/mpl2/anaconda2/envs/theano/lib/python2.7/threading.py", line 359, in wait
    line: _sleep(delay)
    locals:
      _sleep = <global> <built-in function sleep>
      delay = <local> 0.032
KeyboardInterrupt
Quitting

`

**Comment by albertz** [comment]
`KeyboardInterrupt` is not the error, but this is:
`GpuArrayException: cuMemcpyDtoHAsync(dst, src->ptr + srcoff, sz, ctx->mem_s): CUDA_ERROR_INVALID_VALUE: invalid argument`

This is suspicious:
```
      p = <local> W_conv0
      p.get_value = <local> <bound method GpuArraySharedVariable.get_value of W_conv0>
```

It seems as if it is using the gpuarray backend here? Do you have set `device=cpu` in your `~/.theanorc`?
