### ISSUE TITLE
Make `FileCache` able to detect updated remote files

### ISSUE THREAD

**Issue by NeoLegends** [rwth-i6/returnn#1602]
Sometimes corrupt or old files are updated/replaced on the remote file system. If a file is already cached on the local machine, the `FileCache` will not detect this situation and happily use the locally cached variant. I think we can improve on this by moving the cache-keepalive `mtime`-logic to a proxy file, e.g. `original-file.name.keepalive` and comparing the `mtime` of the actual data files.

**Comment by albertz** [comment]
Wouldn't it make more sense the other way around? I.e. have some `original-file.info` or so where we store some information about the original file, like the mtime, size, maybe other things. So we still keep the touching logic for the cached file, and additional also this info file.
