### ISSUE TITLE
DistributeFilesDataset does not interact well w/ datasets that don't have a known num_seqs

### ISSUE THREAD

**Issue by NeoLegends** [rwth-i6/returnn#1614]
DistributeFilesDataset relies on the sub dataset's num_seqs to decide whether a seq idx is available or not. This is problematic if the wrapped dataset does not have a good number here, like PostprocessingDataset.

I think we could change DistributeFilesDataset to poll its underlying dataset iterator-style similar to the implementation of PostprocessingDataset. We can still try to publish `num_seqs` from the child dataset as we do currently, but use the iterator to determine if there are more segments in the underlying dataset or not. 

cc @albertz, WDYT?

**Comment by albertz** [comment]
> DistributeFilesDataset relies on the sub dataset's num_seqs to decide whether a seq idx is available or not

Why? Where?

**Comment by NeoLegends** [comment]
In https://github.com/rwth-i6/returnn/blob/ce97976653a7c09a78c798204ab8bf9fdeb51b4d/returnn/datasets/distrib_files.py#L316 it stores the num_seqs from the sub dataset as property. This comes from https://github.com/rwth-i6/returnn/blob/ce97976653a7c09a78c798204ab8bf9fdeb51b4d/returnn/datasets/distrib_files.py#L535-L545, which comes from https://github.com/rwth-i6/returnn/blob/ce97976653a7c09a78c798204ab8bf9fdeb51b4d/returnn/datasets/distrib_files.py#L656-L659. 

Now in PostprocessingDataset, we derive from CachedDataset2, which looks at `self._num_seqs`: https://github.com/rwth-i6/returnn/blob/ce97976653a7c09a78c798204ab8bf9fdeb51b4d/returnn/datasets/cached2.py#L95-L104. We only ever set that to `0` in PPDataset: https://github.com/rwth-i6/returnn/blob/ce97976653a7c09a78c798204ab8bf9fdeb51b4d/returnn/datasets/postprocessing.py#L168-L170

Now, to fetch another seq, DistributeFilesDataset looks at `self._num_seqs`: https://github.com/rwth-i6/returnn/blob/ce97976653a7c09a78c798204ab8bf9fdeb51b4d/returnn/datasets/distrib_files.py#L419-L421, where it should only see a `0`?

This test case crashes
```python
def iter_identity(x, **kwargs):
    yield from x

def _get_sub_epoch_dataset2(files_subepoch: List[str]) -> Dict[str, Any]:
    hdf_dset = {"class": "HDFDataset", "files": files_subepoch, "seq_ordering": "default"}
    return {"class": "PostprocessingDataset", "dataset": hdf_dset, "map_seq_stream": iter_identity}

concat_dataset = init_dataset(
    {
        "class": "DistributeFilesDataset",
        "files": hdf_files,
        "get_sub_epoch_dataset": _get_sub_epoch_dataset2,
        "partition_epoch": partition_epoch,
    }
)
assert isinstance(concat_dataset, DistributeFilesDataset)
for sub_epoch in range(1, partition_epoch + 1):
    print(f"Sub-epoch {sub_epoch}...")
    concat_dataset.init_seq_order(sub_epoch)
    concat_dataset.load_seqs(0, 1)
```

with:

```
  File "/usr/local/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/process.py", line 314, in BaseProcess._bootstrap
    line: self.run()
    locals:
      self = <local> <NonDaemonicSpawnProcess name='DistributeFilesDataset dataset_id4368856016 ep 1 worker ep 2' parent=86573 started>
  File "/usr/local/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/process.py", line 314, in BaseProcess._bootstrap
    line: self.run()
      self.run = <local> <bound method BaseProcess.run of <NonDaemonicSpawnProcess name='DistributeFilesDataset dataset_id4368856016 ep 1 worker ep 2' parent=86573 started>>
  File "/usr/local/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/process.py", line 108, in BaseProcess.run
    locals:
      self = <local> <NonDaemonicSpawnProcess name='DistributeFilesDataset dataset_id4368856016 ep 1 worker ep 1' parent=86573 started>
    line: self._target(*self._args, **self._kwargs)
    locals:
      self.run = <local> <bound method BaseProcess.run of <NonDaemonicSpawnProcess name='DistributeFilesDataset dataset_id4368856016 ep 1 worker ep 1' parent=86573 started>>
      self = <local> <NonDaemonicSpawnProcess name='DistributeFilesDataset dataset_id4368856016 ep 1 worker ep 2' parent=86573 started>
      self._target = <local> <function _worker_proc_loop at 0x108f1b1c0>
  File "/usr/local/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/process.py", line 108, in BaseProcess.run
    line: self._target(*self._args, **self._kwargs)
    locals:
      self = <local> <NonDaemonicSpawnProcess name='DistributeFilesDataset dataset_id4368856016 ep 1 worker ep 1' parent=86573 started>
      self._target = <local> <function _worker_proc_loop at 0x10bf1b1c0>
      self._args = <local> (1, 1, {'class': 'PostprocessingDataset', 'dataset': {'class': 'HDFDataset', 'files': ['/var/folders/xh/tyqsvtc975b98tm52nqv0t0c0000gn/T/tmpumuglit0-0.hdf', '/var/folders/xh/tyqsvtc975b98tm52nqv0t0c0000gn/T/tmp6k8lmcre-1.hdf', '/var/folders/xh/tyqsvtc975b98tm52nqv0t0c0000gn/T/tmpjrqhy7k8-2.hdf', ...
      self._kwargs = <local> {}
  File "/Users/moritzgunz/Documents/apptek/returnn/returnn/datasets/distrib_files.py", line 659, in _worker_proc_loop
    line: parent_conn.send(("num_seqs", dataset.num_seqs))
      self._args = <local> (2, 1, {'class': 'PostprocessingDataset', 'dataset': {'class': 'HDFDataset', 'files': ['/var/folders/xh/tyqsvtc975b98tm52nqv0t0c0000gn/T/tmpfsdokmym-4.hdf', '/var/folders/xh/tyqsvtc975b98tm52nqv0t0c0000gn/T/tmp8y8b1_4z-5.hdf', '/var/folders/xh/tyqsvtc975b98tm52nqv0t0c0000gn/T/tmpakx8m2m0-6.hdf', ...
      self._kwargs = <local> {}
  File "/Users/moritzgunz/Documents/apptek/returnn/returnn/datasets/distrib_files.py", line 659, in _worker_proc_loop
    line: parent_conn.send(("num_seqs", dataset.num_seqs))
    locals:
      parent_conn = <local> <multiprocessing.connection.Connection object at 0x108d7c280>
      parent_conn.send = <local> <bound method _ConnectionBase.send of <multiprocessing.connection.Connection object at 0x108d7c280>>
      dataset = <local> <PostprocessingDataset 'dataset_id4461518784' epoch=1>
      dataset.num_seqs = <local> !NotImplementedError: 
    locals:
      parent_conn = <local> <multiprocessing.connection.Connection object at 0x10bd7c280>
      parent_conn.send = <local> <bound method _ConnectionBase.send of <multiprocessing.connection.Connection object at 0x10bd7c280>>
      dataset = <local> <PostprocessingDataset 'dataset_id4511588288' epoch=1>
      dataset.num_seqs = <local> !NotImplementedError: 
  File "/Users/moritzgunz/Documents/apptek/returnn/returnn/datasets/cached2.py", line 104, in CachedDataset2.num_seqs
    line: raise NotImplementedError
    locals:
  File "/Users/moritzgunz/Documents/apptek/returnn/returnn/datasets/cached2.py", line 104, in CachedDataset2.num_seqs
    line: raise NotImplementedError
    locals:
      NotImplementedError = <builtin> <class 'NotImplementedError'>
NotImplementedError
      NotImplementedError = <builtin> <class 'NotImplementedError'>
NotImplementedError
```

**Comment by NeoLegends** [comment]
So overall I think DistributeFilesDataset should catch this error, and continue w/o knowing how many seqs there are. Wrapping the underlying dataset in an iterator will allow it to function normally otherwise, just like `PostprocessingDataset` does it.

**Comment by albertz** [comment]
Well the `if seq_idx >= self._num_seqs:` can simply be changed to how we usually do it, via `is_less_than_num_seqs`. Actually I just checked the code, and we already do that, where we handle the `get_data_seq`? So we can just remove this check.

**Comment by albertz** [comment]
> if the wrapped dataset does not have a good number [for `num_seqs`], like PostprocessingDataset.

Btw, what do you mean by that? A dataset should return the correct number, or if this is unknown, it should raise an exception, but it should not return an incorrect (non-good) number.

**Comment by NeoLegends** [comment]
Ah yes, I meant exactly this. It's just that wrapping a dataset that raises an exception when its `num_seqs` is accessed into DistributeFilesDataset does not work right now and I want to change that.

**Comment by albertz** [comment]
> We only ever set [`_num_seqs`] to 0 in PPDataset

No, the `super().init_seq_order` will set it to None for the usual case.

**Comment by NeoLegends** [comment]
Ah, yes. 💡  Should we set it to `self._dataset.num_seqs` if we don't have `map_seq_stream`.

**Comment by albertz** [comment]
> Ah, yes. 💡 Should we set it to `self._dataset.num_seqs` if we don't have `map_seq_stream`?

Yes. (Although you need to check for exceptions.)

But in any case, that's somewhat orthogonal to `DistributeFilesDataset`, where you need to remove this check on `num_seqs`, and otherwise not sure if some other changes are needed.

**Comment by NeoLegends** [comment]
> Actually I just checked the code, and we already do that, where we handle the get_data_seq? So we can just remove this check.

Just removing the code yields to the dataset getting stuck, I believe this check is needed in some form after all.

**Comment by NeoLegends** [comment]
Yeah, never mind, the stuck-ness was indeed an unrelated issue caused by a local change.
