### ISSUE TITLE
Sequence tags in Postprocessing dataset

### ISSUE THREAD

**Issue by DanEnergetics** [rwth-i6/returnn#1622]
It appears to me that the sequence tags in are dropped in the Postprocessing dataset. In the traceback one can see that the sequence tags look as follows:

    seq_tags = <local> Tensor{'seq_tag', [B?], dtype='string'}
    seq_tags.raw_tensor = <local> array(['seq-0', 'seq-1', 'seq-2', 'seq-3', 'seq-4', 'seq-5', 'seq-6',
                                         'seq-7', 'seq-8', 'seq-9', 'seq-10', 'seq-11', 'seq-12', 'seq-13',
                                         'seq-14', 'seq-15', 'seq-16', 'seq-17', 'seq-18', 'seq-19',
                                         'seq-20', 'seq-21', 'seq-22', 'seq-23', 'seq-24', 'seq-25',
                                         'seq-26', 's...

Here's a part of the dataset configuration

<details>
<summary>Dataset configuration</summary>
  
  ```
  train = {
      "class": "PostprocessingDataset",
      "dataset": {
          "class": "HDFDataset",
          "files": [...]
          "partition_epoch": 25,
          "seq_list_filter_file": "/path/to/file",
          "seq_ordering": "random",
      },
      "map_seq_stream": Sequential(
          apply_speed_perturbation, LaplaceOrdering(num_seqs_per_bin=1000)
      ),
      "seq_ordering": "default",
  }
  ```
</details>

**Comment by albertz** [comment]
Ah yes I think that's true.

We should add them as `seq_tag` to the `TensorDict`, and then the `PostprocessingDataset` will read them from the `TensorDict`.
