### ISSUE TITLE
Data Dimension Specification in Config/Datasets

### ISSUE THREAD

**Issue by JackTemaki** [rwth-i6/returnn#164]
Right now, data shapes are defined as a tuple (feature_dim, num_axes), where for num_axes "1" is sparse data with a single time axis, "2" is regular data with a single time axis, and "n" means n-1 time or spatial axes. 

This means, there is no possibility to describe data without a time axis. My idea is, that num_axes "0" would be sparse data without a time axis. But then "1" could be a single feature dimension without a time axis or sparse data with a time axis, meaning this would be not unique.

Any suggestions on how to handle that issue?

**Comment by albertz** [comment]
No, that is just the old format. You can also describe it as a dict (basically like `out_type` in TF layers; kwargs for the `Data` class). Or better: Use `extern_data` in the config instead of `num_inputs`/`num_outputs`.

**Comment by albertz** [comment]
I'm closing now. Feel free to extend whatever you think is missing in the documentation or in the code comments.
