### ISSUE TITLE
FileCache assertion on previous copy attempt age triggered

### ISSUE THREAD

**Issue by NeoLegends** [rwth-i6/returnn#1643]
```
Waiting for lock-file: /ssd/[...]/returnn/file_cache/nas/data/[...]/data[...].lock
Waiting for lock-file: /ssd/[...]/returnn/file_cache/nas/data/[...]/data[...].lock
Waiting for lock-file: /ssd/[...]/returnn/file_cache/nas/data/[...]/data[...].lock
Removing old lockfile '/ssd/[...]/returnn/file_cache/nas/data/[...]/data[...].lock' (probably crashed proc).

[...]

  File "/nas/models/[...]/work/i6_core/tools/git/CloneGitRepositoryJob.SdBYnl2SGErb/output/returnn/returnn/util/file_cache.py", line 294, in FileCache.handle_cached_files_in_config.<locals>._handle_value
    line: res = self.get_file(value.filename)
    locals:
      res = <not found>
      self = <local> <returnn.util.file_cache.FileCache object at 0x7efe22723b80>
      self.get_file = <local> <bound method FileCache.get_file of <returnn.util.file_cache.FileCache object at 0x7efe22723b80>>
      value = <local> CachedFile(filename='/nas/data/[...]/data[...].hdf')
      value.filename = <local> '/nas/data/[...]/data[...].hdf', len = 100
  File "/nas/models/[...]/work/i6_core/tools/git/CloneGitRepositoryJob.SdBYnl2SGErb/output/returnn/returnn/util/file_cache.py", line 120, in FileCache.get_file
    line: self._copy_file_if_needed(src_filename, dst_filename)
    locals:
      self = <local> <returnn.util.file_cache.FileCache object at 0x7efe22723b80>
      self._copy_file_if_needed = <local> <bound method FileCache._copy_file_if_needed of <returnn.util.file_cache.FileCache object at 0x7efe22723b80>>
      src_filename = <local> '/nas/data/[...]/data[...].hdf', len = 100
      dst_filename = <local> '/ssd/[...]/returnn/file_cache/nas/data/[...]/data[...].hdf', len = 138
  File "/nas/models/[...]/work/i6_core/tools/git/CloneGitRepositoryJob.SdBYnl2SGErb/output/returnn/returnn/util/file_cache.py", line 346, in FileCache._copy_file_if_needed
    line: assert dst_tmp_file_age > self._lock_timeout * 0.8, (
              f"FileCache: Expected left-over temp copy file {dst_tmp_filename}"
              f" from crashed previous copy attempt"
              f" to be older than {self._lock_timeout * 0.8:.1f}s but it is {dst_tmp_file_age} seconds old"
          )
    locals:
      dst_tmp_file_age = <local> 0.3813760280609131
      self = <local> <returnn.util.file_cache.FileCache object at 0x7efe22723b80>
      self._lock_timeout = <local> 20
AssertionError: FileCache: Expected left-over temp copy file /ssd/[...]/returnn/file_cache/nas/data/[...]/data[...].hdf.copy from crashed previous copy attempt to be older than 16.0s but it is 0.3813760280609131 seconds old
```

We also get:

```
File "/nas/models/[...]/work/i6_core/tools/git/CloneGitRepositoryJob.SdBYnl2SGErb/output/returnn/returnn/util/file_cache.py", line 479, in run
    os.utime(filename, None)
FileNotFoundError: [Errno 2] No such file or directory
```

One process acquires the lock file but then seems to fail to update the mtime frequently enough for the others to wait. Another process then deletes the lock file and starts copying by itself as well, leading to the assertion triggering because the other process is still copying the data.

This is probably due to FS slowness. I'm not sure what to best do here. We can
1. plainly increase the lock timeout
2. measure the time FS operations take and adjust the timeout based on that (seems difficult to do properly)

In any case we can add the lock file to the touch files thread immediately after acquiring it so that the gap between acquiring the lock and trying to update its mtime is as small as possible and includes no FS operations in between that could cause additional delays.

**Comment by albertz** [comment]
After #1644 was merged now, please check whether this problem still occurs.

**Comment by NeoLegends** [comment]
This has not occured again on the same problematic node.

**Comment by albertz** [comment]
Do we log when we remove the lock file? E.g. log why it is being removed, the recent mtime, etc.

**Comment by NeoLegends** [comment]
Yes:
```
Removing old lockfile '/ssd/pzheng/returnn/file_cache/nas/data/speech/NL_NL/16kHz/NPO/corpus/batch.1.v1/hdf-raw_wav.16kHz.split-151/NPO-batch.1.v1.hdf.76.lock' (probably crashed proc).

```

**Comment by NeoLegends** [comment]
See https://github.com/rwth-i6/returnn/pull/1663

**Comment by albertz** [comment]
> WDYT on adding another check to `LockFile` that tries to figure out if the lock file is currently open/held by another process, instead of relying on the mtime? Do you think this can be reliable at all?

I don't like this.

But also, I don't really understand the issue. How does this actually happen? Why is the mtime not reliable? How can that be? And we should be able to make this reliable, or not? So then, no other weird workaround is needed.

**Comment by NeoLegends** [comment]
A (very) slow FS could be one reason the mtime is unreliable, no? In that case there isn't really anything that can help us AFAIK except for increasing the lock timeout to a value that any slow FS is still fast enough that eventually there will be a visible mtime update. And then this decreases the usability in the good case, where there isn't any FS slowness but an actually crashed process that has left behind stale lockfiles.

**Comment by albertz** [comment]
> A (very) slow FS could be one reason the mtime is unreliable, no?

But we are writing to a local disk here? I expect maybe that this is busy for a few milliseconds, not more. This cannot explain that mtime is unreliable.

Maybe some weird FS flags while mounting the disk could cause this? But I don't think so.

So, I highly doubt that this is the problem. To me it looks like some bug somewhere. Before we add any further hacks/workarounds, we should understand what goes wrong here.

**Comment by NeoLegends** [comment]
Another part of the error message is

```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
FileCache: using existing file /ssd/[...]/corpus/batch.1.v1/hdf-raw_wav.16kHz.split-151/NPO-batch.1.v1.hdf.20
  File "/nas/models/asr/am/[...]/work/i6_core/tools/git/CloneGitRepositoryJob.vEYVF21o1uRS/output/returnn/returnn/util/file_cache.py", line 475, in run
    for filename in self.files:
RuntimeError: dictionary changed size during iteration
```

I think this is because the _TouchFilesThread runs I/O operations while modifying the `self.files` dict, and I believe the GIL is released during these I/O operations, permitting the main thread to modify `self.files` in the mean time.
