### ISSUE TITLE
remove Nose dependency

### ISSUE THREAD

**Issue by albertz** [rwth-i6/returnn#1647]
We used to use nose for our tests. We now switched to pytest. However, in some of the tests, we still make use of some nose utility functions like:
```python
from nose.tools import assert_equal, assert_not_equal, assert_raises, assert_true, assert_is
```
I think pytest does not provide similar functions (or does it?). However, it should be trivial to implement our own variants for these, or just rewrite all code usages by directly using `assert`.

(Pytest cleverly handles normal `assert` and somehow figures out for sth like `assert a == b` that this is checking equality, and then also prints `a` and `b`. I'm not sure if those heuristics/tricks/hacks always work correctly, although they seem to. But maybe to have that explicit as `assert_equal` is better also when we want to switch at some later point to some other testing framework? Not sure...)

Nose is deprecated and I think only works with Python <=3.9, not later. So we definitely must remove this dependency for our tests.

The error you see when you run this on a newer Python version:
```
test_Util.py:4: in <module>
    from nose.tools import assert_equal, assert_not_equal, assert_raises, assert_true, assert_is
/work/az668407/py-envs/py3.12-torch2.5/lib64/python3.12/site-packages/nose/__init__.py:1: in <module>
    from nose.core import collector, main, run, run_exit, runmodule
/work/az668407/py-envs/py3.12-torch2.5/lib64/python3.12/site-packages/nose/core.py:12: in <module>
    from nose.loader import defaultTestLoader
/work/az668407/py-envs/py3.12-torch2.5/lib64/python3.12/site-packages/nose/loader.py:21: in <module>
    from nose.importer import Importer, add_path, remove_path
/work/az668407/py-envs/py3.12-torch2.5/lib64/python3.12/site-packages/nose/importer.py:12: in <module>
    from imp import find_module, load_module, acquire_lock, release_lock
E   ModuleNotFoundError: No module named 'imp'
```

**Comment by NeoLegends** [comment]
I feel like the parsing of the assertions is a pretty nice feature of pytest that I would expect future test frameworks to carry-over and also implement. Other modern languages have printing the asserted values already built-in, so it seems the ecosystem is moving in that direction.

**Comment by albertz** [comment]
> I would expect future test frameworks to carry-over and also implement.

Note that this is highly non-trivial to do and requires quite a lot of complexity, so I'm not sure on that. Actually I have no idea how PyTest does this exactly. Maybe they do some import hook to modify the Python AST inplace to add that. That would be the only way I can imagine to do this.

**Comment by albertz** [comment]
> > I would expect future test frameworks to carry-over and also implement.
> 
> Note that this is highly non-trivial to do and requires quite a lot of complexity, so I'm not sure on that. Actually I have no idea how PyTest does this exactly. Maybe they do some import hook to modify the Python AST inplace to add that. That would be the only way I can imagine to do this.

Note, I just stumbled upon how PyTest does this: https://github.com/pytest-dev/pytest/blob/main/src/_pytest/assertion/rewrite.py

I.e. it really uses an import hook to modify the Python AST, what I assumed (deriving `importlib.abc.MetaPathFinder`, `importlib.abc.Loader`). That's quite complex...
