### ISSUE TITLE
Specify different layer name for parameter loading

### ISSUE THREAD

**Issue by ChristopherBrix** [rwth-i6/returnn#166]
I need to load parameters from a trained model, but modify the config a bit. Specifically, I want to switch the embedding matrix for both source and target. 
Is there a flag which can be used to specify which saved parameters should be used for the initialization? Specifically, I need the following:

`output/rec/target_embed/W` should to be initialized using `source_embed/W` and `source_embed/W` should to be initialized using `output/rec/target_embed/W`

If this is not yet possible, I could write a PR for this feature.

**Comment by albertz** [comment]
There is `preload_from_files`, which should make this possible. See the related code.

**Comment by albertz** [comment]
I don't remember the exact syntax. But maybe sth like that:
```
preload_from_files =  {
'01_init': {
  'init_for_train': ...,
  'filename': ...,
  'prefix': ...
},
'02_swap': {
  'init_for_train': ...,
  'filename': ...,
  'prefix': ...
}
}
```

**Comment by ChristopherBrix** [comment]
If I understand the [code](https://github.com/ChristopherBrix/returnn/blob/master/TFEngine.py#L939) and the [tests](https://github.com/ChristopherBrix/returnn/blob/master/tests/test_TFEngine.py#L1535) correctly, `preload_from_files` only allows me to specify a prefix which is removed from the new parameter name to match the old one. However, this does not allow arbitrary renaming.

I could use it to load the layer `output/rec/target_embed` using `source_embed` by naming it `x_source_embed` and choosing the prefix `output/rec/x_`.
To initialize my new layer `source_embed` using `output/rec/target_embed`, I could probably just name it `output/rec/target_embed`. Not sure whether this is valid in RETURNN, but it's definitely ugly and prone to cause confusion later on.

Did I miss something?

**Comment by albertz** [comment]
Maybe you are right. We can also extend it.


ChristopherBrix <notifications@github.com> schrieb am Fr., 5. Apr. 2019,
19:17:

**Comment by albertz** [comment]
Yet another way might be: Use `forward_weights_init` and `bias_init`. This configures the param init (by default this is random or 0). This can be anything, any custom function, which e.g. loads the right param.

**Comment by ChristopherBrix** [comment]
But `forward_weights_init` is only used during the (random) initialization, right? In my case I want to load a saved checkpoint (with some modifications in the network layout).

Is there a reason why the `CustomCheckpointLoader` is not used in all cases? First, [restoring the saved parameters is tried using the TF function](https://github.com/rwth-i6/returnn/blob/master/TFNetwork.py#L1251). Only if this fails (or `custom_param_importer` has been set for some parameters), the `CustomCheckpointLoader` is used. But is there any situation where the TF way is better than the `CustomCheckpointLoader`?

This prevents me from switching the parameters of two layers. Because no parameters are reported as missing, the TF code is used, and I can't execute my custom logic.
That said, maybe I should set the config flag `custom_param_importer`? I don't quite understand it's meaning yet.

**Comment by albertz** [comment]
`forward_weights_init` is for initialization, which is always done.

The procedure always goes like this (both training and decoding):
* Build network / computation graph.
* Initialize params (can be configured for many layers, via `forward_weights_init` etc; by default that is random or 0, but can be anything).
* Load checkpoint. If something does not fit, uses `CustomCheckpointLoader`. Also handles `preload_from_files`. Also handles `custom_param_importer`.

In training, when one epoch is finished and next epoch starts, it potentially can change the network topology (pretraining). If it has changed, it will:
* Store current params to CPU (`TFNetworkParamsSerialized`).
* Build new network / computation graph.
* Initialize params.
* Copy over params. This can be configured to some degree. See e.g. option `copy_param_mode` (can be `None`, `"ifpossible"`, `"subset"`). And this can further be very generic if you set `custom_param_importer`, which will be used instead if it is set.

**Comment by ChristopherBrix** [comment]
As discussed in the PR, let's postpone the implementation of this feature until there's a real need for it. For now, I'll just use a private fork.

**Comment by nikita68** [comment]
@albertz Do you have an example of how to load weights in for a specific layer from a certain checkpoint? E.g. using ``forward_weights_init``?

**Comment by JackTemaki** [comment]
Maybe this helps, it is an example on how to load a language model from specific model path

```
'lm_output': { 'class': 'subnetwork',
                                       'from': ['prev:output'],
                                       'load_on_init': '/work/asr3/irie/experiments/lm/switchboard/2018-01-23--lmbpe-zeyer/data-train/bpe1k_clean_i256_m2048_m2048.sgd_b16_lr0_cl2.newbobabs.d0.2/net-model/network.023',
                                       'n_out': 1030,
                                       'subnetwork': { 'input': {'activation': 'identity', 'class': 'linear', 'n_out': 256},
                                                       'lstm0': { 'class': 'rnn_cell',
                                                                  'dropout': 0.2,
                                                                  'from': ['input'],
                                                                  'n_out': 2048,
                                                                  'unit': 'LSTMBlock',
                                                                  'unit_opts': {'forget_bias': 0.0}},
                                                       'lstm1': { 'class': 'rnn_cell',
                                                                  'dropout': 0.2,
                                                                  'from': ['lstm0'],
                                                                  'n_out': 2048,
                                                                  'unit': 'LSTMBlock',
                                                                  'unit_opts': {'forget_bias': 0.0}},
                                                       'output': { 'activation': 'identity',
                                                                   'class': 'linear',
                                                                   'dropout': 0.2,
                                                                   'from': ['lstm1'],
                                                                   'n_out': 1030}}},
```

**Comment by nikita68** [comment]
@JackTemaki AFAIK, that works for cases when you want to load the entire network from the checkpoint (though I guess you could hack around that with ``load_ignore_missing`` set to True, but it seems a bit hacky when you only want a single layer from the checkpoint)

**Comment by kazuki-irie** [comment]
You can use `preload_from_files`, I guess.
It's a nested dictionary with 2 keys `filename` and `prefix`.
For all layers in your new network whose layer name starts with `prefix`, it will load the parameters from
the checkpoint specified by `filename` (it will look for the corresponding layer name without the prefix in the given checkpoint).
Something like this:
```
lm_model_filename = "net-model/network.020"  # Checkpoint having a layer "lstm0".
lm_model_prefix = "lm_"

preload_from_files = {
  "load_lm_model" : {"filename": lm_model_filename, "prefix": lm_model_prefix},  # "load_lm_model" is an arbitrary name.
}

network = {
# ...
  "lm_lstm0": {"class": "rec", "unit": "lstm", "n_out": lstm_size, "from": ["input"]},  # Load weights from the layer "lstm0" of the given checkpoint.
# ...
} 
```

**Comment by nikita68** [comment]
True, with ``ignore_missing`` it can also be used to extract a single layer. Thanks!
