### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (1,1025) (0,) 

### ISSUE THREAD

**Issue by j0n4th444n** [rwth-i6/returnn#175]
Hi, I'm using librosa '0.5.1' and I'm having the same issue with the difference I can't update the librosa version. I'm working on a raspberry pi 3 and the newest versions of librosa have some dependencies that can't be installed on my raspbian version.

Please how can i fix this issue in order to extract mfcc feature vector?

## this is the line raising the exception

            mfccs = np.mean(librosa.feature.mfcc(y=wf, sr=sr, n_mfcc=40).T, axis=0)

## this is the code...

    def listening(self):
        self.LED.turnON_led()
        self.AudioPlayer.wakingUp_Notification()
        text, audio = self.STT.listen()
        if audio is not None or text == '':
            self.LED.working_led()
            filename = 'audio.wav'
            file_path = os.path.join(os.getcwd(), 'temp/')
            if not os.path.exists(file_path):
                os.makedirs(file_path)
            audio_path = os.path.join(file_path, filename)
            with open(audio_path, 'wb') as f:
                f.write(audio.get_wav_data())
            wf, sr = librosa.load(audio_path)
            mfccs = np.mean(librosa.feature.mfcc(y=wf, sr=sr, n_mfcc=40).T, axis=0)
            self.Clipboard.append((text, mfccs))
            self.LED.turnOFF_led()
            return not None
        return None

**Comment by albertz** [comment]
You maybe are referring to #132? But as you can read there, this is not a RETURNN issue; this is a librosa issue, which has been reported and discussed here: https://github.com/librosa/librosa/issues/826
The solution is to update librosa (e.g. librosa 0.6.2 works). If that has dependencies which you can not easily install, you have to search for a solution how to install them.
Anyway, this is not RETURNN related, so I'm closing this now.
