### ISSUE TITLE
Demo final text format

### ISSUE THREAD

**Issue by lucgeo** [rwth-i6/returnn#176]
Hi,

I'm trying to run the demo script, everything works fine, but I have a small issue. The obtained transcript contains also some '@@' encodings, more exactly this is an example of my output:

[
(-75.35473, 'IF ANY STILL RETAINED RAN@@ C@@ OR AGAINST HIM IN HIS PRESENT CONDITION THEY PASSED IN SILENCE WHILE HIS WELL WI@@ SH@@ ERS MORE GENEROUS AND PRUDENT ACCOMPANIED HIS MARCH WITH TEARS WITH AC@@ CLAM@@ ATIONS AND WITH PRAYERS FOR HIS SAFETY')
]

I have a simple question: What do I have to change in the config file to obtain the final text-only transcript?

Thank you!

**Comment by albertz** [comment]
It does not do the transformation automatically. But this is trivial to do yourself. Basically if `s` is the string with `'@@'`, you get the final string as `s.replace('@@ ', '')`.

**Comment by albertz** [comment]
Closing now. Please ask if sth is still unclear.
