### ISSUE TITLE
Issue with LmDataset.py input and target values

### ISSUE THREAD

**Issue by ragnarlbrok** [rwth-i6/returnn#188]
I am training LM on librispeech data. I have gone through data pipeline and got confused with input and targets returned by _collect_single_seq function of LMDataset.py.  I printed data and target values during training and got logs like:
data: array(701 398 0)
targets: {'delayed':array(0 701 398)
It seems from logs like targets correspond to previous word instead of next word in a sentence. Can some one clarify these data and targets values and how these values are further being used in LM training?

**Comment by albertz** [comment]
A simple tool to dump the outputs of some dataset is also `tools/dump-dataset.py`.
From the dataset point of view, the dataset just provides some data streams for some data keys (usually "data" and "classes"). By convention, in many cases, "data" is usually the input and "classes" are usually the frame-wise target class indices. (And for historical implementation reasons, there is one `data` attribute which is a Numpy array and a `targets` attribute which is a dict containing all the other data keys.) But it does not have to be that way.
E.g., for the `LmDataset`, this is not the case. There is also no "classes" in `LmDataset`. It has the "data" key, which is the original data itself. And it has another key, the "delayed" key, which is the original data but delayed (prefixed by 0). So, in your network, you would actually use "delayed" as the input, and "data" as the targets. That looks sth like this:
```
{
 "lstm0": {..., "from": "data:delayed"},
 ...
 "output": {..., "target": "data"}
}
```

**Comment by ragnarlbrok** [comment]
Ok, thanks.
