### ISSUE TITLE
Returnn data random_permute 

### ISSUE THREAD

**Issue by yanghongjiazheng** [rwth-i6/returnn#205]
Sorry, I have a question .
I think maybe the code in GeneratingDataset.py line **1038**  get wrong?
```if self.random_permute_opts and self.random_permute_opts.truth_value:```
Maybe it should be changed into
```if self.random_permute_opts !=None and self.random_permute_opts.truth_value:```
I tried to run the following code:
```
from Util import class_idx_seq_to_1_of_k, CollectionReadCheckCovered
random_permute = True
random_permute = CollectionReadCheckCovered.from_bool_or_dict(random_permute)
if random_permute:
     print('success')
```
But the `success` never shows. Could you help me figure out ?
Besides I think I can turn the data random_permute option by set d["audio"]["random_permute"] = True. Am I right?  Thanks for your great work.

**Comment by albertz** [comment]
Thanks for the report. You were completely right. I fixed it in a slightly different way, which should prevent further bugs like this (the old code becomes correct now).
