### ISSUE TITLE
Intended behavior of SliceLayer for negative slice_end values

### ISSUE THREAD

**Issue by ChristopherBrix** [rwth-i6/returnn#206]
What is the intended behavior of the `SliceLayer` for negative `slice_end' values?

Let's say, we have two sequences in our batch, one of length 3, one of length 6 (so `size_placeholder[0] = [3, 6]` and `placeholder.shape[time_dim] = 6`). We want to remove the last time step. I would assume, this could be done using a `SliceLayer` with `axis='T'` and `slice_end=-1`.
But then `slice_end` is [updated](https://github.com/rwth-i6/returnn/blob/master/TFNetworkLayer.py#L2229) to `tf.shape(self.input_data.placeholder)[axis] + slice_end = 6 + (-1) = 5`
And then the new `size_placeholder` is set to `tf.minimum(tf.shape(self.input_data.placeholder)[axis] - slice_end, self.output.size_placeholder[axis_wo_batch])) = tf.minimum(6 - 5, [3, 6]) = [1, 1]`

Is my math wrong? Why don't we just set `self.output.size_placeholder[axis_wo_batch] += slice_end` for negative `slice_end` values? Maybe with an additional check that the sequence lengths don't become negative.

**Comment by albertz** [comment]
I recently also stumbled upon this, or at least that I wanted to have such a functionality, and saw that `SliceLayer` behaves differently. Although then for some reason I decided to do it differently or that it was not a good idea anyway or so (I don't exactly remember anymore).
I'm not sure which of the two behaviors (the existing one, and the one you describe) is more correct or is the canonical one (i.e. which you would assume as the default one if you don't set it).
I'm also not exactly sure, if we change the default behavior now, if it breaks something for someone. Although probably this is not used too much (I don't know).
But maybe you are right, and we should change this behavior. So I would say, for the beginning without any new option, just change it (i.e. make a pull request with the change). But if anyone ever gets back to this, and wants the old behavior, we should introduce an option to make it configurable (and then maybe we again can discuss the default behavior, or maybe even require this to be an explicit setting, without default).
Maybe @Spotlight0xff has also an opinion on this.

**Comment by Spotlight0xff** [comment]
My code only uses the `SliceNdLayer`, I have never used `SliceLayer`.
That being said, I would also assume the behavior you expected (resulting in `size_pl[0]=[2, 5]`).

**Comment by albertz** [comment]
Actually, I just realized, `tf.shape(self.input_data.placeholder)[axis] - slice_end` is wrong in any case (no matter if `slice_end` is positive or negative). That never makes sense. This is actually a serious bug.

**Comment by ChristopherBrix** [comment]
I've created a PR for this. I still need to add some test cases, but I've run it manually and it looks good.
