### ISSUE TITLE
SubnetworkRecCell: size_placeholder of outputs not resolved

### ISSUE THREAD

**Issue by patrick-wilken** [rwth-i6/returnn#225]
I have the following configuration in my recurrent unit:

Choice layers C1 and C2, end layer E
C2 depends on C1, but not on E
E depends on C1

C2 is the last choice layer, thus defines the beam to which all outputs are resolved to (via `_opt_search_resolve()`). C1 is resolved to C2, this works.
However, the size_placeholder of all outputs is set to `seq_len` (in `get_loop_acc_layer()`), which itself comes from the length information of the end layer. In my case, the end layer has beams according to C1, not C2. Resolving these beams is currently missing, giving a shape mismatch in case of different beam sizes or, even worse, outputs of wrong length in case of same beam sizes.

I'm trying to figure out where to do this, but maybe you, @albertz, have an idea right away.

**Comment by albertz** [comment]
Yes, I think it is currently assumed in some places that the end layer has the same beam as the latest choice inside the rec unit. You can enforce this by using `CopyLayer` with `extra_deps`.
Later we should fix this maybe in an automatic way, or make at least a better error message.
