### ISSUE TITLE
Asking about num_outputs  in config

### ISSUE THREAD

**Issue by sanakhamekhem** [rwth-i6/returnn#23]
Hi , I would like to ask about ""num_outputs": {"data": [1,2], "classes": [79,1], "sizes": [2,1]}," which is in the file config real,
Concerning my own dataset, I have 107 units (like charlist : aaA, baB.....)
Then is it correct to make this:
num_outputs": {"data": [1,2], "classes": [107,1], "sizes": [2,1]},
and what are "data": [1,2],"sizes": [2,1]  ????
Thanks in advance

**Comment by sanakhamekhem** [comment]
Besides, I would ask about how can I extract the log probabilies of the recognized frames in order to decode them using a decoder software.
Thanks.

**Comment by pvoigtlaender** [comment]
Hi,

the [1,2] and [2,1] entries in data and sizes should better not be touched. the 79 means we have 79 characters (excluding the CTC blank), so yes, it's correct to change it to 107 if you have 107 characters.

To extract posteriors, you can use the config_fwd of the mdlstm example. 
Then you can do a very simple decoding (without language model, or lexicon) using decode.py to see if it is working.

**Comment by sanakhamekhem** [comment]
Hi, thank you for your response.
I have used this code to decode:
`#!/usr/bin/env python

import h5py
import numpy

with open("chars.txt") as f:
  chars = [l.strip() for l in f.readlines()]
print chars
with h5py.File("mdlstm_real_test.h5", "r") as f:
  x = f["inputs"][...]
  x = numpy.argmax(x, axis=1)
  print 'x: ', x
  x = [chars[idx] for idx in x]
  **print 'char:' , x**
  lens = f["seqLengths"][...]
  tags = f["seqTags"][...]
  start = 0
  for tag, len_ in zip(tags, lens):
    y = []
    last_char = None
    for c in x[start:start+len_]:
      if last_char != c:
        y.append(c)
        last_char = c
    y = [" " if c == "|" else c for c in y]
    output = "".join(y).strip()
    print tag, output
    start += len_`

the char list : ['<UNK>', '<SPACE>', 'aaA', 'aaE', 'aeA', 'aeE'.....]

But, x contains: char: ['|', '|', '|', '|', '|', '|', '|', '|', '|', '|',................
and no result in the decoding, no output

**Comment by pvoigtlaender** [comment]
Hi,

please first make sure that the demo including decoding works for you. Is this the case?

**Comment by sanakhamekhem** [comment]
I did not test it, I will verify, thanks

**Comment by sanakhamekhem** [comment]
I have just a question, when we train the MDLSTM for line images which are written from right to left,
 is there some parameters to change in the code or config??
such the case of Arabic text,
Thanks

**Comment by pvoigtlaender** [comment]
We don't have such an option unfortunately. One possibility would be to explicitly flip the images and overwrite them with the flipped versions, or do the flipping when converting the raw images to hdf5.

**Comment by sanakhamekhem** [comment]
I have done this when I convert to hdf5: 
img = imread(img_name)
rimg = cv2.flip(img, 1)
....................
