### ISSUE TITLE
Fetching full trace of beam search

### ISSUE THREAD

**Issue by Ore-an** [rwth-i6/returnn#231]
I'd like to get the full trace of the beam search during decoding, but I've encountered a problem. Fetching the output of the recurrent cell itself only gives the n-best, and this means you don't get the full set of n choices at each timestep, but accessing the 'choice' part of the cell is impossible, as it's a TensorArray and it's set to clear after read for memory management purposes. Any suggestions on how I could fetch the full trace? 

I'm using the TensorFlow backend, and the decoder cell is the same as the one used for the LibriSpeech attention models, like the pretrained one you released.

**Comment by albertz** [comment]
There are many ways how to get that.

For simple debugging: You can e.g. add an `EvalLayer` right after the `ChoiceLayer`, and use `tf.Print`. You can access the beam information via `self.get_search_choices()` (beam scores and source beam indices) inside the eval function. You can also extend this, by using `tf.py_func`, and then dump all the information you want, in whatever way you want.

In a more principled way: Use `ChoiceGetSrcBeamsLayer`, `ChoiceGetBeamScoresLayer`, `DecideKeepBeamLayer` and `HDFDumpLayer`. We currently work on a script which automatically adds these layers and dumps all these information to HDF files, which you can see [here](https://github.com/rwth-i6/returnn/blob/albert-compile-wip/tools/debug-dump-search-scores.py). But this is currently work-in-progress (it might already work; not sure...).

**Comment by albertz** [comment]
I further improved the script [debug-dump-search-scores.py](https://github.com/rwth-i6/returnn/blob/albert-debug-search-script/tools/debug-dump-search-scores.py).

I also added another script [debug-interactive-search-scores.py](https://github.com/rwth-i6/returnn/blob/albert-debug-search-script/tools/debug-interactive-search-scores.py), which demonstrates how you get the search choices and scores and other information.

**Comment by albertz** [comment]
I did some more updates to the scripts, and also pushed them to the master branch now.
Please comment if you miss anything. I'm closing this for now.

**Comment by Ore-an** [comment]
Thanks, the two new layers `ChoiceGetSrcBeamsLayer` and `ChoiceGetBeamScoresLayer` work perfectly for what I was trying to do. For now, I added them to the network itself when decoding, but I'm looking at your scripts for a better, more general way to do it.
