### ISSUE TITLE
Determining the shape of "prev:" value in eval layer

### ISSUE THREAD

**Issue by JackTemaki** [rwth-i6/returnn#234]
This is more a question than an issue: when using the output of an eval layer as input to itself with "prev:", what determines its shape? I am using the following eval layer:

```
'att_weights': { 'class': 'eval',
    'eval': "self.network.get_config().typed_value('_stepwise_monotonic_probability_fn')(source(0, as_data=True), source(1, as_data=True), 2.0, 'parallel')",
    'from': ['att_energy', 'prev:att_weights'],
    'out_type': {'batch_dim_axis': 0, 'feature_dim_axis': 2, 'time_dim_axis': 1}},

```
And now the shape of `att_energy` is [B, T, 1], and of `prev:att_weights` is [B, 1, 1], but I wanted them to be the same. So what I used as solution is:

```
def init():
    return tf.zeros_like(score)

def compute():
    return previous_alignments

previous_alignments = tf.cond(tf.reduce_sum(previous_alignments) < 0.01, init, compute)
```

where score is based on energy. Is there a different approach for this without using tf.cond by directly specifying the shape of the first feedback?

**Comment by JackTemaki** [comment]
Yes, i was speaking only of the initial value. I will use `tf.cond` as solution then, because my code can not do automatic broadcasting.

**Comment by albertz** [comment]
Note that `tf.cond(tf.equal(network.get_rec_step_index(), 0), ...)` might be a more clean check.
