### ISSUE TITLE
adapt model to single writer

### ISSUE THREAD

**Issue by xdsv** [rwth-i6/returnn#25]
Is there a way to adapt a model (that has been trained on IAM) to the handwriting of a single writer? 
Would that make a substantial difference to the recognition accuracy (for that writer)?

**Comment by pvoigtlaender** [comment]
Hi,

you can first train on all data jointly and then start a second training, where you load the model from the first training, but this time you only train on the data of the specific writer.
This should probably boost the accuracy, but this of course depends on the amount of available adaptation data.
There are also many more elaborate methods for speaker/writer adaptation, but you would need to implement these yourself.

**Comment by xdsv** [comment]
Can you elaborate on how to do this step by step?
Also, how much writer data is "enough" (approximately) in order to get good results?

**Comment by albertz** [comment]
This is research. You have to try out and read other research papers. See option `import_model_train_epoch1` to start a new training where you import an existing model at the beginning.

As this is not really a bug in Returnn, I'm closing this issue now. If you want to discuss further, better ask by mail. But I am not sure if anyone from us can give much more advice than that. As said, this is research.
