### ISSUE TITLE
blocksparse can't find libtensorflow_framework.so with TF 1.15 + GPU

### ISSUE THREAD

**Issue by pzelasko** [rwth-i6/returnn#252]
To reproduce:

    pip install tensorflow_gpu==1.15.0
    nosetests tests/test_TFNativeOp.py:test_init_blocksparse

The message says:

    tensorflow.python.framework.errors_impl.NotFoundError: libtensorflow_framework.so: cannot open shared object file: No such file or directory

Since tensorflow 1.14 they renamed `libtensorflow_framework.so` -> `libtensorflow_framework.so.1`. 

Possible solutions:
- `blocksparse` could be recompiled with TF >= 1.14 so that the new lib name is registered in the wheel 
- create a symlink next to `libtensorflow_framework.so.1` with the expected name

**Comment by albertz** [comment]
We compile `blocksparse` ourselves here, there is no wheel.
Also, it uses our `OpCodeCompiler`, which should use the correct so-file now, or not?

**Comment by pzelasko** [comment]
Probably yes - I only tested with a pip-downloaded version.

pt., 6 gru 2019, 16:46 użytkownik Albert Zeyer <notifications@github.com>
napisał:

**Comment by albertz** [comment]
Hm ok, strange that it even worked then. You are supposed to check out the submodule for this.
Anyway, closing for now, unless this can be reproduced with the right blocksparse module.
