### ISSUE TITLE
Training on top of Librispeech checkpoint (For accent training)

### ISSUE THREAD

**Issue by Shilpil** [rwth-i6/returnn#256]
Hi,
I trained Librispeech data using base2.conv2l.specaug.curric3.config for 250 epochs. Since many audio clips were not recognised correctly I want to continue the training on Indian accent data that we have collected. When I try to restore the 250th checkpoint the following error is thrown :
InvalidArgumentError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint.

I have attatched the original, changed config files and the error logs

Original config file (For Librispeech) : 
[base2.conv2l.specaug.curric3.txt](https://github.com/rwth-i6/returnn/files/3966815/base2.conv2l.specaug.curric3.txt)

Modified config file (For our data) :
The major modification is the class of dataset from LibriSpeechCorpus to OggZipDataset, the log locations and importing the checkpoint
[base2.conv2l.specaug.curric3.indian.txt](https://github.com/rwth-i6/returnn/files/3966819/base2.conv2l.specaug.curric3.indian.txt)

Error logs : 
[crnn.train.indian.horovod-0-1.log](https://github.com/rwth-i6/returnn/files/3966822/crnn.train.indian.horovod-0-1.log)

If we uncomment : 'use_new_filter': True,
The following error is thrown : 
[crnn.train.indian.horovod2.log](https://github.com/rwth-i6/returnn/files/3966835/crnn.train.indian.horovod2.log)

If anyone can point out the error in my config file I will be very thankful.

Thanks

**Comment by albertz** [comment]
`use_new_filter` is an option only for `LibriSpeechCorpus`, not for `OggZipDataset`. That is why it complains with that.

The other error is because it tries to load some existing model params (`loading weights from /home/ubuntu/returnn/net-model/network.250`), but there is some param which has a different shape in your model than in the checkpoint. That is why you get the exception
```
InvalidArgumentError: Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [1024,1] rhs shape= [2048,1]
         [[node saver/save/Assign_9 (defined at /home/ubuntu/returnn/TFNetwork.py:1371) ]]
         [[node saver/save/RestoreV2 (defined at /home/ubuntu/returnn/TFNetwork.py:1371) ]]
```
Unfortunately I cannot see from this log which param/variable that is. But in any case, this probably happened because you have trained the model with a different config.

**Comment by Shilpil** [comment]
Hi,
Yes I removed `use_new_filter`. Since I wanted to find a workaround I just continued training with OggZipDataset by increasing the epochs and keeping everything else the same ( net-model and log locations, learning_rate file etc ). So instead if loading weights from that checpoint it just continued training as the 251st epoch.
