### ISSUE TITLE
TensorFlow 2 compatibility

### ISSUE THREAD

**Issue by manish-kumar-garg** [rwth-i6/returnn#261]
Are there any plans to make this compatible with tensorflow2.0?

**Comment by albertz** [comment]
Yes. This is work-in-progress. There is also a branch for that [here](https://github.com/rwth-i6/returnn/tree/tf2). But it's incomplete so far.

**Comment by albertz** [comment]
I'm closing this now. All further discussion will happen here: #283

**Comment by albertz** [comment]
Some update here: This should work now. Please test. If there are problems, please report in #283.
