### ISSUE TITLE
adding new layers in a pretrained network

### ISSUE THREAD

**Issue by ragnarlbrok** [rwth-i6/returnn#264]
I have a pretrained network, now I added some more layers in network and tried to load the network from checkpoint of pretrained network. It threw error for new layers as they are not in checkpoint. So any way to do that?Basically I want to initialize pretrained layers form checkpoint and new added layers to initialize randomly in new network.

**Comment by albertz** [comment]
This is supported via `preload_from_files`. Example:
```
preload_from_files = {
  "existing-model": {
    "init_for_train": True,   
    "ignore_missing": True,
    "filename": ".../net-model/network.163",  # your checkpoint file
  }             
}              
```

**Comment by ragnarlbrok** [comment]
ok, thanks.
