### ISSUE TITLE
Meaning of "base:" tag

### ISSUE THREAD

**Issue by manish-kumar-garg** [rwth-i6/returnn#269]
What is the meaning of adding `base` tag for example:
```
"s":{"class":"rnn_cell","unit":"standardlstm","n_out":20,"from":["prev:embed","base:input_last"]}
```
What is the significance of `base: input_last` here?

**Comment by patrick-wilken** [comment]
It refers to the base network. The "s" layer is part of a subnetwork (probably the unit of a rec-layer), so by adding "base:" you have access to layers outside the subnetwork.

**Comment by manish-kumar-garg** [comment]
Ok. Thanks!
