### ISSUE TITLE
Error: Op type not registered 'NativeLstm2'

### ISSUE THREAD

**Issue by ValeriyMarkin** [rwth-i6/returnn#277]
I am trying to restore a model from saved files. I run the following code 

> with tf.Session() as sess:
    saver = tf.train.import_meta_graph("./model.009.meta",clear_devices=True)
 saver.restore(sess, "./model.009")

and get 

`tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'NativeLstm2' in binary running on valeriy-VivoBook-S15-X530UN. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) 'tf.contrib.resampler' should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.`

I have looked through some same issues, but it still doesn't work for me.
I have Linux and TF 1.15

**Comment by albertz** [comment]
It means the Op type is not registered. You need to register it first.

For example, you could do so by running:
```
from returnn.TFNativeOp import make_op
from returnn.NativeOp import NativeLstm2
make_op(NativeLstm2)
```
This is not really RETURNN related. This is in general how TensorFlow works. You first need to register all op types which you want to use.
