### ISSUE TITLE
Error running IAM demo

### ISSUE THREAD

**Issue by dutta1kartik3** [rwth-i6/returnn#28]
I attempted to run the example in the demos/mdlstm/IAM folder. Here is the terminal output when a run the go.sh file:

WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next release (v0.10).  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

Using gpu device 0: GeForce GTX 1080 Ti (CNMeM is disabled, cuDNN not available)
RETURNN starting up, version 20160714.042013--git-5a40490-dirty, pid 12085, cwd /home/kartik/new_returnn/demos/mdlstm/IAM
RETURNN command line options: ['config_fwd_kd']
Theano: 0.9.0 (<site-package> in /home/kartik/.local/lib/python2.7/site-packages/theano)
CUDA already initialized in proc 12085
WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next release (v0.10).  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

ERROR (theano.sandbox.cuda): ERROR: Not using GPU. Initialisation of device gpu failed:
Not able to select available GPU from 1 cards (all CUDA-capable devices are busy or unavailable).
EXCEPTION
Traceback (most recent call last):
  File "/home/kartik/new_returnn/TaskSystem.py", line 1381, in <module>
    line: ExecingProcess.checkExec()  # Never returns if this proc is called via ExecingProcess.
    locals:
      ExecingProcess = <local> <class __main__.ExecingProcess at 0x7f7f3c140d50>
      ExecingProcess.checkExec = <local> <function checkExec at 0x7f7f3c171488>
  File "/home/kartik/new_returnn/TaskSystem.py", line 1001, in checkExec
    line: args = unpickler.load()
    locals:
      args = <not found>
      unpickler = <local> <pickle.Unpickler instance at 0x7f7f3c16de60>
      unpickler.load = <local> <bound method Unpickler.load of <pickle.Unpickler instance at 0x7f7f3c16de60>>
  File "/usr/lib/python2.7/pickle.py", line 864, in load
    line: dispatch[key](self)
    locals:
      dispatch = <local> {'': <function load_eof at 0x7f7fa3ca50c8>, '\x80': <function load_proto at 0x7f7fa3ca5140>, '\x83': <function load_ext2 at 0x7f7fa3ca6230>, '\x82': <function load_ext1 at 0x7f7fa3ca61b8>, '\x85': <function load_tuple1 at 0x7f7fa3ca5b90>, '\x84': <function load_ext4 at 0x7f7fa3ca62a8>, '\x87': <f..., len = 54
      key = <local> 'R'
      self = <local> <pickle.Unpickler instance at 0x7f7f3c16de60>
  File "/usr/lib/python2.7/pickle.py", line 1139, in load_reduce
    line: value = func(*args)
    locals:
      value = <not found>
      func = <local> <function getModuleDict at 0x7f7f9f4686e0>
      args = <local> ('Device', ['/home/kartik/new_returnn', '/home/kartik/.local/lib/python2.7/site-packages/PyTorch-4.1.1_SNAPSHOT-py2.7-linux-x86_64.egg', '/home/kartik/.local/lib/python2.7/site-packages/voc_utils-0.0-py2.7.egg', '/home/kartik/.local/lib/python2.7/site-packages/more_itertools-3.1.0-py2.7.egg', '/h..., _[0]: {len = 6}
  File "/home/kartik/new_returnn/TaskSystem.py", line 552, in getModuleDict
    line: mod = import_module(modname)
    locals:
      mod = <not found>
      import_module = <global> <function import_module at 0x7f7fa3ca6f50>
      modname = <local> 'Device', len = 6
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    line: __import__(name)
    locals:
      __import__ = <builtin> <built-in function __import__>
      name = <local> 'Device', len = 6
  File "/home/kartik/new_returnn/Device.py", line 5, in <module>
    line: from Updater import Updater
    locals:
      Updater = <not found>
  File "/home/kartik/new_returnn/Updater.py", line 4, in <module>
    line: import theano
    locals:
      theano = <not found>
  File "/home/kartik/.local/lib/python2.7/site-packages/theano/__init__.py", line 108, in <module>
    line: import theano.sandbox.cuda
    locals:
      theano = <local> <module 'theano' from '/home/kartik/.local/lib/python2.7/site-packages/theano/__init__.pyc'>
      theano.sandbox = <local> <module 'theano.sandbox' from '/home/kartik/.local/lib/python2.7/site-packages/theano/sandbox/__init__.pyc'>
      theano.sandbox.cuda = <local> !AttributeError: 'module' object has no attribute 'cuda'
  File "/home/kartik/.local/lib/python2.7/site-packages/theano/sandbox/cuda/__init__.py", line 728, in <module>
    line: use(device=config.device, force=config.force_device, test_driver=False)
    locals:
      use = <local> None
      device = <not found>
      config = <local> None
      config.device = <local> !AttributeError: 'NoneType' object has no attribute 'device'
      force = <not found>
      config.force_device = <local> !AttributeError: 'NoneType' object has no attribute 'force_device'
      test_driver = <not found>
  File "/home/kartik/.local/lib/python2.7/site-packages/theano/sandbox/cuda/__init__.py", line 586, in use
    line: cuda_ndarray.cuda_ndarray.select_a_gpu()
    locals:
      cuda_ndarray = <global> None
      cuda_ndarray.cuda_ndarray = <global> !AttributeError: 'NoneType' object has no attribute 'cuda_ndarray'
      cuda_ndarray.cuda_ndarray.select_a_gpu = <global> !AttributeError: 'NoneType' object has no attribute 'cuda_ndarray'
RuntimeError: ('Not able to select available GPU from 1 cards (all CUDA-capable devices are busy or unavailable).', 'You asked to force this device and it failed. No fallback to the cpu or other gpu device.')
Device proc gpuX (gpuZ) died: ProcConnectionDied('recv_bytes EOFError: ',)
Theano flags: compiledir_format=compiledir_%(platform)s-%(processor)s-%(python_version)s-%(python_bitwidth)s--dev-gpuZ,device=gpu,force_device=True
EXCEPTION
Traceback (most recent call last):
  File "/home/kartik/new_returnn/Device.py", line 332, in startProc
    line: self._startProc(*args, **kwargs)
    locals:
      self = <local> <Device.Device object at 0x7f703bc37210>
      self._startProc = <local> <bound method Device._startProc of <Device.Device object at 0x7f703bc37210>>
      args = <local> ('gpuZ',)
      kwargs = <local> {}
  File "/home/kartik/new_returnn/Device.py", line 386, in _startProc
    line: interrupt_main()
    locals:
      interrupt_main = <global> <function interrupt_main at 0x7f70405c08c0>
  File "/home/kartik/new_returnn/Util.py", line 637, in interrupt_main
    line: sys.exit(1)  # And exit the thread.
    locals:
      sys = <global> <module 'sys' (built-in)>
      sys.exit = <global> <built-in function exit>
SystemExit: 1
ERR!\nKeyboardInterrupt
EXCEPTION
Traceback (most recent call last):
  File "../../../rnn.py", line 532, in main
    line: init(commandLineOptions=argv[1:])
    locals:
      init = <global> <function init at 0x7f703bc2cc08>
      commandLineOptions = <not found>
      argv = <local> ['../../../rnn.py', 'config_fwd_kd'], _[0]: {len = 15}
  File "../../../rnn.py", line 345, in init
    line: devices = initDevices()
    locals:
      devices = <not found>
      initDevices = <global> <function initDevices at 0x7f703bc2c848>
  File "../../../rnn.py", line 158, in initDevices
    line: time.sleep(0.25)
    locals:
      time = <global> <module 'time' (built-in)>
      time.sleep = <global> <built-in function sleep>
KeyboardInterrupt
Quitting

**Comment by pvoigtlaender** [comment]
The output contains

'Not able to select available GPU from 1 cards (all CUDA-capable devices are busy or unavailable

Are you sure, that there was a free GPU when running it?

**Comment by dutta1kartik3** [comment]
I was able to run the GPU demo given at (http://deeplearning.net/software/theano/tutorial/using_gpu.html). The gpu was detected in that case and the demo program ran without any issues, outputting "Used the gpu". The GPU had no other process running at the time when I tried to run the demo or when I tried to run the go.sh file.

I had set device=cuda in my .theanorc file while running the above demo program.

**Comment by pvoigtlaender** [comment]
Please set device=cpu in the .theanorc and try again.
Even though it will be set to cpu, RETURNN will aquire the GPU in a background process.

**Comment by dutta1kartik3** [comment]
I get a new error upon setting device=cpu in .theanorc. I suppose I need to ensure cudnn is being detected by theano ?

RETURNN starting up, version 20160714.042013--git-5a40490-dirty, pid 36431, cwd /home/kartik/new_returnn/demos/mdlstm/IAM
RETURNN command line options: ['config_fwd_kd']
Theano: 0.9.0 (<site-package> in /home/kartik/.local/lib/python2.7/site-packages/theano)
WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next release (v0.10).  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

Using gpu device 0: GeForce GTX 1080 Ti (CNMeM is disabled, cuDNN not available)
Device gpuX proc starting up, pid 36557
Device gpuX proc: THEANO_FLAGS = 'compiledir_format=compiledir_%(platform)s-%(processor)s-%(python_version)s-%(python_bitwidth)s--dev-gpuZ,device=gpu,force_device=True'
Device train-network: Used data keys: ['classes', 'data', 'sizes']
^[[F^[[ADevice gpuX proc exception: ('The following error happened while compiling the node', CuDNNConvHWBCOp{border_mode='valid'}(GpuContiguous.0, GpuContiguous.0, GpuContiguous.0), '\n', "We can't determine the cudnn version as it is not available", "Can not compile with cuDNN. We got this error:\nnvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).\n/tmp/try_flags_mfyHIk.c:5:19: fatal error: cudnn.h: No such file or directory\ncompilation terminated.\n")
Unhandled exception <type 'exceptions.Exception'> in thread <_MainThread(MainThread, started 140098489444096)>, proc 36557.

Thread current, main, <_MainThread(MainThread, started 140098489444096)>:
(Excluded thread.)

That were all threads.
EXCEPTION
Traceback (most recent call last):
  File "/home/kartik/new_returnn/Device.py", line 982, in process
    line: self.process_inner(device, config, self.update_specs, asyncTask)
    locals:
      self = <local> <Device.Device object at 0x7f6ac2f621d0>
      self.process_inner = <local> <bound method Device.process_inner of <Device.Device object at 0x7f6ac2f621d0>>
      device = <local> 'gpuX'
      config = <local> <Config.Config instance at 0x7f6ac2f676c8>
      self.update_specs = <local> {'layers': [], 'block_size': 0, 'update_params': {}, 'update_rule': 'global'}
      asyncTask = <local> <TaskSystem.AsyncTask instance at 0x7f6ad0c58f80>
  File "/home/kartik/new_returnn/Device.py", line 1035, in process_inner
    line: self.initialize(config, update_specs=update_specs)
    locals:
      self = <local> <Device.Device object at 0x7f6ac2f621d0>
      self.initialize = <local> <bound method Device.initialize of <Device.Device object at 0x7f6ac2f621d0>>
      config = <local> <Config.Config instance at 0x7f6ac2f676c8>
      update_specs = <local> {'layers': [], 'block_size': 0, 'update_params': {}, 'update_rule': 'global'}
  File "/home/kartik/new_returnn/Device.py", line 808, in initialize
    line: self.extractor = theano.function(inputs = [],
                                           outputs = source if len(source) == 1 else [T.concatenate(source, axis=-1)],
                                           givens = givens,
                                           on_unused_input=config.value('theano_on_unused_input', 'ignore'),
                                           name = "extractor")
    locals:
      self = <local> <Device.Device object at 0x7f6ac2f621d0>
      self.extractor = <local> !AttributeError: 'Device' object has no attribute 'extractor'
      theano = <local> <module 'theano' from '/home/kartik/.local/lib/python2.7/site-packages/theano/__init__.pyc'>
      theano.function = <local> <function function at 0x7f6b32b738c0>
      inputs = <not found>
      outputs = <not found>
      source = <local> [Elemwise{switch,no_inplace}.0]
      len = <builtin> <built-in function len>
      T = <local> <module 'theano.tensor' from '/home/kartik/.local/lib/python2.7/site-packages/theano/tensor/__init__.pyc'>
      T.concatenate = <local> <function concatenate at 0x7f6b29823848>
      axis = <not found>
      givens = <local> [(y_classes, y_classes), (x, y_data), (y_sizes, y_sizes), (j_classes, j_classes), (i, j_data), (j_sizes, j_sizes), (tags, tags_var)], len = 7
      on_unused_input = <not found>
      config = <local> <Config.Config instance at 0x7f6ac2f676c8>
      config.value = <local> <bound method Config.value of <Config.Config instance at 0x7f6ac2f676c8>>
      name = <not found>
  File "/home/kartik/.local/lib/python2.7/site-packages/theano/compile/function.py", line 326, in function
    line: fn = pfunc(params=inputs,
                     outputs=outputs,
                     mode=mode,
                     updates=updates,
                     givens=givens,
                     no_default_updates=no_default_updates,
                     accept_inplace=accept_inplace, name=name,
                     rebuild_strict=rebuild_strict,
                     allow_input_downcast=allow_input_downcast,
                     on_unused_input=on_unused_input,
                     profile=profile,
                     output_keys=output_keys)
    locals:
      fn = <not found>
      pfunc = <global> <function pfunc at 0x7f6b32bd3758>
      params = <not found>
      inputs = <local> []
      outputs = <local> [Elemwise{switch,no_inplace}.0]
      mode = <local> None
      updates = <local> []
      givens = <local> [(y_classes, y_classes), (x, y_data), (y_sizes, y_sizes), (j_classes, j_classes), (i, j_data), (j_sizes, j_sizes), (tags, tags_var)], len = 7
      no_default_updates = <local> False
      accept_inplace = <local> False
      name = <local> 'extractor', len = 9
      rebuild_strict = <local> True
      allow_input_downcast = <local> None
      on_unused_input = <local> 'ignore', len = 6
      profile = <local> None
      output_keys = <local> None
  File "/home/kartik/.local/lib/python2.7/site-packages/theano/compile/pfunc.py", line 486, in pfunc
    line: return orig_function(inputs, cloned_outputs, mode,
                               accept_inplace=accept_inplace, name=name,
                               profile=profile, on_unused_input=on_unused_input,
                               output_keys=output_keys)
    locals:
      orig_function = <global> <function orig_function at 0x7f6b32bbb1b8>
      inputs = <local> [In(y_classes), In(y_data), In(y_sizes), In(j_classes), In(j_data), In(j_sizes), In(tags_var), In(W_conv0), In(b_conv0), In(W1_mdlstm0), In(W2_mdlstm0), In(W3_mdlstm0), In(W4_mdlstm0), In(U1_mdlstm0), In(U2_mdlstm0), In(U3_mdlstm0), In(U4_mdlstm0), In(V1_mdlstm0), In(V2_mdlstm0), In(V3_mdlstm0), ..., len = 99
      cloned_outputs = <local> [Elemwise{switch,no_inplace}.0]
      mode = <local> None
      accept_inplace = <local> False
      name = <local> 'extractor', len = 9
      profile = <local> None
      on_unused_input = <local> 'ignore', len = 6
      output_keys = <local> None
  File "/home/kartik/.local/lib/python2.7/site-packages/theano/compile/function_module.py", line 1795, in orig_function
    line: fn = Maker(inputs,
                     outputs,
                     mode,
                     accept_inplace=accept_inplace,
                     profile=profile,
                     on_unused_input=on_unused_input,
                     output_keys=output_keys).create(
              defaults)
    locals:
      fn = <not found>
      Maker = <local> <class 'theano.compile.function_module.FunctionMaker'>
      inputs = <local> [In(y_classes), In(y_data), In(y_sizes), In(j_classes), In(j_data), In(j_sizes), In(tags_var), In(W_conv0), In(b_conv0), In(W1_mdlstm0), In(W2_mdlstm0), In(W3_mdlstm0), In(W4_mdlstm0), In(U1_mdlstm0), In(U2_mdlstm0), In(U3_mdlstm0), In(U4_mdlstm0), In(V1_mdlstm0), In(V2_mdlstm0), In(V3_mdlstm0), ..., len = 99
      outputs = <local> [Out(Elemwise{switch,no_inplace}.0,False)]
      mode = <local> <theano.compile.mode.Mode object at 0x7f6b236fd690>
      accept_inplace = <local> False
      profile = <local> None
      on_unused_input = <local> 'ignore', len = 6
      output_keys = <local> None
      create = <not found>
      defaults = <local> [<array([[0]], dtype=int32)>, <CudaNdarray([[[ 0.]]])>, <array([[0]], dtype=int32)>, <array([[0]], dtype=int8)>, <array([[0]], dtype=int8)>, <array([[0]], dtype=int8)>, <array([], shape=(0, 0), dtype=int8)>, <CudaNdarray([[[[-0.21161591  0.08376592 -0.04271842]
                            [ 0.19575438  0.19206183 -0.1560..., len = 99
  File "/home/kartik/.local/lib/python2.7/site-packages/theano/compile/function_module.py", line 1661, in create
    line: _fn, _i, _o = self.linker.make_thunk(
              input_storage=input_storage_lists, storage_map=storage_map)
    locals:
      _fn = <not found>
      _i = <not found>
      _o = <not found>
      self = <local> <theano.compile.function_module.FunctionMaker object at 0x7f6ab498ca10>
      self.linker = <local> <theano.gof.vm.VM_Linker object at 0x7f6ab498c450>
      self.linker.make_thunk = <local> <bound method VM_Linker.make_thunk of <theano.gof.vm.VM_Linker object at 0x7f6ab498c450>>
      input_storage = <local> [<array([[0]], dtype=int32)>, <CudaNdarray([[[ 0.]]])>, <array([[0]], dtype=int32)>, <array([[0]], dtype=int8)>, <array([[0]], dtype=int8)>, <array([[0]], dtype=int8)>, <array([], shape=(0, 0), dtype=int8)>, <CudaNdarray([[[[-0.21161591  0.08376592 -0.04271842]
                                 [ 0.19575438  0.19206183 -0.1560..., len = 99
      input_storage_lists = <local> [[array([[0]], dtype=int32)], [CudaNdarray([[[ 0.]]])], [array([[0]], dtype=int32)], [array([[0]], dtype=int8)], [array([[0]], dtype=int8)], [array([[0]], dtype=int8)], [array([], shape=(0, 0), dtype=int8)], [CudaNdarray([[[[-0.21161591  0.08376592 -0.04271842]
                                       [ 0.19575438  0.19206183 -0.1560..., len = 99, _[0]: {_[0]: {len = 1, _[0]: {len = 1}}}
      storage_map = <local> None
  File "/home/kartik/.local/lib/python2.7/site-packages/theano/gof/link.py", line 699, in make_thunk
    line: return self.make_all(input_storage=input_storage,
                               output_storage=output_storage,
                               storage_map=storage_map)[:3]
    locals:
      self = <local> <theano.gof.vm.VM_Linker object at 0x7f6ab498c450>
      self.make_all = <local> <bound method VM_Linker.make_all of <theano.gof.vm.VM_Linker object at 0x7f6ab498c450>>
      input_storage = <local> [[array([[0]], dtype=int32)], [CudaNdarray([[[ 0.]]])], [array([[0]], dtype=int32)], [array([[0]], dtype=int8)], [array([[0]], dtype=int8)], [array([[0]], dtype=int8)], [array([], shape=(0, 0), dtype=int8)], [CudaNdarray([[[[-0.21161591  0.08376592 -0.04271842]
                                 [ 0.19575438  0.19206183 -0.1560..., len = 99, _[0]: {_[0]: {len = 1, _[0]: {len = 1}}}
      output_storage = <local> None
      storage_map = <local> None
  File "/home/kartik/.local/lib/python2.7/site-packages/theano/gof/vm.py", line 1047, in make_all
    line: thunks.append(node.op.make_thunk(node,
                                           storage_map,
                                           compute_map,
                                           no_recycling,
                                           impl=impl))
    locals:
      thunks = <local> [<function rval at 0x7f6ab5efed70>, <function rval at 0x7f6ab8306050>, <function rval at 0x7f6ab5d4f1b8>, <function rval at 0x7f6ab5d4f320>, <function rval at 0x7f6ab5d4fb90>, <function rval at 0x7f6ab5d4fc08>, <function rval at 0x7f6ab5d4f398>, <function rval at 0x7f6ab82a4758>, <function rval a..., len = 183
      thunks.append = <local> <built-in method append of list object at 0x7f6aaf520998>
      node = <local> CuDNNConvHWBCOp{border_mode='valid'}(GpuContiguous.0, GpuContiguous.0, GpuContiguous.0)
      node.op = <local> <cuda_implementation.CuDNNConvHWBCOp.CuDNNConvHWBCOp object at 0x7f6ac30273d0>
      node.op.make_thunk = <local> <bound method CuDNNConvHWBCOp.make_thunk of <cuda_implementation.CuDNNConvHWBCOp.CuDNNConvHWBCOp object at 0x7f6ac30273d0>>
      storage_map = <local> {b_conv3: [CudaNdarray([ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
                              0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
                              0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
                              0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0..., len = 733
      compute_map = <local> {ScalarFromTensor.0: [False], V1_mdlstm2: [True], b_conv3: [True], Subtensor{::, int64}.0: [False], W1_mdlstm3: [True], Subtensor{::, int64}.0: [False], W2_mdlstm3: [True], MultiDirectionalTwoDLSTMOp.0: [False], y_sizes: [True], Elemwise{int_div,no_inplace}.0: [False], MultiDirectionalTwoDLSTMOp...., len = 733
      no_recycling = <local> set([HostFromGpu.0]), len = 1
      impl = <local> None
  File "/home/kartik/.local/lib/python2.7/site-packages/theano/gof/op.py", line 935, in make_thunk
    line: return self.make_c_thunk(node, storage_map, compute_map,
                                   no_recycling)
    locals:
      self = <local> <cuda_implementation.CuDNNConvHWBCOp.CuDNNConvHWBCOp object at 0x7f6ac30273d0>
      self.make_c_thunk = <local> <bound method CuDNNConvHWBCOp.make_c_thunk of <cuda_implementation.CuDNNConvHWBCOp.CuDNNConvHWBCOp object at 0x7f6ac30273d0>>
      node = <local> CuDNNConvHWBCOp{border_mode='valid'}(GpuContiguous.0, GpuContiguous.0, GpuContiguous.0)
      storage_map = <local> {b_conv3: [CudaNdarray([ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
                              0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
                              0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
                              0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0..., len = 733
      compute_map = <local> {ScalarFromTensor.0: [False], V1_mdlstm2: [True], b_conv3: [True], Subtensor{::, int64}.0: [False], W1_mdlstm3: [True], Subtensor{::, int64}.0: [False], W2_mdlstm3: [True], MultiDirectionalTwoDLSTMOp.0: [False], y_sizes: [True], Elemwise{int_div,no_inplace}.0: [False], MultiDirectionalTwoDLSTMOp...., len = 733
      no_recycling = <local> set([HostFromGpu.0]), len = 1
  File "/home/kartik/.local/lib/python2.7/site-packages/theano/gof/op.py", line 839, in make_c_thunk
    line: outputs = cl.make_thunk(input_storage=node_input_storage,
                                  output_storage=node_output_storage)
    locals:
      outputs = <not found>
      cl = <local> <theano.gof.cc.CLinker object at 0x7f6aac699810>
      cl.make_thunk = <local> <bound method CLinker.make_thunk of <theano.gof.cc.CLinker object at 0x7f6aac699810>>
      input_storage = <not found>
      node_input_storage = <local> [[None], [None], [None]]
      output_storage = <not found>
      node_output_storage = <local> [[None]]
  File "/home/kartik/.local/lib/python2.7/site-packages/theano/gof/cc.py", line 1190, in make_thunk
    line: cthunk, in_storage, out_storage, error_storage = self.__compile__(
              input_storage, output_storage, storage_map,
              keep_lock=keep_lock)
    locals:
      cthunk = <not found>
      in_storage = <not found>
      out_storage = <not found>
      error_storage = <not found>
      self = <local> <theano.gof.cc.CLinker object at 0x7f6aac699810>
      self.__compile__ = <local> <bound method CLinker.__compile__ of <theano.gof.cc.CLinker object at 0x7f6aac699810>>
      input_storage = <local> [[None], [None], [None]]
      output_storage = <local> [[None]]
      storage_map = <local> None
      keep_lock = <local> False
  File "/home/kartik/.local/lib/python2.7/site-packages/theano/gof/cc.py", line 1131, in __compile__
    line: thunk = self.cthunk_factory(error_storage,
                                      input_storage,
                                      output_storage,
                                      storage_map,
                                      keep_lock=keep_lock)
    locals:
      thunk = <not found>
      self = <local> <theano.gof.cc.CLinker object at 0x7f6aac699810>
      self.cthunk_factory = <local> <bound method CLinker.cthunk_factory of <theano.gof.cc.CLinker object at 0x7f6aac699810>>
      error_storage = <local> [None, None, None]
      input_storage = <local> ([None], [None], [None])
      output_storage = <local> ([None],)
      storage_map = <local> None
      keep_lock = <local> False
  File "/home/kartik/.local/lib/python2.7/site-packages/theano/gof/cc.py", line 1586, in cthunk_factory
    line: module = get_module_cache().module_from_key(
              key=key, lnk=self, keep_lock=keep_lock)
    locals:
      module = <not found>
      get_module_cache = <global> <function get_module_cache at 0x7f6b33b6b140>
      module_from_key = <not found>
      key = <local> (((3, 3), (3,), (3,), (3,), (3,)), ('CLinker.cmodule_key', ('-DCUDA_NDARRAY_CUH=c72d035fdf91890f3b36710688069b2e', '-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION', '-O3', '-Wno-unused-label', '-Wno-unused-variable', '-Wno-write-strings', '-arch=sm_61', '-fno-math-errno'), ('cublas', 'cuda_ndarray',...
      lnk = <not found>
      self = <local> <theano.gof.cc.CLinker object at 0x7f6aac699810>
      keep_lock = <local> False
  File "/home/kartik/.local/lib/python2.7/site-packages/theano/gof/cmodule.py", line 1122, in module_from_key
    line: src_code = lnk.get_src_code()
    locals:
      src_code = <not found>
      lnk = <local> <theano.gof.cc.CLinker object at 0x7f6aac699810>
      lnk.get_src_code = <local> <bound method CLinker.get_src_code of <theano.gof.cc.CLinker object at 0x7f6aac699810>>
  File "/home/kartik/.local/lib/python2.7/site-packages/theano/gof/cc.py", line 1462, in get_src_code
    line: mod = self.get_dynamic_module()
    locals:
      mod = <not found>
      self = <local> <theano.gof.cc.CLinker object at 0x7f6aac699810>
      self.get_dynamic_module = <local> <bound method CLinker.get_dynamic_module of <theano.gof.cc.CLinker object at 0x7f6aac699810>>
  File "/home/kartik/.local/lib/python2.7/site-packages/theano/gof/cc.py", line 1506, in get_dynamic_module
    line: self.code_gen()
    locals:
      self = <local> <theano.gof.cc.CLinker object at 0x7f6aac699810>
      self.code_gen = <local> <bound method CLinker.code_gen of <theano.gof.cc.CLinker object at 0x7f6aac699810>>
  File "/home/kartik/.local/lib/python2.7/site-packages/theano/gof/cc.py", line 826, in code_gen
    line: behavior = op.c_code(node, name, isyms, osyms, sub)
    locals:
      behavior = <not found>
      op = <local> <cuda_implementation.CuDNNConvHWBCOp.CuDNNConvHWBCOp object at 0x7f6ac30273d0>
      op.c_code = <local> <bound method CuDNNConvHWBCOp.c_code of <cuda_implementation.CuDNNConvHWBCOp.CuDNNConvHWBCOp object at 0x7f6ac30273d0>>
      node = <local> CuDNNConvHWBCOp{border_mode='valid'}(<CudaNdarrayType(float32, 4D)>, <CudaNdarrayType(float32, 4D)>, <CudaNdarrayType(float32, vector)>)
      name = <local> 'node_<<<<HASH_PLACEHOLDER>>>>_0', len = 31
      isyms = <local> ['V3', 'V5', 'V7']
      osyms = <local> ['V1']
      sub = <local> {'fail': '{\n        __failure = 9;\n        if (!PyErr_Occurred()) {\n            PyErr_SetString(PyExc_RuntimeError,\n                "Unexpected error in an Op\'s C code. "\n                "No Python exception was set.");\n            }\n        goto __label_9;}', 'id': 9, 'failure_var': '__f...
  File "/home/kartik/new_returnn/cuda_implementation/CuDNNConvHWBCOp.py", line 235, in c_code
    line: cudnn_version = theano.sandbox.cuda.dnn.version()[0]/1000
    locals:
      cudnn_version = <not found>
      theano = <global> <module 'theano' from '/home/kartik/.local/lib/python2.7/site-packages/theano/__init__.pyc'>
      theano.sandbox = <global> <module 'theano.sandbox' from '/home/kartik/.local/lib/python2.7/site-packages/theano/sandbox/__init__.pyc'>
      theano.sandbox.cuda = <global> <module 'theano.sandbox.cuda' from '/home/kartik/.local/lib/python2.7/site-packages/theano/sandbox/cuda/__init__.pyc'>
      theano.sandbox.cuda.dnn = <global> <module 'theano.sandbox.cuda.dnn' from '/home/kartik/.local/lib/python2.7/site-packages/theano/sandbox/cuda/dnn.pyc'>
      theano.sandbox.cuda.dnn.version = <global> <function dnn_version at 0x7f6b2387b0c8>
  File "/home/kartik/.local/lib/python2.7/site-packages/theano/sandbox/cuda/__init__.py", line 424, in dnn_version
    line: raise Exception(
              "We can't determine the cudnn version as it is not available",
              dnn_available.msg)
    locals:
      Exception = <builtin> <type 'exceptions.Exception'>
      dnn_available = <global> <function dnn_available at 0x7f6b27eb5e60>
      dnn_available.msg = <global> "Can not compile with cuDNN. We got this error:\nnvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).\n/tmp/try_flags_mfyHIk.c:5:19: fatal error: cudnn.h: No such file or d..., len = 327
Exception: ('The following error happened while compiling the node', CuDNNConvHWBCOp{border_mode='valid'}(GpuContiguous.0, GpuContiguous.0, GpuContiguous.0), '\n', "We can't determine the cudnn version as it is not available", "Can not compile with cuDNN. We got this error:\nnvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).\n/tmp/try_flags_mfyHIk.c:5:19: fatal error: cudnn.h: No such file or directory\ncompilation terminated.\n")
Device proc gpuX (gpuZ) died: ProcConnectionDied('recv_bytes EOFError: ',)
Theano flags: compiledir_format=compiledir_%(platform)s-%(processor)s-%(python_version)s-%(python_bitwidth)s--dev-gpuZ,device=gpu,force_device=True
EXCEPTION
Traceback (most recent call last):
  File "/home/kartik/new_returnn/Device.py", line 332, in startProc
    line: self._startProc(*args, **kwargs)
    locals:
      self = <local> <Device.Device object at 0x7f0dde7dc250>
      self._startProc = <local> <bound method Device._startProc of <Device.Device object at 0x7f0dde7dc250>>
      args = <local> ('gpuZ',)
      kwargs = <local> {}
  File "/home/kartik/new_returnn/Device.py", line 386, in _startProc
    line: interrupt_main()
    locals:
      interrupt_main = <global> <function interrupt_main at 0x7f0ddf429398>
  File "/home/kartik/new_returnn/Util.py", line 637, in interrupt_main
    line: sys.exit(1)  # And exit the thread.
    locals:
      sys = <global> <module 'sys' (built-in)>
      sys.exit = <global> <built-in function exit>
SystemExit: 1
KeyboardInterrupt
EXCEPTION
Traceback (most recent call last):
  File "../../../rnn.py", line 532, in main
    line: init(commandLineOptions=argv[1:])
    locals:
      init = <global> <function init at 0x7f0dde7d07d0>
      commandLineOptions = <not found>
      argv = <local> ['../../../rnn.py', 'config_fwd_kd'], _[0]: {len = 15}
  File "../../../rnn.py", line 345, in init
    line: devices = initDevices()
    locals:
      devices = <not found>
      initDevices = <global> <function initDevices at 0x7f0dde7d0410>
  File "../../../rnn.py", line 158, in initDevices
    line: time.sleep(0.25)
    locals:
      time = <global> <module 'time' (built-in)>
      time.sleep = <global> <built-in function sleep>
KeyboardInterrupt
Quitting

**Comment by pvoigtlaender** [comment]
it says

We can't determine the cudnn version as it is not available

Did you properly set up cudnn?
Please have a look at http://deeplearning.net/software/theano/library/sandbox/cuda/dnn.html

**Comment by dutta1kartik3** [comment]
Thank you very much for your help. It is functioning now.
