### ISSUE TITLE
Error when initializing layers

### ISSUE THREAD

**Issue by Ore-an** [rwth-i6/returnn#281]
I get an error when creating a NativeLstm2 layer (I've omitted the first part of the trace):
```
 File "/disk/scratch4/acarmant/software/returnn/TFNativeOp.py", line 872, in __call__
    line: out, _, _, final_cell_state = self.op(inputs, weights, y0, c0, index, start, step)
    locals:
      out = <not found>
      _ = <not found> 
      final_cell_state = <not found>
      self = <local> <TFNativeOp.NativeLstm2 object at 0x7f731014c850>
      self.op = <local> <function native_lstm2 at 0x7f7310141290>
      inputs = <local> <tf.Tensor 'lstm0_fw/rec/add:0' shape=(?, ?, 4096) dtype=float32>
      weights = <local> <tf.Variable 'lstm0_fw/rec/W_re:0' shape=(1024, 4096) dtype=float32_ref>
      y0 = <local> <tf.Tensor 'lstm0_fw/rec/initial_h:0' shape=(?, 1024) dtype=float32>
      c0 = <local> <tf.Tensor 'lstm0_fw/rec/initial_c:0' shape=(?, 1024) dtype=float32>
      index = <local> <tf.Tensor 'extern_data/placeholders/data/sequence_mask_time_major/cast_float32:0' shape=(?, ?) dtype=float32>
      start = <local> <tf.Tensor 'lstm0_fw/rec/start:0' shape=() dtype=int32>
      step = <local> <tf.Tensor 'lstm0_fw/rec/step:0' shape=() dtype=int32>
  File "<string>", line 90, in native_lstm2
ERROR: cannot get more detailed exception info because:
   Traceback (most recent call last):
     File "/disk/scratch4/acarmant/software/returnn/better_exchook.py", line 1099, in format_tb
       alt_fn = fallback_findfile(filename)
     File "/disk/scratch4/acarmant/software/returnn/better_exchook.py", line 360, in fallback_findfile
       mods = [m for m in sys.modules.values() if m and getattr(m, "__file__", None) and filename in m.__file__]
     File "/disk/scratch4/acarmant/software/returnn/better_exchook.py", line 360, in <listcomp>
       mods = [m for m in sys.modules.values() if m and getattr(m, "__file__", None) and filename in m.__file__]
   RuntimeError: dictionary changed size during iteration      

ValueError: wrong number of inputs. required 7 but got 1439969333 for 'lstm0_fw/rec/NativeLstm2' (op: 'NativeLstm2') with input shapes: [?,?,4096], [1024,4096], [?,1024], [?,1024], [?,?], [], [].
```

This is using a config file based on [your LibriSpeech example](https://github.com/rwth-i6/returnn-experiments/blob/master/2018-asr-attention/librispeech/full-setup-attention/returnn.config). The full configuration is here, but the changes shouldn't have any impact on the first layer:
[libri_bidec_conf.txt](https://github.com/rwth-i6/returnn/files/4350799/libri_bidec_conf.txt)

The error happens on the creation of the first lstm layer, "lstm0_fw", and the input to the layer doesn't seem broken:

`layer root/'source' output: Data(name='source_output', shape=(None, 40), batch_shape_meta=[B,T|'time:var:extern_data:data',F|40])`

I've tried recompiling the operation, but I still get the error. The (wrong) number of inputs changes, and it can be negative or positive (but seems it always has 10 digits). Could you point me in the right direction to debug this?

My ReturNN version is the most recent, I'm using Python3.7, TF 1.15, CUDA 10.0 and cuDNN 7.4.

**Comment by albertz** [comment]
The `RuntimeError: dictionary changed size during iteration` is just due to some problem in better_exchook. I pushed an update which should fix this problem. Maybe try again. You might get a bit more detailed stack trace, although not sure. At least this error should be gone.

About the error:
The relevant part is this:
`ValueError: wrong number of inputs. required 7 but got 1439969333 for 'lstm0_fw/rec/NativeLstm2' (op: 'NativeLstm2') with input shapes: [?,?,4096], [1024,4096], [?,1024], [?,1024], [?,?], [], [].`
I'm quite sure that you have a mismatch in the C++ ABI between your compiler (GCC version) and the compiler (GCC version) used to compile TF. (In some other cases, you would get an exception like `undefined context (mismatch in C++ ABI?)`.) Check `tf.__compiler_version__` for that, and check what GCC version you have installed. Make sure that the same major version of GCC is installed.

**Comment by Ore-an** [comment]
Thanks for the help, the compiler mismatch was the problem.

**Comment by albertz** [comment]
Good to know. Just for future reference, can you maybe say what `tf.__compiler_version__` reported for you, what GCC version you had installed before, and which you installed now? And what Linux distribution you are using?

**Comment by Ore-an** [comment]
The TensorFlow version I got from pip was compiled with GCC 7.3.1 20180303, while I had version 4.8.5 20150623 in my PATH. Our servers run a distro based on RHEL, specifically Scientific Linux 7.6. I just compiled the exact version used to compile the pip package and added it to my PATH.

**Comment by Ore-an** [comment]
Adding to this, I went back to TF 1.14, and that one uses GCC 4.8.5.

**Comment by albertz** [comment]
Ok, thanks for the information.
Why did you go back to TF 1.14? I thought this problem was resolved? Any other problems?

**Comment by Ore-an** [comment]
I had a problem with getting nonfinite scores on the output of CTC in pretraining and the model breaking within 4 or 5 sub-epochs, and it also happened with other architectures and layers, such as the linear embedding layer in a recurrent decoder. As it happened more than 10 times in a row and wasn't happening before, I couldn't chalk it up to non-deterministic behaviour, so I made some changes such as downgrading TF, trying a different GPU etc. To be honest, I have no idea what fixed it (or if it really is fixed or if it was just a clump of bad luck with initializations) and I'm not sure if it's reproducible at all, so I didn't open an issue. If I get some insight on the how or why I'll open one.

**Comment by patrick-wilken** [comment]
Hi, I recently also had divergent trainings when going from TF 1.11 to 1.15 (and simultaneously many other changes like different GPU, other versions of other libraries...). Maybe this is really an issue? I did not have time to invest this further, I will report if I find out more.

**Comment by albertz** [comment]
When switching hardware (e.g. using a different type of GPU), you can also have different results. And of course a few of the ops are non-deterministic anyway.
The same can naturally happen when switching the TF version.
Some of the hyper params can be sensible, and when they work well on one hardware, one TF version, they can be bad (or even break) on another. It usually helps to make the learning rate warmup longer, or start with lower learning rate, or increase pretrain repetitions, which will make it more robust in any case (but might yield somewhat less optimal results).
If you are not able to get it to run after doing that, or the divergent training is in general much more often, we should maybe study this in more detail, though.

**Comment by albertz** [comment]
Also related: #262
