### ISSUE TITLE
How to evaluate a trained model directly?

### ISSUE THREAD

**Issue by iamweiweishi** [rwth-i6/returnn#282]
**Main issue: How to calculate the WER metric based on this config and one specific ckpt?**

I have trained a ASR model using 'base2.conv2l.specaug.curric3.config' on LibriSpeech, and got ckpt models.

I tried to evaluate the WER of the model by running: 
CUDA_VISIBLE_DEVICES=0 python rnn.py --config returnn-experiments/2019-asr-e2e-trafo-vs-lstm/librispeech/base2.conv2l.specaug.curric3.config --task analyze --load net-model/network.100

But the following error occurs,

error > 

line: raise ValueError("copy_compatible_to: self %r already has more dims than target data %r" % (self, data))
    locals:
      ValueError = <builtin> <class 'ValueError'>
      self = <local> Data(name='target_embed_output', shape=(None, 621), batch_shape_meta=[B,T|'time:var:extern_data:classes',F|621])
      data = <local> Data(name='target_embed_output', shape=(621,), time_dim_axis=None, batch_shape_meta=[B,F|621])
ValueError: copy_compatible_to: self Data(name='target_embed_output', shape=(None, 621), batch_shape_meta=[B,T|'time:var:extern_data:classes',F|621]) already has more dims than target data Data(name='target_embed_output', shape=(621,), time_dim_axis=None, batch_shape_meta=[B,F|621])

Besides, I am not sure whether this is the right way to get WER.

Thank you.
Regards

**Comment by albertz** [comment]
Why do you use task `analyze`?
W.r.t. the error, you need to provide the full stack trace.

For a full example setup, please check [here](https://github.com/rwth-i6/returnn-experiments/tree/master/2018-asr-attention/librispeech/full-setup-attention).
[This script](https://github.com/rwth-i6/returnn-experiments/blob/master/2018-asr-attention/librispeech/full-setup-attention/tools/search.py) will do the recognition and in the end calls `returnn/tools/calculate-word-error-rate.py` to calculate the WER.

**Comment by iamweiweishi** [comment]
> Why do you use task `analyze`?
> W.r.t. the error, you need to provide the full stack trace.
> 
> For a full example setup, please check [here](https://github.com/rwth-i6/returnn-experiments/tree/master/2018-asr-attention/librispeech/full-setup-attention).
> [This script](https://github.com/rwth-i6/returnn-experiments/blob/master/2018-asr-attention/librispeech/full-setup-attention/tools/search.py) will do the recognition (via task `search`), then calls `returnn/tools/search-bpe-to-words.py` and then calls `returnn/tools/calculate-word-error-rate.py` to calculate the WER.

**Comment by iamweiweishi** [comment]
I followed the steps [here](https://github.com/rwth-i6/returnn-experiments/tree/master/2018-asr-attention/librispeech/full-setup-attention). The only difference is that I did not use the 'ogg' format. I used the unzip data directly.
All the params are kept the same and use [this config](https://github.com/rwth-i6/returnn-experiments/blob/master/2018-asr-attention/librispeech/full-setup-attention/returnn.config) But I get NAN of loss and cost just as [here](https://github.com/rwth-i6/returnn-experiments/issues/34).
Then I followed the reference in [issue](https://github.com/rwth-i6/returnn-experiments/issues/34), and used this [config](https://github.com/rwth-i6/returnn-experiments/blob/master/2019-asr-e2e-trafo-vs-lstm/librispeech/base2.conv2l.specaug.curric3.config), but the loss seems to be also abnormal after many epochs:

> train epoch 154, step 310, cost:ctc 6.547522317998528, cost:output/output_prob 3.838401624264691, error:ctc 0.9804081627517007, error:decision 0.0, error:output/output_prob 0.7428571424679831, loss 3180.689, max_size:classes 56, max_size:data 1580, mem_usage:GPU:0 8.0GB, num_seqs 6, 3.214 sec/step, elapsed 0:15:33, exp. remaining 0:10:18, complete 60.17%
train epoch 154, step 311, cost:ctc 6.648204478302944, cost:output/output_prob 3.858900365303441, error:ctc 0.980845971556846, error:decision 0.0, error:output/output_prob 0.7438148458022624, loss 3291.3506, max_size:classes 54, max_size:data 1652, mem_usage:GPU:0 8.0GB, num_seqs 6, 3.254 sec/step, elapsed 0:15:36, exp. remaining 0:10:16, complete 60.33%
train epoch 154, step 312, cost:ctc 6.353795215635073, cost:output/output_prob 3.779440018400123, error:ctc 0.9814814918790943, error:decision 0.0, error:output/output_prob 0.7560386553523131, loss 3146.3696, max_size:classes 54, max_size:data 1610, mem_usage:GPU:0 8.0GB, num_seqs 6, 3.397 sec/step, elapsed 0:15:40, exp. remaining 0:10:13, complete 60.50%
train epoch 154, step 313, cost:ctc 6.565730684769733, cost:output/output_prob 3.890935676386107, error:ctc 0.9816879127174616, error:decision 0.0, error:output/output_prob 0.7452229410409927, loss 3283.393, max_size:classes 60, max_size:data 1679, mem_usage:GPU:0 8.0GB, num_seqs 5, 3.436 sec/step, elapsed 0:15:43, exp. remaining 0:10:11, complete 60.67%
train epoch 154, step 314, cost:ctc 6.381381045217722, cost:output/output_prob 3.801346212997032, error:ctc 0.9822878037812188, error:decision 0.0, error:output/output_prob 0.7564575498690829, loss 3449.399, max_size:classes 63, max_size:data 1652, mem_usage:GPU:0 8.0GB, num_seqs 6, 3.552 sec/step, elapsed 0:15:47, exp. remaining 0:10:09, complete 60.84%
train epoch 154, step 315, cost:ctc 6.60334960370551, cost:output/output_prob 3.846664221870697, error:ctc 0.9825119390152396, error:decision 0.0, error:output/output_prob 0.7464229051256552, loss 3286.5293, max_size:classes 62, max_size:data 1700, mem_usage:GPU:0 8.0GB, num_seqs 5, 3.413 sec/step, elapsed 0:15:50, exp. remaining 0:10:07, complete 61.02%
train epoch 154, step 316, cost:ctc 6.604438721909106, cost:output/output_prob 3.7778755036484317, error:ctc 0.9843416450894439, error:decision 0.0, error:output/output_prob 0.750177942099981, loss 3646.788, max_size:classes 75, max_size:data 1695, mem_usage:GPU:0 8.0GB, num_seqs 5, 2.999 sec/step, elapsed 0:15:53, exp. remaining 0:10:05, complete 61.18%
train epoch 154, step 317, cost:ctc 6.639152670511066, cost:output/output_prob 3.883951475094136, error:ctc 0.9837963036261499, error:decision 0.0, error:output/output_prob 0.7492284006439149, loss 3409.4858, max_size:classes 67, max_size:data 1653, mem_usage:GPU:0 8.0GB, num_seqs 6, 3.010 sec/step, elapsed 0:15:56, exp. remaining 0:10:02, complete 61.35%
train epoch 154, step 318, cost:ctc 6.564242607667551, cost:output/output_prob 3.802791486819785, error:ctc 0.9820452606072648, error:decision 0.0, error:output/output_prob 0.7361436253995635, loss 3320.0425, max_size:classes 61, max_size:data 1665, mem_usage:GPU:0 8.0GB, num_seqs 6, 3.108 sec/step, elapsed 0:15:59, exp. remaining 0:10:00, complete 61.51%

I tried to do the recognition based on this [script](https://github.com/rwth-i6/returnn-experiments/blob/master/2018-asr-attention/librispeech/full-setup-attention/tools/search.py). 
WER was always larger than 110%.

I have no idea why this happens. Any suggestions on this?
Thank you.

**Comment by albertz** [comment]
> I used the unzip data directly.

I don't exactly understand what you mean by that. Which dataset did you use?

Also, what BPE or vocab settings?

> the loss seems to be also abnormal after many epochs

You started from scratch again (i.e. you deleted the models) after you changed the settings, right?

When you used [this config](https://github.com/rwth-i6/returnn-experiments/blob/master/2019-asr-e2e-trafo-vs-lstm/librispeech/base2.conv2l.specaug.curric3.config), did you also try to change the learning rate warmup (e.g. to 15 steps) and things like that (as explained [here](https://github.com/rwth-i6/returnn-experiments/issues/34#issuecomment-568171995))? Also check some of the comments [here](https://github.com/rwth-i6/returnn-experiments/issues/23).

> WER was always larger than 110%.

I assume that is because your model has not learned well. E.g. for `error:output/output_prob`, you should see a value <0.5 at least, otherwise the model will be bad.

To debug whether there might be other problems, you should also look at the output of your search. I.e. compare some seqs of `recog_words_file` vs `data/dataset/...trans.raw` (as in [this script](https://github.com/rwth-i6/returnn-experiments/blob/master/2018-asr-attention/librispeech/full-setup-attention/tools/search.py)).

**Comment by albertz** [comment]
I'm closing now. Please follow my suggestion, and report back if there are still problems.
