### ISSUE TITLE
Missing size_placeholder inside of rec-Layer

### ISSUE THREAD

**Issue by Zettelkasten** [rwth-i6/returnn#284]
I am trying to modify the Transformer architecture for MT to include the previous time step's encoder-decoder attention weights to calculate the current weights (a layer called `dec_01_att_weights`).
For this, I take the input `prev:dec_01_att_weights`, and pass it through a self-written layer that performs pooling over a variable sized time dimension (in this case, the source time dimension). However, this custom layer requires information about the source sequence lengths to perform masking, but the source's Data objects lack this info which results in the following exception when calling `get_sequence_mask()`:
```
  File "/u/petrick/att/returnn/TFUtil.py", line 2104, in is_time_axis_dynamic
    line: assert isinstance(self.shape[self.time_dim_axis_excluding_batch], int), (
    locals:
      isinstance = <builtin> <built-in function isinstance>
      self = <local> Data(name='prev:dec_01_att_weights_output', shape=(None, 1, 8), feature_dim_axis=2, beam=SearchBeam(name='output/prev:output', beam_size=12), batch_shape_meta=[B,T|?,F|1,8])
      self.shape = <local> (None, 1, 8)
      self.time_dim_axis_excluding_batch = <local> 0
      int = <builtin> <class 'int'>
AssertionError: Data(name='prev:dec_01_att_weights_output', shape=(None, 1, 8), feature_dim_axis=2, beam=SearchBeam(name='output/prev:output', beam_size=12), batch_shape_meta=[B,T|?,F|1,8]): dynamic time axis dim (None) (axis 1) but size_placeholder {} misses information
```

I noticed that in TFNetworkRecLayer.py in copy_as_prev_time_frame, you set
```
    if prev_output is not None:
      layer.output.placeholder = prev_output
      layer.output.placeholder.set_shape(tf.TensorShape(layer.output.batch_shape))
      layer.output.size_placeholder = {}  # must be set
```
(around line 3125) thus removing the size_placeholder.
I tried to comment out this last line, and that fixes my problem as the size_placeholder is now set. My config now works during training.

However, when using beam search with beam size 12, I run into a problem where the shape of the size_placeholder for the time dimension does not match with the batch dimension of the placeholder itself: For the first sequence, the size_placeholder of the time dim is 6, but the batch dim of my placeholder is 72=12*6.
I guess that somewhere, the batch dim is merged with the beam dimension, and that this does not happen here.

I am obviously doing something wrong and my fix that just comments out the line up there does not handle every case, and I am not familiar enough with the Returnn code to fix it myself. Maybe you can help, @albertz ? Thanks a lot!

**Comment by albertz** [comment]
First: You should always avoid to write your own layer. There is almost never a reason to do so. Please check out the documentation and our introduction video to development with Returnn ([here](https://returnn.readthedocs.io/)). E.g. pooling over variable sized dimension, that sounds very much like what the `ReduceLayer` is doing.

But anyway, about the problem: That might be some bug (setting `size_placeholder = {}`). It would be good if you could produce a very simple test case (as simple as possible) which demonstrates that (see other tests as examples).

In case of beam search, normally it would automatically handle such things (see e.g. `SelectSearchSourcesLayer`), if the dependencies are set correctly.

**Comment by Zettelkasten** [comment]
Thanks for the quick reply!
The ReduceLayer only supports pooling over the entire sequence, but not with a window (i.e. for every tensor entry, only take the k neighboring tokens and average over those). The PoolLayer can do this but does not handle variable sized dimensions.

I will try to come up with a simple test case reproducing my problem, thanks.

**Comment by albertz** [comment]
The `PoolLayer` would be almost what you want though, or not? The only problem you have with it is that it would use the padded values (0) at the borders? I'm not sure if that is really such a big problem. Apply batch-norm or layer-norm on the input, and it should be fine. This should be much faster than treating the window dimension as dynamic.

Otherwise, you could maybe also use the `WindowLayer`, and do it more explicitly.
Maybe we could also add an option for `WindowLayer` to make the resulting window axis also having dynamic length. Then you could simply use `WindowLayer` together with `ReduceLayer`.

**Comment by Zettelkasten** [comment]
Thanks Albert, you are probably right that padding doesn't make a big difference. We will try it without any masking for now, and perhaps switch to the other options you mentioned in the future.
This fixes my problem with the missing size_placeholder for now.

My issue with a tensor having the wrong size during search remains though, even without any custom Returnn code. I have created a PR containing a failing test case for this. I would be very grateful if you could have a look! Thanks a lot.
Also, please rename/move this issue if you find that it is not related to the original problem.

**Comment by Zettelkasten** [comment]
I did some additional tests with an actual network config for MT that had the issue with beam search I demonstrated in my test case, using `beam_size = 1` for now to be able to use it during search.
I trained the config once with `optimize_move_layers_out = True` and once with the flag set to `False`. When not moving layers out of the loop, it trained fine. However, with the optimization flag, it did not learn anything at all (stuck at ~0.1 % BLEU).

It seems like that `optimize_move_layers_out = True` changes the semantics of my network. That should never be the case, or am I missing something?

**Comment by albertz** [comment]
`optimize_move_layers_out = True` should not change the semantics. There are a number of test cases for this, e.g. `test_reclayer_optimize_out_linear` and co, which test that you get the same output (up to numerical differences). If you can verify that you will get different output, this is clearly a bug. But maybe that's not the case here.

The numerical differences can add up, and even play a bigger role at the gradient accumulation. Esp the gradient accumulation will use a different algorithm depending on whether it is inside the loop or outside, also depending on the specific layer. If it is inside, the gradient accumulation will be handled by `tf.while_loop`, and is mostly like the straight-forward implementation, going backwards over the sequence and using inplace-add. Outside the loop is in most cases better, as it does a more clever and stable reduce-sum reduction (depending on the layer), or a single batched matmul, etc. So actually I would expect it to be more stable when it is moved out (unless there is some bug). But in any case, the behavior might be slightly different, and it could be just bad luck, and/or your current hyper params work better for that case, or so.

Note that you can control a bit for individual layers, whether they are moved out of the loop or not, via `collocate_with`.

**Comment by Zettelkasten** [comment]
Thanks for all those useful tips. Turns out that it actually was a problem with my config: A SoftmaxOverSpatial layer was using another time axis during training than it was using during search, as its `time_dim_axis` changed depending on whether the layer was in a loop or not.
Perhaps future documentation about Data should be more explicit about that, especially about what the one `time_dim_axis` is when there are actually two time axes (like you often have in MT decoding for source and target time).

My issue with beam search remains, and as it turns out, two other students at i6 are currently stuck with the same issue (perhaps in different contexts, but with the same error message and with it working fine when `beam_size=1`). We're still investigating.

**Comment by albertz** [comment]
The `time_dim_axis` depends on the layers. Every layer could potentially reset this. So your question cannot be answered in general, and is very specific to your specific layers. (You can simply check the output and then you will likely see why it is that way.) But in general,  that is why I would always recommend to use unique tag names (via `stag:...`), to always avoid such problems.

About beam search, I'm not exactly sure what the issue is. But is there is an issue, let's keep organized here: Better open a separate issue.

This issue here is about `size_placeholder` (and nothing else).

**Comment by Zettelkasten** [comment]
Ok thank you. I will close this issue for now, as I was not able to reproduce it myself anymore and think that it might be more related to the implementation of my custom layer that I am no longer using.

We will open a separate issue for the beam search problem. Thanks!

**Comment by albertz** [comment]
The test in #285 is related to this issue with `size_placeholder` or to the other beam search problem? If it's outdated, please close as well. Otherwise also refer to in the new issue.

**Comment by Zettelkasten** [comment]
Sorry, the PR is related to beam search, and not to this issue.
