### ISSUE TITLE
Keyword Spotting in return

### ISSUE THREAD

**Issue by AhmedCheikhRouhou** [rwth-i6/returnn#29]
At First, i want to thank you for the RETURNN Framework.

My application is to use the trained model for Keyword Spotting in text images.

Does this framework support such application ? if not, is there anyway to implement it ?

Thank you in advance.

**Comment by pvoigtlaender** [comment]
Hi,

I don't think that we support that. As a very simple approach, you can run a recognition and then search in the recognized text for the keyword, but this will yield suboptimal results.

**Comment by albertz** [comment]
Closing this now, as this is not really a bug in Returnn. If you implement that, contributions are welcome!
