### ISSUE TITLE
Multi-gpu training with horovod

### ISSUE THREAD

**Issue by tvatsal1996** [rwth-i6/returnn#321]
I am trying to figure out how you have ensured equal number of steps on each worker in case of multi-gpu training with horovod for tf2. Can you please help me with this? Thank you :)

**Comment by albertz** [comment]
We do not necessarily have equal steps. That is why there is a check in every sep if all the instances have more data. But just see the code, I think it becomes very clear then.

**Comment by albertz** [comment]
Closing this, as this is not really an issue with RETURNN.
I think a better place to ask questions is on StackOverflow with `returnn` tag.

**Comment by tvatsal1996** [comment]
Ok. Thanks a lot :)
