### ISSUE TITLE
LearningRateControl incorrectly gets numpy type

### ISSUE THREAD

**Issue by JackTemaki** [rwth-i6/returnn#326]
I got this error when continuing a training from a checkpoint:

```
  File "/home/nick/github/returnn/returnn/learning_rate_control.py", line 543, in calc_learning_rate_for_epoch
    line: learning_rate = self.calc_learning_rate_decay_or_grow(
            learning_rate, decay=relative_error > self.relative_error_threshold)
    locals:
      learning_rate = <local> 0.001
      self = <local> NewbobRelative(relative_error_threshold=-0.01)
      self.calc_learning_rate_decay_or_grow = <local> <bound method LearningRateControl.calc_learning_rate_decay_or_grow of NewbobRelative(relative_error_threshold=-0.01)>
      decay = <not found>
      relative_error = <local> -0.7156845253057729
      self.relative_error_threshold = <local> -0.01
  File "/home/nick/github/returnn/returnn/learning_rate_control.py", line 184, in calc_learning_rate_decay_or_grow
    line: assert isinstance(decay, bool)
    locals:
      isinstance = <builtin> <built-in function isinstance>
      decay = <local> False
      bool = <builtin> <class 'bool'>
```

I checked the code, and it seems fine. For some reason the assert fails although decay is `False`, which I do not understand.

**Comment by albertz** [comment]
Very likely `decay` is in fact a `numpy.ndarray`. Make sure that it is really a `bool`.

**Comment by JackTemaki** [comment]
Calling `type` resulted in `<class 'numpy.bool_'>`, should I test for both?

**Comment by JackTemaki** [comment]
FYI:
In `calc_relative_error`:
```
    old_key, old_error = self.get_epoch_error_key_value(old_epoch)
    new_key, new_error = self.get_epoch_error_key_value(new_epoch)
    print(type(old_error))
    print(type(new_error))
```

The types are for some reason different:
```
<class 'float'>
<class 'numpy.float64'>
```

I am investigating further later on.

**Comment by albertz** [comment]
> Calling `type` resulted in `<class 'numpy.bool_'>`, should I test for both?
> 
> EDIT: I think it is best to just to a `bool` cast around the compare

No. As I said: Just check where this comes from, and fix the problem itself. Do not add workarounds. It should never be a numpy type.

**Comment by JackTemaki** [comment]
Well......:

```
>>> import numpy   
>>> var = numpy.float64(2)
>>> type(var)
<class 'numpy.float64'>
>>> isinstance(var, float)
True
>>> 
```

This is why we have numpy.float64 in the dictionary... The checks do not hold for that. Should I do a fixed cast in `set_epoch_error`?

**Comment by albertz** [comment]
I'm not sure what you are saying. Just fix it that there is no Numpy type. `decay` never should possibly be a Numpy type. Find out why it is a Numpy type, and change that such that it is not a Numpy type.

**Comment by JackTemaki** [comment]
Sorry for the unclear message. I am just saying that there probably always has been a numpy type before, and the existing `isinstance(value, float)` which was intended to check this never did the correct check. Also, there seems to be an important test-case missing, as some demos and one of my setups do not work any more.

Instead of casting, I can search for the exact value of course.

**Comment by albertz** [comment]
I don't see `isinstance(value, float)` in what you posted?
Sure, there might have been bugs before?
If there are missing important test cases, then please add them.

**Comment by JackTemaki** [comment]
The `numpy.float64` values are coming from the Tensorflow session call, and are never touched again. I could do a cast at an arbitrary location, the most consistent location might be in `Runner._finalize()`

**Comment by JackTemaki** [comment]
So what should it be? Casting all score and and error values from the `Runner` to float explictely, or just doing a bool cast for the `decay` value? We should do this as soon as possible, this seems to be breaking nearly all setups, and at least 4 demos.

**Comment by albertz** [comment]
Which TF session call? Where exactly? How does it get in here? What part of the documentation is wrong?

**Comment by albertz** [comment]
Also, what is the problem? The fix should be very straight-forward, or not?

**Comment by albertz** [comment]
As I see, LearningRateControl is completely independent from Numpy. It doesn't make sense if it would also accept Numpy types and then needs to check for every passed argument for that. That would just make the code more complicated. I guess this is clear, or not? I wonder why you consider this. Or maybe I understand you wrong.

**Comment by albertz** [comment]
In `Runner`, according to the documentation, all is already `float`. So I'm not sure what you mean. Unless you say that some of the documentation is wrong. Where exactly?
Just fix it in the most clean way. I don't think this will be arbitrary in any way, once you figured out where the actual problem comes from.
Also, definitely add test cases for the cases which fail currently.

**Comment by JackTemaki** [comment]
I pushed a simple test case which should do the job (I am not sure if 5 epochs are sufficient to trigger this error each time)

> I don't think this will be arbitrary in any way, once you figured out where the actual problem comes from.

This is definitely not clear to me. So in the following code part, `score` and `error` are set, which are supposed to be `float` according to the type documentation. I added an assert, and the values are `numpy.float64`, which cause `decay` to be set to `numpy.bool_` instead to `bool`. This is because two `numpy.float64` are compared.

```
  def _finalize(self, num_steps):
    """
    Called at the end of an epoch.

    :param int num_steps: number of steps we did for this epoch
    """
    results = {key: self._normalize_loss(value, key, self._inv_norm_accumulated)
               for (key, value) in self._results_accumulated.items()}
    self.results = results
    self.score = {key: value for (key, value) in results.items() if key.startswith("cost:")}

    # I added this for a debugging
    for value in self.score.values():
      assert not isinstance(value, numpy.float64)

    if self.engine.config.bool("calculate_exp_loss", False):
      self.score.update({key + ":exp": numpy.exp(value) for (key, value) in results.items() if key.startswith("cost:")})
    self.error = {key: value for (key, value) in results.items() if key.startswith("error:")}
    self.num_steps = num_steps
    self.finalized = True
```

So for me, the only valid position to do the casting would be when filling the `self.score` and `self.error` dicts.

**Comment by albertz** [comment]
> I added an assert, and the values are numpy.float64

But where does that come from?

> So for me, the only valid position to do the casting would be when filling the self.score and self.error dicts.

Why? You still have not really figured out where it really comes from.

**Comment by albertz** [comment]
> I pushed a simple test case which should do the job (I am not sure if 5 epochs are sufficient to trigger this error each time)

Never push a test case which is not yet fixed!

**Comment by JackTemaki** [comment]
> But where does that come from?

You really have to be more specific about this question, according to the docs, this is the first position where it is assumed to be a `float` and not a numpy datatype. Before it is always assumed to be in a numpy format, which is correct.

> Never push a test case which is not yet fixed!

Given the severity of this bug, I assumed the current master should not be labelled as "build passing". But ok, the next time I will not do this.

**Comment by albertz** [comment]
> > But where does that come from?
> 
> You really have to be more specific about this question, according to the docs, this is the first position where it is assumed to be a `float` and not a numpy datatype. Before it is always assumed to be in a numpy format, which is correct.

I thought that it is float before. I don't know, I'm not looking at the code currently. Maybe the documentation is also already wrong. Then fix that as well.
In any case, just do the most clean fix. This really should be trivial. I wonder what needs to be discussed about that.
I think `self.score` and `self.error` are always supposed so be `dict[str,float]`. It would be totally unnecessary to allow numpy types as well there. That would just makes things more complicated. This is obvious, or not?

> > Never push a test case which is not yet fixed!
> 
> Given the severity of this bug, I assumed the current master should not be labelled as "build passing". But ok, the next time I will not do this.

Everything works for me, and this behavior is already there since a while (before the restructuring). Nobody complained so far. If there is a missing test case for a common problem, that's bad, but the solution is never to just add the test case to master without also fixing the problem. We ensure in master that all tests are passing. This is always the case. But now you violate that. Now we have a broken master because of that, where not all tests are passing. We never should have that.

**Comment by JackTemaki** [comment]
Maybe to be more specific:

The `fetches_results` are obviously numpy values:
```
  def _collect_eval_info(self, fetches_results):
    """
    :param dict[str,numpy.ndarray|None] fetches_results: results of calculations, see self._get_fetches_dict()
    :return: dict for printing the step stats, see self._print_process(), e.g. {"cost:output": 2.3}
    :rtype: dict[str,float]
```

The scalar cost values are stored in as keys:
```
    keys = [k for k in fetches_results.keys() if k.startswith("cost:") or k.startswith("error:") or k == "loss"]
```

And the keys are used to extract the costs here (same function):
```
    # Accumulate for epoch stats.
    self._results_accumulated += NumbersDict({key: fetches_results[key] for key in keys})
```

`self._results_accumulated` has no documented data type, and also `self._normalize_loss` assumes any type.
So fixing it here will be the most consistent.

 > Everything works for me, and this behavior is already there since a while

The changes are only 2 weeks old, so it is unlikely that many people already started training runs with the updated master.

**Comment by JackTemaki** [comment]
I did the minimal changes necessary, the demo and test-case run now. All documentation strings should be correct now.

**Comment by albertz** [comment]
_collect_eval_info

returns float per doc. That also makes most sense. This is what you fixed
now?


Nick Rossenbach <notifications@github.com> schrieb am Fr., 7. Aug. 2020,
18:16:

**Comment by albertz** [comment]
Also, it is still unclear to me, where does the numpy type actually come
from?


Albert Zeyer <albzey@googlemail.com> schrieb am Fr., 7. Aug. 2020, 20:48:

**Comment by JackTemaki** [comment]
> _collect_eval_info
>returns float per doc. That also makes most sense. This is what you fixed
>now?

The `fetches_results` at the beginning of the function (making a copy of it) might be an alternative solution, that is true. But I wanted to change as few variables as possible.

> Also, it is still unclear to me, where does the numpy type actually come
> from?

I still do not understand this question... Tensorflow session runs [`sess.run`](https://github.com/rwth-i6/returnn/blob/2764c545eb477a9d02c9bebc5778edac12ebc816/returnn/tf/engine.py#L665 ) values are always numpy types, mostly `numpy.float32`. But because the `inv_loss_norm_factors` in `_collect_eval_info` are computed by using `numpy.float32` and Python `float`, the result is casted to `numpy.float64`. Is this what you mean?

**Comment by albertz** [comment]
`_collect_eval_info` returns float. That is what the documentation says. So this is wrong or not?
But this is also what make sense, or not? Even if the documentation is wrong, then it should be fixed that this is the case. There is no need for a Numpy type there. And if this is fixed, or if this is already true, then I don't see how it can become a Numpy type later on.

I'm not speaking about all of `fetches_results`. That doesn't make sense. That surely can contain other stuff. It doesn't make sense to cast all of it to float scalars. I'm just speaking about the score/error. That's what `_collect_eval_info` returns, or not? I don't see why that should be a Numpy type.

You should try to make the code simple and straightforward. It should make sense. Numpy types (ndarray but even scalars) should be used when they make sense, but otherwise not (esp because they can make things more complicated, as you see here).

I was not sure that the Numpy type comes from session.run. That is why I asked. I could have imagined it comes from somewhere else.
