### ISSUE TITLE
Cannot use WrapEpochValue outside of pretraining epochs

### ISSUE THREAD

**Issue by curufinwe** [rwth-i6/returnn#337]
Before the restructuring I could use WrapEpochValue in the network dictionary even after pretraining was finished, now these are not replaced after the last pretraining epoch. I.e. I get an error like
`TypeError: Failed to convert object of type <class 'returnn.pretrain.WrapEpochValue'> to Tensor. Contents: <returnn.pretrain.WrapEpochValue object at 0x14fbb5dffca0>. Consider casting elements to a supported type.`
In the first epoch after pretraining. Is this expected behaviour now?

**Comment by albertz** [comment]
Can you post the full error (including stack trace) + config?

**Comment by albertz** [comment]
I pushed sth, which probably fixes this. Can you try? (And reopen if you still have the problem.)

**Comment by curufinwe** [comment]
Your commit fixed it. Thank you.
