### ISSUE TITLE
Index out of range error

### ISSUE THREAD

**Issue by sharmaannapurna** [rwth-i6/returnn#34]
Hi, I tried running the training on a different dataset as suggested by you.
I am getting "index out of range" error after every batch...Please help me to figure out what has gone wrong? Following is the log:

`
index out of range4: 182 / 183, 0 / 1, 81 / 80 
index out of range4: 182 / 183, 0 / 1, 81 / 80 
index out of range4: 182 / 183, 0 / 1, 81 / 80 
index out of range4: 182 / 183, 0 / 1, 81 / 80 
index out of range4: 182 / 183, 0 / 1, 81 / 80 
index out of range4: 182 / 183, 0 / 1, 81 / 80 
index out of range4: 182 / 183, 0 / 1, 81 / 80 
index out of range4: 182 / 183, 0 / 1, 81 / 80 
index out of range4: 182 / 183, 0 / 1, 81 / 80 
index out of range4: 182 / 183, 0 / 1, 81 / 80 
index out of range4: 182 / 183, 0 / 1, 81 / 80 
index out of range4: 182 / 183, 0 / 1, 81 / 80 
index out of range4: 182 / 183, 0 / 1, 81 / 80 
index out of range4: 182 / 183, 0 / 1, 81 / 80 
index out of range4: 182 / 183, 0 / 1, 81 / 80 
index out of range4: 182 / 183, 0 / 1, 81 / 80 
index out of range4: 182 / 183, 0 / 1, 81 / 80 
index out of range4: 182 / 183, 0 / 1, 81 / 80 
index out of range4: 182 / 183, 0 / 1, 81 / 80 
index out of range4: 182 / 183, 0 / 1, 81 / 80 
index out of range4: 182 / 183, 0 / 1, 81 / 80 
index out of range4: 182 / 183, 0 / 1, 81 / 80 
index out of range4: 182 / 183, 0 / 1, 81 / 80 
index out of range4: 182 / 183, 0 / 1, 81 / 80 
index out of range4: 182 / 183, 0 / 1, 81 / 80 
index out of range4: 182 / 183, 0 / 1, 81 / 80 
index out of range4: 182 / 183, 0 / 1, 81 / 80 
index out of range4: 182 / 183, 0 / 1, 81 / 80 
index out of range4: 182 / 183, 0 / 1, 81 / 80 
index out of range4: 182 / 183, 0 / 1, 81 / 80 
index out of range4: 182 / 183, 0 / 1, 81 / 80 
index out of range4: 182 / 183, 0 / 1, 81 / 80 
index out of range4: 182 / 183, 0 / 1, 81 / 80 
index out of range4: 182 / 183, 0 / 1, 81 / 80 
index out of range4: 182 / 183, 0 / 1, 81 / 80 
train epoch 1, batch 12, cost:output 4.52913375128, elapsed 0:00:44, exp. remaining 0:20:27, complete 3.50%
0:20:27 [||||||                                                                                        3.50%                                                                                               ]running 1 sequence slices (382273 nts) of batch 13 on device gpu0
index out of range4: 183 / 184, 0 / 1, 81 / 80 

`

**Comment by pvoigtlaender** [comment]
Hi,

this is most probably a problem with the number of labels. Does your dataset use a different number of labels/characters? Please check if this is correct in the config.

**Comment by sharmaannapurna** [comment]
Thanks..That worked. Also I want to ask if we can train only a few layers from the original model(transfer learning)?

**Comment by pvoigtlaender** [comment]
There is a parameter which you can add in the layer definition in json, I think you have to set "trainable": false for the layers which should not be updated.
Please have a try, and maybe check the code for some details. 
If it doesn't work, feel free to post again here.

**Comment by sharmaannapurna** [comment]
Hi, Thank you for the reply. I dont understand following parameters that are used in config_real:

- "max_seqs": 10,
- "nadam": 1,
- "reinit": 0,
- "log_verbosity": 5,

Further,  If training is interrupted at some step, how can i continue from the previous saved model? can i do it with task = forward or else?

**Comment by pvoigtlaender** [comment]
Hi,

max_seqs is an upper bound on the number of sequences (i.e. images in your case), which are processed together in one mini-batch
nadam: 1 means, that Adam with Nesterov momentum is used as the optimizer
reinit: 0  there I'm not sure what exactly it does, better just leave it like this
log_verbosity: 5  controls how many messages are printed to the log. 5 is the highest verbosity, so everything will be printed. You can reduce it if you want less output

I think the default behaviour should be to continue the training if a previous model is available

**Comment by sharmaannapurna** [comment]
Thank you very much for the prompt reply.
