### ISSUE TITLE
Transfer learning in transformer ASR model

### ISSUE THREAD

**Issue by HardikSailor** [rwth-i6/returnn#361]
Hi all, I need to use a pre-trained encoder and decoder part without the output layer for transfer learning to other language ASR tasks. I will use other ASR task BPE codes and all for the output layer. How to do that precisely since the transformer has many layers and layer-wise initialization is too much complicated. I have followed librispeech-based transformer ASR training config. I tried with pre_load_from_files={} where I specified prefix="lstm0_", "lstm1_" and "encoder". But while training it is not loading those pretrained layers. Kindly help me regarding this.

**Comment by papar22** [comment]
As far as I understood, you have a transformer model trained on task1 and you want to transfer all parameters as an initialization step to train another model on task2 without the output layer as your vocabulary might be different. If this is what you want, there is no need for layer-wise pretraining as you start from a converged model. The easiest way to do that is to use preload_from_files and specify the prefix to nothing,i.e. prefix="". It means you load all parameters for the new model. To avoid loading the output layer, rename the layer and it should work fine.
Something like that:
preload_from_files = {
    "transformer" : {"filename": "PATH_TO_NETWORK", "prefix": "", "init_for_train": True, "ignore_missing": True},
}
Does it answer your question?

**Comment by HardikSailor** [comment]
Yes, I have tried and it worked well. Many thanks.
