### ISSUE TITLE
Device gpuX proc exception: ('The following error happened while compiling the node'

### ISSUE THREAD

**Issue by rogerzico** [rwth-i6/returnn#37]
Tesla K80,   theano 0.9

"THEANO_FLAGS='floatX=float32' python ../../../rnn.py config_demo"

It seems to me:

Device.py: 347 
    self._startProc(*args, **kwargs)    /// try to compile with a task using nvcc

Device.py: 355
    def _startProc(self, device_tag):

Device.py: 385 -391
    self.proc = AsyncTask(...
   ...
    self.input_queue = self.output_queue = self.proc.conn
/// created connection with the task

Device.py : 393 -
    try:
         // then try to read results, but got an exception
      self.id = self.output_queue.recv(); """ :type: int """
      self.device_name = self.output_queue.recv(); """ :type: str """
      self.num_train_params = self.output_queue.recv(); """ :type: int """  # = len(trainnet.gparams)
      self.sync_used_targets()
    except ProcConnectionDied as e:

Somehow, the "nvcc" proc died, therefore cannot be "read".

----

Device gpuX proc starting up, pid 7360
Device gpuX proc: THEANO_FLAGS = 'compiledir_format=compiledir_%(platform)s-%(processor)s-%(python_version)s-%(python_bitwidth)s--dev-gpuZ,device=gpu,floatX=float32,force_device=True'
Device train-network: Used data keys: ['classes', 'data', 'sizes']
using adam with nag and momentum schedule
Device gpuX proc exception: ('The following error happened while compiling the node', GpuDnnSoftmax{tensor_format='bc01', mode='channel', algo='accurate'}(GpuContiguous.0), '\n', 'nvcc return status', 1, 'for cmd', 'nvcc -shared -O3 -Xlinker -rpath,/usr/local/cuda/lib64 -arch=sm_37 -m64 -Xcompiler -fno-math-errno,-Wno-unused-label,-Wno-unused-variable,-Wno-write-strings,-DCUDA_NDARRAY_CUH=mc72d035fdf91890f3b36710688069b2e,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,-fPIC,-fvisibility=hidden -Xlinker -rpath,/home/ubuntu/.theano/compiledir_Linux-4.4.0-1052-aws-x86_64-with-debian-stretch-sid-x86_64-3.6.3-64--dev-gpuZ/cuda_ndarray -I/home/ubuntu/.theano/compiledir_Linux-4.4.0-1052-aws-x86_64-with-debian-stretch-sid-x86_64-3.6.3-64--dev-gpuZ/cuda_ndarray -I/usr/local/cuda/include -I/home/ubuntu/anaconda3/lib/python3.6/site-packages/theano/sandbox/cuda -I/home/ubuntu/anaconda3/lib/python3.6/site-packages/numpy/core/include -I/home/ubuntu/anaconda3/include/python3.6m -I/home/ubuntu/anaconda3/lib/python3.6/site-packages/theano/gof -L/home/ubuntu/.theano/compiledir_Linux-4.4.0-1052-aws-x86_64-with-debian-stretch-sid-x86_64-3.6.3-64--dev-gpuZ/cuda_ndarray -L/home/ubuntu/anaconda3/lib -o /home/ubuntu/.theano/compiledir_Linux-4.4.0-1052-aws-x86_64-with-debian-stretch-sid-x86_64-3.6.3-64--dev-gpuZ/tmp52h_i3it/m3084ad5093769045f45143c157756096.so mod.cu -lcudart -lcublas -lcuda_ndarray -lcudnn -lpython3.6m', "[GpuDnnSoftmax{tensor_format='bc01', mode='channel', algo='accurate'}(<CudaNdarrayType(float32, (False, False, True, True))>)]")
Device proc gpuX (gpuZ) died: ProcConnectionDied('recv_bytes EOFError: ',)
Theano flags: compiledir_format=compiledir_%(platform)s-%(processor)s-%(python_version)s-%(python_bitwidth)s--dev-gpuZ,device=gpu,floatX=float32,force_device=True

---

**Comment by pvoigtlaender** [comment]
Hi,

the part with the connection between the processes is not important.
What is really happening is nvcc failed to compile some code ('nvcc return status', 1, 'for cmd', 'nvcc -shared -O3 -Xlinker -rpath,/usr/local/cuda/lib64 -arch=sm_37 -m6 ...)
I don't see the actual error message from the compiler. Is there any more output which you didn't post?

**Comment by rogerzico** [comment]
I redirected the error results to a file;
too long to post here; 
attached here
[err.txt](https://github.com/rwth-i6/returnn/files/1751055/err.txt)

**Comment by pvoigtlaender** [comment]
I think this is the problem:
cudnnSetFilterNdDescriptor_v4
Most probably because of the cudnn version. A quick fix would be to downgrade cudnn. 
What might also work (not sure) is to replace each call to cudnnSetFilterNdDescriptor_v4 with cudnnSetFilterNdDescriptor
Will have to look in the docs of the new cudnn versions

**Comment by albertz** [comment]
Maybe als a cuDNN header mixup. Or just too new cuDNN version. It says this initially:
```
Using gpu device 0: Tesla K80 (CNMeM is disabled, cuDNN 7005)
/home/ubuntu/anaconda3/lib/python3.6/site-packages/theano/sandbox/cuda/__init__.py:631: UserWarning: Your cuDNN version is more recent than the one Theano officially supports. If you see any problems, try updating Theano or downgrading cuDNN to version 5.1.
```
Can you try cuDNN 5.1?

**Comment by rogerzico** [comment]
cudnnSetFilterNdDescriptor_v4
cudnnSetFilterNdDescriptor

Neither function is referenced by this package;

Could it be helper code from theano sandbox?

**Comment by albertz** [comment]
They are part of cuDNN.

**Comment by pvoigtlaender** [comment]
Some files in
https://github.com/rwth-i6/returnn/tree/master/cuda_implementation
use these functions.
In recent cudnn versions, cudnnSetFilterNdDescriptor_v4 was removed and instead cudnnSetFilterNdDescriptor should be used.
I think the file which is really the problem here is
https://github.com/rwth-i6/returnn/blob/master/cuda_implementation/CuDNNConvHWBCOp.py
We have some code for handling different cudnn versions, but it seems not to handle everything correct yet. Feel free to contribute here, or wait a bit until we get to this, or downgrade to an older cudnn version.

**Comment by pvoigtlaender** [comment]
I just noticed that cudnnSetFilterNdDescriptor_v4 doesn't actually occur in our own code in returnn.
So probably it's just a mismatch between theano and cudnn version, maybe 0.9 cannot run with the new cudnn version.

**Comment by rogerzico** [comment]
@pvoigtlaender 
@albertz 

Yes, I think it is yet another version mismatch problem.
You can close this one if you like;
Thanks for looking into it.
