### ISSUE TITLE
Grouped convolutions

### ISSUE THREAD

**Issue by vieting** [rwth-i6/returnn#382]
I'd like to use grouped convolutions in RETURNN, analog to the `groups` option of `Group1d` in PyTorch (https://pytorch.org/docs/stable/generated/torch.nn.Conv1d.html).

In principle, `tf.nn.convolution` does a grouped convolution when using a filter with shape `spatial_filter_shape + [in_channels // groups, out_channels]` instead of `spatial_filter_shape + [in_channels, out_channels]`. So we could just add a `groups` option and adapt the filter shape accordingly, however, the grouped convolution is not yet available on CPU in tensorflow.

Would be interested to hear your thoughts about this.

**Comment by JackTemaki** [comment]
I wrote custom code doing grouped convolution for some TTS feedback, based on `tf.nn.depthwise_conv2d`, but I never fully checked if this is the correct approach. Are you sure the default `tf.nn.convolution` does support that? Someone asked the same question in the tutorial Q&A, so it seems it might be a good idea to add such a layer, or extending the existing conv layer.

**Comment by vieting** [comment]
Yes, it does support that but only for GPU apparently. I compared `torch.nn.functional.conv1d` with `groups=16` and `tf.nn.convolution` (tf version 1.15) in a small script and they seem to do the same thing. But when running it on CPU, you get 
>UnimplementedError: The Conv2D op currently does not support grouped convolutions on the CPU. [...]

Your custom code is not yet available in the master branch I suppose?

**Comment by JackTemaki** [comment]
It was not a layer, but just code in a config, so no. Actually, are grouped convolutions and depthwise convolutions the same? I think there is some difference. For groups it is just that there is no connection across groups, right? For depthwise convolution there are actually different filters for different channels.

**Comment by vieting** [comment]
From the PyTorch documentation it seems that depthwise convolution is a special case of grouped convolution:
>When `groups == in_channels` and `out_channels == K * in_channels`, where `K` is a positive integer, this operation is also termed in literature as depthwise convolution.
https://pytorch.org/docs/stable/generated/torch.nn.Conv1d.html

**Comment by JackTemaki** [comment]
Ah, so in any case each group gets its own filters, ok

**Comment by albertz** [comment]
Do `tf.nn.depthwise_conv2d` and `tf.nn.convolution` internally resolve to different kernels? I thought `tf.nn.convolution` is the most generic API, which internally will select the right kernel.

Anyway, in RETURNN, whatever we add, it should work on both CPU+GPU. If `tf.nn.convolution` does not work with groups on CPU, then you would need some special code for this to handle:
```
if on_cpu: ....
else: ...
```

Also, RETURNN should ideally use the most efficient kernel for each case. E.g. if for depthwise convolution, it would be more efficient to directly call `tf.nn.depthwise_conv2d` (and TF does not do that automatically in `tf.nn.convolution`), then we should use `tf.nn.depthwise_conv2d` for this case. Of course that needs some research (and maybe small benchmarking), which is actually faster. If you are not sure, always prefer simpler code.

**Comment by albertz** [comment]
Just to add:

We discussed already (somewhere, elsewhere) that if we find other famous frameworks being a good example, we could copy it (the API) similarly to that. In this case, as they just have it as an option for e.g. `Conv1d`, it might make sense to just add a new option to our `ConvLayer` as well (as opposed to adding a new separate layer).

**Comment by albertz** [comment]
I added some initial support in 6d73b4e7bbf838daf0f8b8fbf3fd038e68b8b9a0.
This will use `tf.nn.depthwise_conv2d` if this is depthwise conv.
Otherwise just `tf.nn.convolution`.

This is incomplete in multiple ways, e.g. in the generic case (not depthwise), it would not work on CPU. But we can extend it later if that is needed at some point (or maybe TF itself just adds support for it, so we do not have to care). We should not overengineer this unless really needed (or very suboptimal in performance for some reason).
