### ISSUE TITLE
Where do you implement the "Beam search" function?  Gpu or Cpu?

### ISSUE THREAD

**Issue by yanghongjiazheng** [rwth-i6/returnn#393]
Dear authors, thanks for your great works. I learned a lot.  And the beam search of Returnn is quite efficient,  I wonder to know where do you implement it and which codes can I refer to.

**Comment by patrick-wilken** [comment]
Hi, this doc page is probably a good place to start: https://returnn.readthedocs.io/en/latest/internals/search.html?highlight=beam%20search

There you see a list of classes which as a whole implement the beam search logic. Note, that beam search is done entirely as part of the Tensorflow graph. I guess the Tensorflow ops involved are mostly, if not all, placed on CPU.

**Comment by albertz** [comment]
> I guess the Tensorflow ops involved are mostly, if not all, placed on CPU.

Of course this is wrong. They are all placed on GPU. That makes the beam search very efficient.

The core layer is `ChoiceLayer`, and the core function in it is `tf.nn.top_k`. The idea is that it gets in a probability distribution over the classes, which already has a beam (i.e. a number of hypotheses), and then it selects the top-k from those, i.e. selecting a new beam (pruning by k).

**Comment by patrick-wilken** [comment]
Yep, that was an uneducated guess 😅 I was thinking of ops like top_k and gather_nd, but just checked, almost everything runs on GPU.

**Comment by albertz** [comment]
@yanghongjiazheng Does this answers it for you? Is the documentation helpful? If yes, we can close this I guess. Otherwise, can you say what we maybe should improve in the documentation?

**Comment by yanghongjiazheng** [comment]
Yes, sure. The documentation helps a lot.  But I still have a question, "When and How does the beam search end?"  For example , when we get "beamsize" search results with <EOS>

**Comment by albertz** [comment]
> Yes, sure. The documentation helps a lot. But I still have a question, "When and How does the beam search end?" For example , when we get "beamsize" search results with `<s>`

This is configurable. You specify the ending condition. You specify a sub layer called `"end"` of type `bool` inside the recurrent loop (the `RecLayer`), and when this is True, it would end the corresponding hypothesis. When all hypotheses are ended, or a configurable optional dynamic maximum seq length is hit, it will end the beam search.

@JackTemaki Maybe you might want to extend the documentation.

**Comment by JackTemaki** [comment]
What exactly should I extend? The end token is explained here:
https://returnn.readthedocs.io/en/latest/user_guide/recurrent_subnet.html#recurrent-nets-with-independent-step-count

Maybe the relation to the beam search is not clear yet, I can add some links.

**Comment by albertz** [comment]
> What exactly should I extend?

Whatever you think was unclear from reading the discussion here. Or if you think everything was clear, just leave it as it is.

**Comment by JackTemaki** [comment]
Updated documentation with 607cf8db10c9be6635f13b73310724efca172c79
