### ISSUE TITLE
How to set a specific GPU device

### ISSUE THREAD

**Issue by aarora8** [rwth-i6/returnn#40]
https://github.com/rwth-i6/returnn/blob/5dbdf69189a75fe39adccaf3429d117ffcc6255b/demos/mdlstm/IAM/go.sh#L3

I'm on a cluster - on the node when I get scheduled I have to select a free gpu. I can find the free gpu, but I am not sure how to pass it in code for multidimensional lstm (IAM code).

inside go.sh should I do the following ?

./create_IAM_dataset.py
mkdir -p models log priors
CUDA_VISIBLE_DEVICES=$(free-gpu) /home/aaror/miniconda2/bin/python ../../../rnn.py config_demo

**Comment by pvoigtlaender** [comment]
I think this should work. Have a try.
