### ISSUE TITLE
Edit on GitHub links in documentation partly broken

### ISSUE THREAD

**Issue by albertz** [rwth-i6/returnn#401]
They are broken on the API pages. E.g. [here](https://returnn.readthedocs.io/en/latest/api/tf.distributed.html).

(They work correct on other doc pages, e.g. [here](https://returnn.readthedocs.io/en/latest/advanced/multi_gpu.html).)

**Comment by JackTemaki** [comment]
I am not sure what you mean here, I see a single typo in one link in the docstring for `tf.distributed`. Do you want me to check all API pages?

**Comment by albertz** [comment]
On every page in our doc, there is a "Edit on GitHub" link in the right top.
This link is broken on all API pages.
In this example, it links to: https://github.com/rwth-i6/returnn/blob/master/docs/api/tf.distributed.rst
But it should link to: https://github.com/rwth-i6/returnn/blob/master/returnn/tf/distributed.py
This is not a typo.

**Comment by JackTemaki** [comment]
Ah, I see the problem. But the link is not broken (the link is correct), it is just that the files do not exist as they are generated while building the documentation. There is no direct control where this link points to for specific files, only a global edit. The options we have is keeping the broken link, or removing the link completely (https://github.com/readthedocs/sphinx_rtd_theme/issues/314).

**Comment by albertz** [comment]
The link is broken == you click on it and get a 404 page.

> only a global edit

Can't you just make some if-branch, like `if api_page: return <this_url>; else return <other_url>`?

**Comment by JackTemaki** [comment]
The linkcode_resolve function has no influence on this (see the breadcrumbs file I linked). The only way to edit this is to either touch the sphinx_rtd_template (not a good idea) or to make use of the meta tag (I am trying this right now).

**Comment by JackTemaki** [comment]
It seems this is not yet supported, but will be supported in the upcoming Sphinx 4. So I would suggest we just disable the link globally.

**Comment by albertz** [comment]
Ok.


Nick Rossenbach <notifications@github.com> schrieb am Mi., 2. Dez. 2020,
12:32:

**Comment by JackTemaki** [comment]
As it was now possible, fixed with 295fc54
