### ISSUE TITLE
can't use dump-forward.py

### ISSUE THREAD

**Issue by spaceiling** [rwth-i6/returnn#413]
Hi, could anyone help? I’m trying to use `returnn/tools/dump-forward.py` and then giving a returnn config, but always get the error from `rnn.engine.run_single(dataset=dataset, seq_idx=seq_idx, output_dict=output_dict)` that `InvalidArgumentError: You must feed a value for placeholder tensor 'global_tensor_train_flag/train_flag' with dtype bool` in `returnn/tf/util/basic.py` but the engine was initialised from the config that was with a `task = "train"`

**Comment by albertz** [comment]
(Please properly format with Markdown in the future.)

**Comment by albertz** [comment]
It looks a bit like `dump-forward` is somewhat broken. But I will push a small fix, which should fix this.

**Comment by albertz** [comment]
Can you try again?
