### ISSUE TITLE
Multitasking using different targets

### ISSUE THREAD

**Issue by HardikSailor** [rwth-i6/returnn#427]
Hi team,
I need to use transformer model for multilingual ASR. I am also exploring how to use multiple targets such as language ID along with BPE codes. However, GeneratingDataset.py and TFNetwork.py supports only singe target either BPE or char.  Also, config needs to be specified classes with respective to the targets. How to add multiple losses with different targets (need not be same dimension as BPE) along with default CTC and attention loss with BPE targets.
Thank you.

**Comment by albertz** [comment]
Hi,

Thank you for the interest in RETURNN.

Note that I moved the issue to the RETURNN repo, where it belongs.

About the dataset, multiple options:

* You could use `MetaDataset` to combine multiple datasets and then have multiple targets available. Please refer to the documentation. Open a new issue specifically about `MetaDataset` if sth is unclear.

* You can use `MapDatasetBase` as an easy way to implement an own dataset. Please see the documentation. Open a new issue about `MapDatasetBase` if sth is unclear about that.

* You can implement an own dataset based on `CachedDataset2`.

* You could copy `OggZipDataset`, call it `MultiTargetOggZipDataset` or so, and extend it by that.

Use the `dump-dataset` tool to test your dataset, whether it is doing what you expect, i.e. provide the multiple targets as expected.

The network supports multiple targets already. You are maybe referring to the default target. But you can simply have multiple losses, and each loss can provide a different `target` option.

**Comment by HardikSailor** [comment]
Hi,
Thank you very much for the suggestions. I have tried to create new class in GeneratingDataset.py that accepts targets2 and classes 2 defined in config. However, TFNetwork.py is accepting para from config and it takes only default targets (target and classes). Do I need to change TFNetwork.py also to support this?
Thank you.

**Comment by albertz** [comment]
First of all, you don't need to modify RETURNN code at all. Also not to add the dataset. You can add the dataset in your own file (next to your config, not within RETURNN). And also no modification is needed for the network.

Also, you always use the latest version of RETURNN. Otherwise it is difficult to provide support, and it is somewhat wasted time to discuss issues which might be totally outdated. (I assume you have an old version because you mention old file names.)

As said, to use any target, you would for example use this in the network:
```
"output_target2": {..., "loss": "...", "target": "target2"}
```

**Comment by HardikSailor** [comment]
Thanks again for the suggestion. Yes, I am having an old repo. However, since my other experiments are done with this, I need to currently use this version. Let me add target2 the way you suggested.

**Comment by albertz** [comment]
I assume there is no actual bug, and also no feature request (as all this should already be supported), so I'm closing this now.
But feel free to ask further questions.
