### ISSUE TITLE
Profiling tensorflow network

### ISSUE THREAD

**Issue by 3DExtended** [rwth-i6/returnn#44]
Hey!

I am currently struggling with profiling a network: 
There is a possibility to profile a tensorflow network using TensorBoard via RunMetadata (see [here](https://www.tensorflow.org/programmers_guide/graph_viz#runtime_statistics)). 
I searched returnn for this feature but couldn't find it. 
Is there a similar way to profile individual components (e.g. layers) of a returnn tensorflow network?

Best, 
Peter

**Comment by albertz** [comment]
How did you search for it? When you search for `RunMetadata`, you will find it. I think just setting `store_metadata_mod_step` will probably work. Or maybe you have to extend the code.
As the name spaces will divide by layers, I think you should get all the information from that.

**Comment by 3DExtended** [comment]
I am sorry. I searched the documentation of returnn for "profiling", "profile" and "runmetadata" and since there were no results I posted this issue. The documentation should be updated... 

Setting `store_metadata_mod_step` worked for me. 
Thanks for the help.
