### ISSUE TITLE
In the readme the links to the documentation are broken

### ISSUE THREAD

**Issue by jvhoffbauer** [rwth-i6/returnn#445]
In the readme, the link to e.g. basic usage is broken. It is https://returnn.readthedocs.io/en/latest/basic_usage.html but should be https://returnn.readthedocs.io/en/latest/getting_started/basic_usage.html

I think, this also holds true for other links in the readme.

**Comment by albertz** [comment]
The link should still work, or not? At least for me, I get a redirect.

**Comment by albertz** [comment]
Thanks for the report. I fixed the redirect for now ([Admin console](https://readthedocs.org/dashboard/returnn/redirects/)). Might take a while until it is updated.
