### ISSUE TITLE
Error WHile running demo

### ISSUE THREAD

**Issue by prolaser** [rwth-i6/returnn#47]
Hey guys. I am trying to run the demo on the server which i have ssh access to. while running i encountered some error regarding to theano's flag (optimizer).Now i have chnaged the optimizer in .theanorc several times to (fast_compile and None) but none of that works.here i have copied the error i got maybe you guys can help me with it : 
at64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
('converting IAM_lines to', 'features/raw/demo.h5')
features/raw/demo.h5
(0, '/', 3)
[koeln:15698] mca: base: component_find: unable to open /usr/lib64/mpi/gcc/openmpi/lib64/openmpi/mca_btl_usnic: libpsm_infinipath.so.1: cannot open shared object file: No such file or directory (ignored)
[koeln:15698] mca: base: component_find: unable to open /usr/lib64/mpi/gcc/openmpi/lib64/openmpi/mca_mtl_ofi: libpsm_infinipath.so.1: cannot open shared object file: No such file or directory (ignored)
[koeln:15698] mca: base: component_find: unable to open /usr/lib64/mpi/gcc/openmpi/lib64/openmpi/mca_mtl_psm: libpsm_infinipath.so.1: cannot open shared object file: No such file or directory (ignored)
ERROR (theano.sandbox.cuda): ERROR: Not using GPU. Initialisation of device gpu failed:
initCnmem: cnmemInit call failed! Reason=CNMEM_STATUS_OUT_OF_MEMORY. numdev=1

Traceback (most recent call last):
  File "../../../rnn.py", line 27, in <module>
    from Device import Device, TheanoFlags, getDevicesInitArgs
  File "/home/sadeghi/returnn/Device.py", line 5, in <module>
    from Updater import Updater
  File "/home/sadeghi/returnn/Updater.py", line 4, in <module>
    import theano
  File "/usr/lib/python2.7/site-packages/theano/__init__.py", line 111, in <module>
    theano.sandbox.cuda.tests.test_driver.test_nvidia_driver1()
  File "/usr/lib/python2.7/site-packages/theano/sandbox/cuda/tests/test_driver.py", line 38, in test_nvidia_driver1
    if not numpy.allclose(f(), a.sum()):
  File "/usr/lib/python2.7/site-packages/theano/compile/function_module.py", line 871, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/usr/lib/python2.7/site-packages/theano/gof/link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/usr/lib/python2.7/site-packages/theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
RuntimeError: Cuda error: kernel_reduce_ccontig_node_97496c4d3cf9a06dc4082cc141f918d2_0: out of memory. (grid: 1 x 1; block: 256 x 1 x 1)

Apply node that caused the error: GpuCAReduce{add}{1}(<CudaNdarrayType(float32, vector)>)
Toposort index: 0
Inputs types: [CudaNdarrayType(float32, vector)]
Inputs shapes: [(10000,)]
Inputs strides: [(1,)]
Inputs values: ['not shown']
Outputs clients: [[HostFromGpu(GpuCAReduce{add}{1}.0)]]

Debugprint of the apply node: 
GpuCAReduce{add}{1} [id A] <CudaNdarrayType(float32, scalar)> ''   
 |<CudaNdarrayType(float32, vector)> [id B] <CudaNdarrayType(float32, vector)>

Storage map footprint:
 - <CudaNdarrayType(float32, vector)>, Shared Input, Shape: (10000,), ElemSize: 4 Byte(s), TotalSize: 40000 Byte(s)
 TotalSize: 40000 Byte(s) 0.000 GB
 TotalSize inputs: 40000 Byte(s) 0.000 GB

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
sadeghi@koeln:~/returnn/demos/mdlstm/IAM>

**Comment by prolaser** [comment]
By the way there is also another error while i free up the whole GPU memory, first i thought i dont have enough memory but i got 1080 8 gigs free memory:
snic: libpsm_infinipath.so.1: cannot open shared object file: No such file or directory (ignored)
[koeln:18084] mca: base: component_find: unable to open /usr/lib64/mpi/gcc/openmpi/lib64/openmpi/mca_mtl_ofi: libpsm_infinipath.so.1: cannot open shared object file: No such file or directory (ignored)
[koeln:18084] mca: base: component_find: unable to open /usr/lib64/mpi/gcc/openmpi/lib64/openmpi/mca_mtl_psm: libpsm_infinipath.so.1: cannot open shared object file: No such file or directory (ignored)
Using gpu device 0: GeForce GTX 1080 (CNMeM is enabled with initial size: 95.0% of memory, cuDNN 7003)
/usr/lib/python2.7/site-packages/theano/sandbox/cuda/__init__.py:600: UserWarning: Your cuDNN version is more recent than the one Theano officially supports. If you see any problems, try updating Theano or downgrading cuDNN to version 5.
  warnings.warn(warn)
Traceback (most recent call last):
  File "../../../rnn.py", line 27, in <module>
    from Device import Device, TheanoFlags, getDevicesInitArgs
  File "/home/sadeghi/returnn/Device.py", line 5, in <module>
    from Updater import Updater
  File "/home/sadeghi/returnn/Updater.py", line 4, in <module>
    import theano
  File "/usr/lib/python2.7/site-packages/theano/__init__.py", line 111, in <module>
    theano.sandbox.cuda.tests.test_driver.test_nvidia_driver1()
  File "/usr/lib/python2.7/site-packages/theano/sandbox/cuda/tests/test_driver.py", line 39, in test_nvidia_driver1
    raise Exception("The nvidia driver version installed with this OS "
Exception: The nvidia driver version installed with this OS does not give good results for reduction.Installing the nvidia driver available on the same download page as the cuda package will fix the problem: http://developer.nvidia.com/cuda-downloads
sadeghi@koeln:~/returnn/demos/mdlstm/IAM> clear

sadeghi@koeln:~/returnn/demos/mdlstm/IAM> CUDA_VISIBLE_DEVICES=1 ./go.sh
/usr/lib64/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
('converting IAM_lines to', 'features/raw/demo.h5')
features/raw/demo.h5
(0, '/', 3)
[koeln:18267] mca: base: component_find: unable to open /usr/lib64/mpi/gcc/openmpi/lib64/openmpi/mca_btl_usnic: libpsm_infinipath.so.1: cannot open shared object file: No such file or directory (ignored)
[koeln:18267] mca: base: component_find: unable to open /usr/lib64/mpi/gcc/openmpi/lib64/openmpi/mca_mtl_ofi: libpsm_infinipath.so.1: cannot open shared object file: No such file or directory (ignored)
[koeln:18267] mca: base: component_find: unable to open /usr/lib64/mpi/gcc/openmpi/lib64/openmpi/mca_mtl_psm: libpsm_infinipath.so.1: cannot open shared object file: No such file or directory (ignored)
Using gpu device 0: GeForce GTX 1080 (CNMeM is enabled with initial size: 95.0% of memory, cuDNN 7003)
/usr/lib/python2.7/site-packages/theano/sandbox/cuda/__init__.py:600: UserWarning: Your cuDNN version is more recent than the one Theano officially supports. If you see any problems, try updating Theano or downgrading cuDNN to version 5.
  warnings.warn(warn)
Traceback (most recent call last):
  File "../../../rnn.py", line 27, in <module>
    from Device import Device, TheanoFlags, getDevicesInitArgs
  File "/home/sadeghi/returnn/Device.py", line 5, in <module>
    from Updater import Updater
  File "/home/sadeghi/returnn/Updater.py", line 4, in <module>
    import theano
  File "/usr/lib/python2.7/site-packages/theano/__init__.py", line 111, in <module>
    theano.sandbox.cuda.tests.test_driver.test_nvidia_driver1()
  File "/usr/lib/python2.7/site-packages/theano/sandbox/cuda/tests/test_driver.py", line 39, in test_nvidia_driver1
    raise Exception("The nvidia driver version installed with this OS "
Exception: The nvidia driver version installed with this OS does not give good results for reduction.Installing the nvidia driver available on the same download page as the cuda package will fix the problem: http://developer.nvidia.com/cuda-downloads

**Comment by pvoigtlaender** [comment]
It looks like your nvidia driver is causing trouble. Can you install a different driver? Maybe this will also fix the first error.

**Comment by sharmaannapurna** [comment]
Hello,
I am getting this error log after running the config_demo: 

``Train data:
  input: 1 x 1
  output: {'classes': [79, 1], 'sizes': [2, 1], 'data': [1, 2]}
  HDF dataset, sequences: 3, frames: 764399
Devices:
  cpu0: cpu0 (units: 1 clock: 1.08Ghz memory: 2.0GB) working on 1 batch (update on device)
Learning-rate-control: no file specified, not saving history (no proper restart possible)
using adam with nag and momentum schedule
Network layer topology:
  input #: 1
  hidden 1Dto2D '1Dto2D' #: 1
  hidden source 'classes_source' #: 2
  hidden conv2 'conv0' #: 15
  hidden conv2 'conv1' #: 45
  hidden conv2 'conv2' #: 75
  hidden conv2 'conv3' #: 105
  hidden conv2 'conv4' #: 105
  hidden mdlstm 'mdlstm0' #: 30
  hidden mdlstm 'mdlstm1' #: 60
  hidden mdlstm 'mdlstm2' #: 90
  hidden mdlstm 'mdlstm3' #: 120
  hidden mdlstm 'mdlstm4' #: 120
  output softmax 'output' #: 82
net params #: 2627902
net trainable params: [W_conv0, b_conv0, W_conv1, b_conv1, W_conv2, b_conv2, W_conv3, b_conv3, W_conv4, b_conv4, U1_mdlstm0, U2_mdlstm0, U3_mdlstm0, U4_mdlstm0, V1_mdlstm0, V2_mdlstm0, V3_mdlstm0, V4_mdlstm0, W1_mdlstm0, W2_mdlstm0, W3_mdlstm0, W4_mdlstm0, b1_mdlstm0, b2_mdlstm0, b3_mdlstm0, b4_mdlstm0, U1_mdlstm1, U2_mdlstm1, U3_mdlstm1, U4_mdlstm1, V1_mdlstm1, V2_mdlstm1, V3_mdlstm1, V4_mdlstm1, W1_mdlstm1, W2_mdlstm1, W3_mdlstm1, W4_mdlstm1, b1_mdlstm1, b2_mdlstm1, b3_mdlstm1, b4_mdlstm1, U1_mdlstm2, U2_mdlstm2, U3_mdlstm2, U4_mdlstm2, V1_mdlstm2, V2_mdlstm2, V3_mdlstm2, V4_mdlstm2, W1_mdlstm2, W2_mdlstm2, W3_mdlstm2, W4_mdlstm2, b1_mdlstm2, b2_mdlstm2, b3_mdlstm2, b4_mdlstm2, U1_mdlstm3, U2_mdlstm3, U3_mdlstm3, U4_mdlstm3, V1_mdlstm3, V2_mdlstm3, V3_mdlstm3, V4_mdlstm3, W1_mdlstm3, W2_mdlstm3, W3_mdlstm3, W4_mdlstm3, b1_mdlstm3, b2_mdlstm3, b3_mdlstm3, b4_mdlstm3, U1_mdlstm4, U2_mdlstm4, U3_mdlstm4, U4_mdlstm4, V1_mdlstm4, V2_mdlstm4, V3_mdlstm4, V4_mdlstm4, W1_mdlstm4, W2_mdlstm4, W3_mdlstm4, W4_mdlstm4, b1_mdlstm4, b2_mdlstm4, b3_mdlstm4, b4_mdlstm4, W_in_mdlstm4_output, b_output]
start training at epoch 1 and batch 0
using batch size: 600000, max seqs: 10
learning rate control: ConstantLearningRate(defaultLearningRate=0.0005, minLearningRate=0.0, defaultLearningRates={1: 0.0005, 25: 0.0003, 35: 0.0001}, errorMeasureKey=None, relativeErrorAlsoRelativeToLearningRate=False, minNumEpochsPerNewLearningRate=0, filename=None), epoch data: 1: EpochData(learningRate=0.0005, error={}), 25: EpochData(learningRate=0.0003, error={}), 35: EpochData(learningRate=0.0001, error={}), error key: None
pretrain: None
start epoch 1 with learning rate 0.0005 ...
TaskThread train failed
Unhandled exception <class 'AssertionError'> in thread <TrainTaskThread(TaskThread train, started daemon 140403630638848)>, proc 7390.
EXCEPTION
Traceback (most recent call last):
  File "/home/mpl2/Projects/returnn/EngineTask.py", line 377, in run
    line: self.run_inner()
    locals:
      self = <local> <TrainTaskThread(TaskThread train, started daemon 140403630638848)>
      self.run_inner = <local> <bound method TaskThread.run_inner of <TrainTaskThread(TaskThread train, started daemon 140403630638848)>>
  File "/home/mpl2/Projects/returnn/EngineTask.py", line 402, in run_inner
    line: device.prepare(epoch=self.epoch, **self.get_device_prepare_args())
    locals:
      device = <local> <Device.Device object at 0x7fb27eeae898>
      device.prepare = <local> <bound method Device.prepare of <Device.Device object at 0x7fb27eeae898>>
      epoch = <not found>
      self = <local> <TrainTaskThread(TaskThread train, started daemon 140403630638848)>
      self.epoch = <local> 1
      self.get_device_prepare_args = <local> <bound method TrainTaskThread.get_device_prepare_args of <TrainTaskThread(TaskThread train, started daemon 140403630638848)>>
  File "/home/mpl2/Projects/returnn/Device.py", line 1424, in prepare
    line: self.set_net_params(network)
    locals:
      self = <local> <Device.Device object at 0x7fb27eeae898>
      self.set_net_params = <local> <bound method Device.set_net_params of <Device.Device object at 0x7fb27eeae898>>
      network = <local> <Network.LayerNetwork object at 0x7fb24dd05208>
  File "/home/mpl2/Projects/returnn/Device.py", line 1237, in set_net_params
    line: self.trainnet.set_params_by_dict(network.get_params_dict())
    locals:
      self = <local> <Device.Device object at 0x7fb27eeae898>
      self.trainnet = <local> <Network.LayerNetwork object at 0x7fb27eeaeb70>
      self.trainnet.set_params_by_dict = <local> <bound method LayerNetwork.set_params_by_dict of <Network.LayerNetwork object at 0x7fb27eeaeb70>>
      network = <local> <Network.LayerNetwork object at 0x7fb24dd05208>
      network.get_params_dict = <local> <bound method LayerNetwork.get_params_dict of <Network.LayerNetwork object at 0x7fb24dd05208>>
  File "/home/mpl2/Projects/returnn/Network.py", line 680, in set_params_by_dict
    line: self.output[name].set_params_by_dict(params[name])
    locals:
      self = <local> <Network.LayerNetwork object at 0x7fb27eeaeb70>
      self.output = <local> {'output': <<class 'NetworkOutputLayer.SequenceOutputLayer'> class:softmax name:output>}
      name = <local> 'output', len = 6
      set_params_by_dict = <not found>
      params = <local> {'output': {'b_output': array([-4.406719, -4.406719, -4.406719, -4.406719, -4.406719, -4.406719,
                              -4.406719, -4.406719, -4.406719, -4.406719, -4.406719, -4.406719,
                              -4.406719, -4.406719, -4.406719, -4.406719, -4.406719, -4.406719,
                              -4.406719, -4.406719, -4.406719, -4.406719, -4...., len = 13
  File "/home/mpl2/Projects/returnn/NetworkBaseLayer.py", line 148, in set_params_by_dict
    line: (self, p, self_param_shape, v.shape)
    locals:
      self = <local> <<class 'NetworkOutputLayer.SequenceOutputLayer'> class:softmax name:output>
      p = <local> 'b_output', len = 8
      self_param_shape = <local> (80,)
      v = <local> array([-4.406719, -4.406719, -4.406719, -4.406719, -4.406719, -4.406719,
                         -4.406719, -4.406719, -4.406719, -4.406719, -4.406719, -4.406719,
                         -4.406719, -4.406719, -4.406719, -4.406719, -4.406719, -4.406719,
                         -4.406719, -4.406719, -4.406719, -4.406719, -4.406719, -4.406719,
                       ..., len = 82
      v.shape = <local> (82,)
AssertionError: In <<class 'NetworkOutputLayer.SequenceOutputLayer'> class:softmax name:output>, param b_output shape does not match. Expected (80,), got (82,).

KeyboardInterrupt
Quitting

```
I am not sure whats gone wrong. Can it be OS dependent? I recently changed to Ubuntu18.04.
