### ISSUE TITLE
Merging dimensions in recurrence with WindowLayer is inconsistent across search and training

### ISSUE THREAD

**Issue by jvhoffbauer** [rwth-i6/returnn#491]
When using a recurrent layer, that uses recursion on the output of a `Choicelayer` (with beam size 1), I observe different dimensions when performing training and search. This becomes problematic, when using the `MergeDimsLayer` to merge the output with dimensions given as below. I am merging the output of a `WindowLayer` with window size 3. Using except_time in the merge layer, does not handle the search case and except_batch introduces an error in the training phase (see [log.txt](https://github.com/rwth-i6/returnn/files/6385304/log.txt)). 

```
search: ["B&Beam{'output/prev:output'}(1)", 'T|3', 'F|128']
training: ['B', "T|'time:var:extern_data:classes'", '3', 'F|128']
```

The bug here is probably, that the window layer is not consistent in marking the window dimension.

**Comment by jvhoffbauer** [comment]
A quick (and dirty) workaround is to use `axes = 'except_batch' if not is_search else 'except_time'` in the merge layer.

**Comment by albertz** [comment]
You should not use `except_batch` or `except_time` when a `RecLayer` is involved in any way. There are usually always better ways to refer to the axes you want to merge.

In this case, why not just use `axes='static'`?

**Comment by albertz** [comment]
As I understand from Slack, this is resolved? So closing. (Next time, please respond here, and clarify, and close for yourself.)
