### ISSUE TITLE
Issues when running RETURNN with conda

### ISSUE THREAD

**Issue by JackTemaki** [rwth-i6/returnn#532]
RETURNN does not detect Cuda paths under conda installations, as the folder structure is different from native Cuda installations.

The typical error message is e.g.:
`AssertionError: No parent dir of '/opt/conda/lib/libcudart.so.11.0.221' is a valid CUDA path.`

This issue is mostly a reminder for me to fix this at some point in the future.

**Comment by albertz** [comment]
There is nothing to fix. This is just not supported because Conda has a broken (incomplete) CUDA installation.
