### ISSUE TITLE
RETURNN wont create priors

### ISSUE THREAD

**Issue by prolaser** [rwth-i6/returnn#54]
Hey all

After running config_real i stop the training on 72 epochs which the error is reduced to 0.0564. After that i have run the config_forward and all i got was a mdlstm_real_valid.h5 but my prior folder is still empty. Can some one please help me with this issue. and also how can i do the testing on my dataset to calculate accuracy.

Thanks you

**Comment by pvoigtlaender** [comment]
Hi,

I'm not sure why it's not writing out the priors, you can try to debug this part:
https://github.com/rwth-i6/returnn/blob/c9f488a079603d67d80742ec0406e64c4ed81366/Engine.py#L515

Towards testing try config_fwd and the decode script (see your other github issue as well).

**Comment by albertz** [comment]
I'm not sure if this is resolved or not. Closing this now. Please update if you want.
