### ISSUE TITLE
Expected behaviour of optimised(pulled out of loop) layers in `RecLayer`

### ISSUE THREAD

**Issue by jotix16** [rwth-i6/returnn#550]
What is the expected behavior when a certain layer is being pulled out of a subnetwork in a `RecLayer`?

Logically, I would expect all optimized(pulled out) layers to get an extra time axis which would be equivalent to accumulating the its outputs for each recurrent step.

**Comment by albertz** [comment]
> What is the expected behavior when a certain layer is being pulled out of a subnetwork in a `RecLayer`?

This question is quite vague.
But the answer is that the final result should numerically be the same.

> Logically, I would expect all optimized(pulled out) layers to get an extra time axis which would be equivalent to accumulating the its outputs for each recurrent step.

Usually but not necessarily. E.g. when the computation is in fact independent from the time step index (e.g. you calculate sth like `max(base:encoder)` or so, which is totally independent from the current time index), it should not have an extra time axis.

Is there some actual issue? Or just clarification? Make a PR if you want to improve documentation. Or show some actual case where you think there is some buggy behavior. I'm closing this issue now.
