### ISSUE TITLE
compile_tf_graph.py not working with rec_step_by_step

### ISSUE THREAD

**Issue by JackTemaki** [rwth-i6/returnn#566]
While trying to update some setups to the latest RETURNN version we (@mmz33)  found that the `compile_tf_graph.py` does currently not work at all when using the `--rec_step_by_step` parameter. This probably happened because there are no tests for the tools, and all people that used this functionality still had old versions of RETURNN.

Even after fixing the SubnetworkRecCell calls and (temporarily) disabling the current assert that fails, I was not able to compile at least one network that uses a recurrent subnetwork with the recurrent step flag set.

I started a branch where I added two simple test cases, a (working) simple compile call and a (crashing) recurrent step compile call: https://github.com/rwth-i6/returnn/tree/nick_fix_compile

**Comment by albertz** [comment]
Yeah, I almost expected that this would break at some point without tests...

If you would want to investigate a bit more, you could bisect search the
last commit where your test runs through without error.


Nick Rossenbach ***@***.***> schrieb am Mo., 26. Juli 2021,
20:22:
