### ISSUE TITLE
`DotLayer` behavior unintuitive with rec automatic optimization

### ISSUE THREAD

**Issue by albertz** [rwth-i6/returnn#569]
(*Just a suggestion for now.*)
(*Also see [wiki on rec automatic optimization, special layer behavior](https://github.com/rwth-i6/returnn/wiki/Rec-automatic-optimization,-special-behavior-of-layers).*)

When `DotLayer` operates on values inside a rec loop (`RecLayer`), the `RecLayer` automatic optimization could move it + its inputs out of the loop, which would introduce a time axis on one or both of the inputs. To have the behavior correct, this extra axis must be added to the corresponding `var` option. The current solution is to use `T?` to have this working for both cases.

This is against the principle that the user should not need to think about the automatic optimization, and unintuive.

Possible solutions:

- Instead of specifying `var1`/`var2` for `DotLayer`, the user could specify the common shared axes (`common` or `share` or so). Currently this is implied/inferred. But when this `common` would be specified, we could infer `var1`/`var2`.
  One reason I did not add `common` originally because I found it slightly annoying that `B` would need to be specified then all the time. Or maybe `B` could always be included?
  I'm not sure if there are other problems.

- Somehow add special logic for the automatic optimization for `DotLayer`, to extend `var` of corresponding input?

**Comment by Zettelkasten** [comment]
> - Instead of specifying `var1`/`var2` for `DotLayer`, the user could specify the common shared axes (`common` or `share` or so). Currently this is implied/inferred. But when this `common` would be specified, we could infer `var1`/`var2`.

If it was like this, then the user would instead need to specify `T?` as common axes when using a DotLayer inside a RecLayer which operates independent of the rec time axis.
This is different to the behavior of all other layers, like e.g. LinearLayer or GatherLayer which just assume that all not explicitly specified dims are "batch" dims.
I feel like specifying it differently here for DotLayer would hurt readability of configs because it's different from what all other layers expect you to specify.

**Comment by albertz** [comment]
Ah yes, you are right. But my suggestion was not to remove the `var` option. It was just an additional way. The user either would provide `var` or `common`.

Btw, the use case I have in mind here are e.g.:
```
d[output + '_att_energy'] = {"class": "dot", "red1": -1, "red2": -1, "var1": "T", "var2": "T?",
               "from": ['base:' + output + '_att_key', output + '_att_query']}  # (B, H, enc-T, 1)
```
Or also (via #391):
```
energy: {class: dot, from: [q, k_accum], red1:"static:-1", red2:"static:-1", var1:"T?", var2:"T"},  # [B,T] inside, [T,B,T] outside

att: {class: dot, from: [v_accum, att_weights], red1:"T", red2: "stag:history?", var1:"static:-1", var2:[]},  # [B,V] inside, [T,B,V] outside
```

Again, what I want to achieve is that the user should not need to care about the potential automatic optimization. Currently this is not the case. The user needs to think about both cases, and must use sth like `T?` for this example.

But the `common` option does not really solve this. It would just make the need for `T?` obsolete in this case. So I think it is still useful to have. But the user still need to think about automatic optimization.

But if the user does not think about automatic optimization, i.e. just about the case inside the loop, it can still break. E.g. the user would maybe write this inside the loop:
```
# base:att_key is (B, enc-T, H, D/H) (base, so outside)
# att_query is (B, H, D/H) (inside)
energy: {
  class: dot, from: ['base:att_key', 'att_query'],
  red1: "static:-1", red2: "static:-1",
  var1: "T", var2: [], add_var2_if_empty:True}  # (B, H, enc-T, 1) (inside)
```

So the question is, can automatic optimization handle that correctly automatically? Or what is needed to be able to do so?
 
It knows that some `base:...` layer will not change by the optimization. So only the input `att_query` changes. So from that it could infer that the extra time axis cannot be part of `common` because it was not part of it before, and thus it must be part of `var2`.

For another example where both inputs are inside the loop, and then both inputs are optimized and get an extra time axis, for this case it should add it to `common`.

For the case we discussed in #391, this is yet more complicated. Because `k_accum` does not get a new time axis when optimized out ([B,T,K] in both cases), so it would be wrong to add it to `common`. So it is more about whether a new time axis is added or not. `k_accum` behaves like `base:att_key` in the example before.

In any case, this logic would be specific to `DotLayer`. For any layer, we would need some new classmethod, like `LayerBase.transform_config_dict_on_opt`, and then `DotLayer` can overwrite this with special logic. Basically if a new time axis is added to both inputs, it would add this axis to `common`, and otherwise to either only `var1` or `var2`.
