### ISSUE TITLE
Cleanup AllophoneStateIdxParserLayer

### ISSUE THREAD

**Issue by albertz** [rwth-i6/returnn#584]
I think this layer is not used by anyone.
It should also be obsolete as it should be possible to reimplement this using other base layers.

Remove?

**Comment by albertz** [comment]
I implemented this layer myself for some old experiments.
Maybe @curufinwe or @Marvin84 are still using it?

**Comment by Marvin84** [comment]
I am using eval layers for getting the phoneme labels out of the dense state-tying and never used this layer.
