### ISSUE TITLE
`SplitDimsLayer` wrong feature axis

### ISSUE THREAD

**Issue by albertz** [rwth-i6/returnn#596]
Via https://github.com/rwth-i6/pytorch-to-returnn/pull/54.

```
# data: [B,F|F'feature:data'(512),T|'time:var:extern_data:data'[B]]
"Unflatten": {'class': 'split_dims', 'from': 'data', 'axis': 'T', 'dims': [-1, 1]},
# unflatten: [B,F'feature:data'(512),T|'time:var:extern_data:data'[B],F|'Unflatten_split_dims1'(1)]
```

I would expect that the original feature dim axis stays as before.

This is due to the default behavior of `NotSpecified`.
As it is not specified (`NotSpecified`) before, it stays not specified after.
But that changes the feature dim axis (1 before, then -1 after).

**Comment by albertz** [comment]
@Zettelkasten what do you think? This should be changed, right?

**Comment by Zettelkasten** [comment]
Ouh yes, this is against all principles that the order of axes should not matter.
In this case, maybe even in general, I am also quite sure that nobody relied on this behavior.
From my POV, passing `feature_dim_axis=NotSpecified` to the `Data` should be resolved to some concrete `int|None`, just like it is now for `time_dim_axis`. But that leaves some questions open, e.g. what should happen if you take a `[B,T]` tensor with `feature_dim_axis=NotSpecified`, and than expand dims by 1. Should the new dim be the feature dim or not? And so on ...

But then again I avoided using `NotSpecified` in all my configs, I never found it useful, only non-transparent. Maybe people that use this have other opinions, and use/like this "feature"?

**Comment by albertz** [comment]
@dierkes-j Note that this was fixed now.
