### ISSUE TITLE
`DotLayer` reduce over dynamic axis should respect the seq mask

### ISSUE THREAD

**Issue by albertz** [rwth-i6/returnn#629]
`DotLayer` should respect the dyn size (or seq mask) when you reduce dynamic axes, just like `ReduceLayer` etc would do over dynamic axes. The `DotLayer` currently completely ignores this. This is fine when the user explicitly performs masking beforehand. E.g. `SoftmaxOverSpatialLayer` will do the right thing. However, otherwise it will be wrong in general. This is esp also a problem for the concept of dynamic axes with extended dynamic sizes.

Implementing this for `DotLayer` is not so nice, though, because this additional masking is not needed for the common case where there was a `SoftmaxOverSpatialLayer` before. The additional masking is not wrong, but it would make it a bit slower. So we definitely want to avoid this. But how can we know when this can be skipped? It could explicitly check whether one of the inputs comes from `SoftmaxOverSpatialLayer` but this would be very ugly, hacky, and also fail in some cases (e.g. by any automatic internal wrapping layers such as `SelectSearchSourcesLayer`). But is there a better more generic way? Somehow some way that the input can say "I'm already masked, padded values are 0, no need to mask again". Other layers like `ReduceLayer` could also use this information. The padded values are also relevant. For `DotLayer` we want 0. For `ReduceLayer` with `sum` or `avg` we want 0. For `ReduceLayer` with `max` or also `SoftmaxOverSpatialLayer` we want -inf. But then, I'm not sure if we are maybe making it too complicated in end.

_Originally posted by @albertz in https://github.com/rwth-i6/returnn/issues/391#issuecomment-906772624_

**Comment by Zettelkasten** [comment]
Related to this and also to #627, I also just now noticed that it is a little weird/inconsistent that we have `red1` and `red2` as arguments. These axes really need to be the same, and also share the same dyn lengths.
But if I understood correctly it's also possible to have dim tags that are marked the same, but have different descriptions. Then that logic here would fail. I'm not sure if that's a real issue or if that's something we should even allow. The user could always just rename the axes before.

**Comment by albertz** [comment]
> Related to this and also to #627, I also just now noticed that it is a little weird/inconsistent that we have `red1` and `red2` as arguments. These axes really need to be the same, and also share the same dyn lengths.

This is only very recent that we allow to specify dim tags. At least directly. A bit longer that we allow it by name. But then we also still do not guarantee to have them unique (which is another thing we want at some point).

Also, specifying static dims is probably still not optimal because you likely end up with different dim tags. Basically all layers which accept `n_out` should instead accept a static dim tag to make this work well. Otherwise you will always have different dim tags.

Also, users might specify integers (unless we fix #627).

So currently we just have some checks that static dims are the same.

But I agree, if we have dim tags even more consistent, also for static dims, and also unique, then it make sense to just specify reduce dims jointly for both inputs. But we are not really there yet.

> But if I understood correctly it's also possible to have dim tags that are marked the same, but have different descriptions. Then that logic here would fail. I'm not sure if that's a real issue or if that's something we should even allow. The user could always just rename the axes before.

Why would it fail? The description would not matter at all when you directly specify the dim tag.

**Comment by Zettelkasten** [comment]
Ah yes, I didn't think far enough about this. I mainly thought about sharing the strings the user provides (i.e. just take some `red: str`, and then use `red_i=input_i.get_axes_from_description(red)`, behaving just like we set `red1=red2=red`).
But what you say makes more sense, not just the axis descriptions should be the same, but really the dim tags.

> > But if I understood correctly it's also possible to have dim tags that are marked the same, but have different descriptions. Then that logic here would fail. I'm not sure if that's a real issue or if that's something we should even allow. The user could always just rename the axes before.
> 
> Why would it fail? The description would not matter at all when you directly specify the dim tag.

Yea, that would work fine if we enforce the dim tags to be the same, not the descriptions.

> But anyway, we should discuss this in a separate issue. This is really orthogonal/independent of handling the seq mask.

Okay.
