### ISSUE TITLE
Error in RangeInAxisLayer

### ISSUE THREAD

**Issue by robin-p-schmitt** [rwth-i6/returnn#638]
https://github.com/rwth-i6/returnn/blob/8f5142be4ae7ef1770bbe37db82cc0f95def3674/returnn/tf/layers/basic.py#L2025

I think there is an error in the layer. The description says:
`Assume that the input is e.g. (B,T,D), and you specify axis="T", you will get (B=1,T,D=1),
  where the specified axis is filled with ``tf.range``.`

It first sets: `out = tf.range(0, source_shape[axis], dtype=dtype)` (shape (T,))
Then, if we set `keepdims=True`, it sets the output shape as follows:
`out_shape = [
        source_shape[i]
        if (i == axis or i == self.output.batch_dim_axis)
        else 1
        for i in range(self.output.batch_ndim)]`
In the example, this would yield shape `(B,T,1)`.

Then, in the end, it tries: `out = tf.reshape(out, out_shape)`. However, this won't work because tf doesn't support broadcasting in the reshape function and therefore we cannot reshape `(T,)` to `(B,T,1)`.
In my case, tf raised the error: `Input to reshape is a tensor with 3 values, but the requested shape has 12`, because my range axis has size 3 and my batch axis has size 4.

However, even if it would work, it would not return the shape described in the documentation, namely `(1,T,1)`. 

An easy fix would be to just change the output shape:
`out_shape = [
        source_shape[i]
        if i == axis
        else 1
        for i in range(self.output.batch_ndim)]`

What do you think? @albertz @Zettelkasten

**Comment by Zettelkasten** [comment]
I think the batch dim axis always needs to be unbroadcasted. I think there is code that relies on this (maybe beam search and so, I'm not sure). E.g. see `Data.copy_add_batch_dim`, that also always unbroadcasts the batch dim.

So maybe we should update the docstring?

Is this actually an issue for you?

Also there is `keepdims=False` you could set. Then the output shape is just `(T)`.
I would usually always use `keepdims=False`. This makes much more sense to me than having these "dummy" axes.
I think those were mainly there because some layers didn't support inputs without a batch dim back then. But most now should do that.

**Comment by robin-p-schmitt** [comment]
I don't really need it as I can also use the `ExpandDimsLayer` afterwards to re-add the axes with `dim=1` (so that other layers can broadcast the dimensions then). I was just wondering if the layer would work at all if setting `keepdims=True` because I think the reshape operation always fails in this case, right? Except for when we choose the batch axis as the range axis.

**Comment by albertz** [comment]
You should never need to add the axes.


Robin Schmitt ***@***.***> schrieb am Fr., 10. Sept. 2021,
13:01:

**Comment by Zettelkasten** [comment]
> I was just wondering if the layer would work at all if setting keepdims=True because I think the reshape operation always fails in this case, right?

Oh yea, I think you're right. So I guess nobody anyway used `RangeInAxisLayer` with `keepdims=True`? I would then maybe suggest just to remove `keepdims=True` entirely... see #639.

**Comment by albertz** [comment]
Such broadcast axes should never be needed to be added. RETURNN should always handle that correctly internally. In fact, manual broadcast axes by the user could be even confusing for RETURNN (although there is some logic for it to handle that, e.g in `Data.get_common_data`, or `Data.copy_compatible_to`).

For the same reason, there should never be the need to use `ExpandDimsLayer`.

**Comment by robin-p-schmitt** [comment]
> Such broadcast axes should never be needed to be added. RETURNN should always handle that correctly internally. In fact, manual broadcast axes by the user could be even confusing for RETURNN (although there is some logic for it to handle that, e.g in `Data.get_common_data`, or `Data.copy_compatible_to`).
> 
> For the same reason, there should never be the need to use `ExpandDimsLayer`.

Okay, I didn't know that RETURNN could do that automatically. I will have a look at that.
