### ISSUE TITLE
`RangeInAxisLayer`, make `keepdims=False` the default

### ISSUE THREAD

**Issue by Zettelkasten** [rwth-i6/returnn#639]
Are there any reasons why one would ever add such "broadcast/dummy" dim? This seems unintuitive to me. `RangeInAxisLayer` even unbroadcasts the batch dim.
I feel like having `keepdims=True` is mostly legacy, because many layers expected the batch dim axis to exist in the past. But now most should be fine.
If there's no reason to have it around, I would also deprecate `keepdims=True` entirely.

This would need a new behavior version (#508).

Also see #638.

**Comment by Zettelkasten** [comment]
As in #638, `keepdims=True` was anyway broken for inputs with a batch dim? So probably nobody ever used this default anyway?

**Comment by albertz** [comment]
> Are there any reasons why one would ever add such "broadcast/dummy" dim?

No. You are right, this is legacy. And in case there are any other layers which behave wrongly, those should be fixed.

> If there's no reason to have it around, I would also deprecate `keepdims=True` entirely.

Yes.

> This would need a new behavior version (#508).

Maybe. I think the behavior should actually not change. So maybe we can safely change the default without new behavior. Not sure.

**Comment by albertz** [comment]
Yea, or as discussed in #638, as `keepdims=True` seems to be broken anyway and no-one has cared so far, and all tests are passing, this case seems to be unused, so we maybe should just change the default, and raise an error when it is set to True. 

No new behavior version needed then.
