### ISSUE TITLE
Online decoding

### ISSUE THREAD

**Issue by modernAlcibiades** [rwth-i6/returnn#69]
Does returnn framework support models with an online sequence decoder like neural transducer? Can you suggest what files and classes I should look into to write one such config?

**Comment by albertz** [comment]
The `RecLayer` is very generic and supports any kind of models. That also allows online sequence models. It also allows for online / local attention models.

**Comment by albertz** [comment]
Not sure if there is any issue/bug in Returnn, so closing this issue now.
Feel free to reopen if you think there is some problem.
For questions/discussions, better just write a mail.
