### ISSUE TITLE
Accessing Prev: in Subnetwork of Rec Unit in Search/Forward

### ISSUE THREAD

**Issue by Atticus1806** [rwth-i6/returnn#698]
Hey, 

when trying to use `prev:` in a subnetwork of a recurrent unit, it causes the error, that the layer is not found, so e.g. 
`LayerNotFound: sub-layer 'prev:accum' not found in <TFNetwork 'root/decoder(rec-subnet)/accum_sub(subnet)' parent_layer=<InternalLayer decoder/'accum_sub' out_type=Data{[B?]}> train=False search>` .  
From what i am aware this does not happen in training, only when task is forward or search.

A short config to reproduce this would be: 
```
#!rnn.py
use_tensorflow = True
task = "search"
train = {"class": "DummyDataset", "input_dim": 1, "output_dim": 1, "num_seqs": 1, "seq_len": 5}
eval = train
load = '/u/hilmes/experiments/tts_new_sis/work/i6_core/returnn/training/ReturnnTrainingJob.bunNt3PJFk7D/output/models/epoch.200'
network = {
  "output": {
    "class": "rec",
    "from": "data",
    "unit": {
      'accum_sub': {
        'class': 'subnetwork', 'from': [],
        'subnetwork': {
          'accum': {'class': 'combine', 'kind': 'add', 'from': ['prev:accum', 'data:source']},
          'output': {'class': 'copy', 'from': 'accum'}}},
      'output': {'class': 'copy', 'from': 'accum_sub'}}}}
num_inputs = 1
num_outputs = 1
```
while this config is not fully working even without the error, it causes the error, thus should be sufficient, which can be "fixed" by moving `accum` out of `accum_sub`, which then causes other errors which are not related. 
<details>
 <summary>(old) "working" config  </summary>

```
#!rnn.py
use_tensorflow = True
task = "search"
train = {"class": "DummyDataset", "input_dim": 1, "output_dim": 1, "num_seqs": 1, "seq_len": 5}
eval = train
load = '/u/hilmes/experiments/tts_new_sis/work/i6_core/returnn/training/ReturnnTrainingJob.bunNt3PJFk7D/output/models/epoch.200'
network = {
  'decoder': {
    'class': 'rec',
    'from': 'data',
    'target': "classes",
    'unit': {
      'accum': {'class': 'combine', 'kind': 'add', 'from': ['prev:accum', 'data:source']},
      'output': {'class': 'copy', 'from': 'accum'}}},
  'output': {'class': 'copy', 'from': 'decoder'}}
num_inputs = 1
num_outputs = 1
```

</details>

**Comment by albertz** [comment]
(Can you fix the formatting?)

**Comment by albertz** [comment]
I don't see `accum_end` in your example.

**Comment by Atticus1806** [comment]
> I don't see `accum_end` in your example.

Oh, whoops, pasted the original error not the one from the example config, changed now.

**Comment by albertz** [comment]
For `end`, you need a bool of shape [B].
But if you don't really need that for the example, just use `from: data` in the rec layer, and then `data:source` inside.
Always try to simplify the example as much as possible.

**Comment by Atticus1806** [comment]
Actually you are right, I thought the `end` layer was needed for rec unit but it crashes before that so I can just remove that too. 
Simplified a bit more and also fixed the formatting.

**Comment by albertz** [comment]
(Can you fix the formatting with 2 space indent instead of tab?)

**Comment by albertz** [comment]
Also, you don't need `'end'` at all in the example then.

**Comment by Atticus1806** [comment]
>(Can you fix the formatting with 2 space indent instead of tab?)

Yeah I can try, for some reason copying from Pycharm does weird things to the formatting so gotta do that by hand :D 

> Also, you don't need 'end' at all in the example then.
Right

**Comment by Atticus1806** [comment]
ah think i found the setting now

**Comment by albertz** [comment]
Note that when you use `base:prev:accum_sub/accum` instead of `prev:accum`, it works. But I guess we should also make it work for `prev:accum`.

I started to work on this in PR #699.

**Comment by albertz** [comment]
Note that you also have another small mistake: You want to use `base:data:source` instead of `data:source` in the subnet.

**Comment by Atticus1806** [comment]
>Note that you also have another small mistake: You want to use base:data:source instead of data:source in the subnet.
Also no cop.

Oh yes, I updated the network to your config from the test and also put the "working" config in a spoiler since its different from this test config. 

Thanks anyways for the quick response!
