### ISSUE TITLE
GatherLayer: problem with search beam

### ISSUE THREAD

**Issue by robin-p-schmitt** [rwth-i6/returnn#708]
There is a problem with the `get_out_data_from_opts` function of `GatherLayer` during search. This is the problematic part:

```
out_type = input_data.get_kwargs(include_special_axes=False)
out_type["name"] = "%s_output" % name
out_type["dim_tags"] = dim_tags
out_type["beam"] = SearchBeam.get_combined_beam(input_data.beam, position_data.beam)
out_type["available_for_inference"] = input_data.available_for_inference and position_data.available_for_inference
...
output_data = Data(**out_type)
```

`out_type` uses the `batch` information from `input_data` and the **combined** `beam` information from `input_data` and `position_data`. This means that `batch.beam` and `beam` can be different if `input_data` and `position_data` have different beam information and this leads to a problem inside of `output_data = Data(**out_type)`:

```
  File "/mnt/projects/i6/returnn/returnn/tf/util/data.py", line 1490, in Data.__init__
    line: assert batch.beam == beam
    locals:
      batch = <local> BatchInfo{B}
      batch.beam = <local> None
      beam = <local> SearchBeam(name='output/prev:output', beam_size=3)
AssertionError
```

The full error and the code to reproduce the problem are in https://gist.github.com/robin-p-schmitt/9e8d968fa2609cf17909c1bd6e25c5c0.

**Comment by albertz** [comment]
See for example `DotLayer`. When you add sth like:
```
out_type["batch"] = BatchInfo.get_common_batch_info([src.batch for src in (input_data, position_data)])
```
This probably fixes the problem.
Can you try, and maybe create a PR? The PR should then also include your test.
