### ISSUE TITLE
`Data`: `sparse_dim: DimensionTag` to unify `sparse`, `dim`, `vocab`

### ISSUE THREAD

**Issue by albertz** [rwth-i6/returnn#722]
It would be nice to have a `DimensionTag` which describes the sparse dim (when `Data.sparse is True`).

**Comment by Zettelkasten** [comment]
This is also nice/required for when we add an `axis`/`in_dim` argument to `LinearLayer`.

**Comment by albertz** [comment]
`Data.dim_tags` corresponds to the dims which are really present in the tensor. So to `batch_shape`. Or we have the property `Data.placeholder.ndim == len(Data.dim_tags)`. I would leave that behavior of `dim_tags`.

However, we can make a separate `implicit_dim_tags` or so. Very similar as what I proposed as `out_implicit_shape` in #706.
