### ISSUE TITLE
`DotLayer` argument simplifications

### ISSUE THREAD

**Issue by albertz** [rwth-i6/returnn#739]
This issue is just to collect recent orthogonal but related proposals.

# `DotLayer` specific

- #627 
- #636 
- #738
- #740 
- #741
 
# Related on dim tags

- #597
- #632
- #634 
- #706 

# Other related

- #691
- `GatherLayer`
- `LinearLayer`

**Comment by albertz** [comment]
Note, in principle, `DotLayer` would not need any options anymore, as we can infer all the information about what axes to reduce and what axes are shared. However, I think it is good to have to specify the `reduce` axes explicitly. Maybe we could however omit this when the user specifies `out_shape`.

**Comment by Zettelkasten** [comment]
The `reduce` arg is always needed to distinguish it from the common axes, right?
(Okay, you could infer it from `out_shape` as it is not present there but the common axes are.)

**Comment by albertz** [comment]
> The `reduce` arg is always needed to distinguish it from the common axes, right? (Okay, you could infer it from `out_shape` as it is not present there but the common axes are.)

Ah yes you are right.

**Comment by albertz** [comment]
I think all the main features for `DotLayer` are implemented now, so this can be closed.
