### ISSUE TITLE
VariableLayer, use add_batch_axis=False by default

### ISSUE THREAD

**Issue by albertz** [rwth-i6/returnn#763]
This is probably an historic artifact and should never be needed.

Similar as #630 and #639.

This maybe needs a new behavior version (#508). Or maybe not, as it should (in theory) have no impact on anything...

**Comment by Zettelkasten** [comment]
> This needs a new behavior version (#508).

I wonder, is this really needed? I don't think there are many layers which really operate on this axis and that make sense to use after `VariableLayer`. Or are there still layers that require a batch axis to be present?

**Comment by albertz** [comment]
Hm yea, maybe you are right. I don't know. I guess I just check if all our tests are passing, and if so, then it is fine.

**Comment by Zettelkasten** [comment]
Further, if this is really doesn't break anything, we could also go as far and just remove support for `add_batch_axis` and `add_time_axis` entirely, just as we did in #641 for `RangeInAxisLayer`.

**Comment by albertz** [comment]
> Further, if this is really doesn't break anything, we could also go as far and just remove support for `add_batch_axis` and `add_time_axis` entirely, just as we did in #641 for `RangeInAxisLayer`.

In #641 where we removed `keepdims` in `RangeInAxisLayer`, this was safe as it was anyway broken in the code (as far as I remember), so no working config could possible exist and get broken by this change.

This is maybe different here. It has worked before, so any config with explicit `add_batch_axis=True` would have worked before and would break then.

Although, there are probably not much (or any) configs which do have that. I don't know.

So this might need a new behavior version.
