### ISSUE TITLE
Examples for DimensionTag usage

### ISSUE THREAD

**Issue by JackTemaki** [rwth-i6/returnn#775]
Currently there is no good starting point for users (including myself) to get familiar with the usage of the DimensionTags.

We have:
 - https://returnn.readthedocs.io/en/latest/user_guide/dataset.html#synchronizing-dynamic-axes , which is a very specific limited use case
 - https://github.com/rwth-i6/returnn/wiki/Operations-on-dimension-tags , which gives only very abstract information that is not directly useful
 - https://returnn.readthedocs.io/en/latest/api/tf.util.data.html#returnn.tf.util.data.DimensionTag , where the docstring also does not really provide information
 
And I am not aware of public config examples (outside of Github issues/PRs maybe) that make use of it. So with the current state no one is invited to use them, but will stick to the old way of defining axes. Of course we can keep this hidden, and then only provide examples for the upcoming returnn-common setups. I just wanted to raise this issue as #258 was closed.

**Comment by albertz** [comment]
Note that usually in many cases the tests are also good examples. Or even, in almost all cases. Just see for usages of `DimensionTag` throughout the test cases.

**Comment by albertz** [comment]
Also note that the API for the user is actually not really fixed or decided yet. Of course you can use it as it is used internally. Any many people do that already like that. But this can be a bit verbose.

Related is also: https://github.com/rwth-i6/returnn_common/issues/17

**Comment by albertz** [comment]
One starting point is here in the documentation: https://returnn.readthedocs.io/en/latest/getting_started/data.html

This should give an overview of `Data` and `DimensionTag`. If this overview is lacking, we should extend that.

**Comment by albertz** [comment]
This has been extended now via #853. I guess this is a good starting point. And as said, there are already lots of examples via all the test cases.
