### ISSUE TITLE
`ConvLayer` `with_bias=False` default is inconsistent to `LinearLayer` `with_bias=True` default

### ISSUE THREAD

**Issue by albertz** [rwth-i6/returnn#787]
I don't really know if we should do anything now, or change this.
I just want to raise this issue here.
Maybe we can also just close it if this is fine or we cannot really do anything about it now.

I also want to know whether one of the settings is very unexpected so users might have used it wrongly. That would be an argument to make it explicit or change the default (of course via new behavior version (#508)).

Also, as usual, we should check the defaults of other frameworks.

* [PyTorch `Linear`](https://pytorch.org/docs/stable/generated/torch.nn.Linear.html): `bias=True`
* [PyTorch `Conv1d`](https://pytorch.org/docs/stable/generated/torch.nn.Conv1d.html): `bias=True`
* [Keras `Dense`](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dense): `use_bias=True`
* [Keras `Conv1D`](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Conv1D): `use_bias=True`

So in all cases, it seems that `with_bias=True` would be more expected.

**Comment by albertz** [comment]
There was not so much feedback yet (also not on Slack).

I think `with_bias=True` makes more sense to have it consistent to everything else.

The question is how to introduce this. Just via a new behavior version?

**Comment by vieting** [comment]
I agree `with_bias=True` is more consistent. A new behavior version makes sense to me.
