### ISSUE TITLE
NativeLstm (version 1) does not correctly handle first/last state

### ISSUE THREAD

**Issue by albertz** [rwth-i6/returnn#813]
This test case fails:
```
def test_reclayer_optimize_out_rec_nativelstm():
  check_reclayer_optimize_out({"class": "rec", "unit": "NativeLstm"})
```
Note that this is specifically about the first version. It works correctly with `NativeLstm2`.
Unfortunately our `unit="lstm"` default currently uses `NativeLstm` internally. So when you just used `lstm`, you have the same problem.
The same problem also for `unit="lstmp"`.
(Maybe it's anyway a good idea to change that default to `NativeLstm2`.)

From briefly looking at it, I think the reason is that `NativeLstm` does not handle the first (initial) and last state correctly or completely. It looks like it only handles the cell state `c` but not `h`.

When the LSTM is not optimized out of the loop, it means this problem occurs every single frame.

This means, when you used sth like this in your config, the LSTM was not behaving correctly:
```
...
output: {class: rec, ..., unit: {
  ...
  s: {class: rec, unit: lstm, ...},
  ...
}}
```
This is quite standard in some attention-based LSTM-based encoder-decoder models.

Note that when you used `rnn_cell`, you could not make use of `NativeLstm` anyway, so you did not have this problem (only the problem that it is slow).
Also, again as stated before, when you use `NativeLstm2`, you also did not have this problem.

**Comment by albertz** [comment]
I'm not exactly sure what to do about it. Maybe just disallow `NativeLstm` inside another rec layer so that people do not run into this. Maybe additionally changing the `RecLayer` `unit="lstm"` default to `NativeLstm2`.

**Comment by JackTemaki** [comment]
I think I started to always use nativelstm2 some time ago, there should be no remaining `nativelstm` layers in my setups, but I will verify. Some seutps transfered from other people might have it.

**Comment by michelwi** [comment]
Thanks for the heads up, I was not using `NativeLstm` (v1) in my experiments.
