### ISSUE TITLE
AvgPooling not implemented for all axis shapes on CPU

### ISSUE THREAD

**Issue by JackTemaki** [rwth-i6/returnn#829]
As this was part of a RASR Job I do not have a stacktrace, but I got this error when running from a compiled graph:
```
error calling Session::Run (target: ): Invalid argument: Default AvgPoolingOp only supports NHWC on device type CPU
         [[{{node blstms/2/pool_0/avg_pool}}]]
```
which means there is the necessity to restrict the pooling layer to some specific axis layout when using average as pooling method.
On GPU everything was fine of course.

**Comment by albertz** [comment]
How do you compile the graph? There is no real bug here, neither in TensorFlow nor in RETURNN.

When you compile the graph for GPU, it is correct to use NCHW because that is faster.
When you compile the graph for CPU, it would automatically use NHWC.

**Comment by JackTemaki** [comment]
Oh you are right, this is an issue with the limitations of the tf_compile_graph.py tool, and not about the RETURNN graph.
I will extend this and make a PR, there is no issue here.

**Comment by JackTemaki** [comment]
Okay I am a little bit confused here, the version I had this issue with is from 1. December, and there it correctly switches between NCHW and NHWC for GPU and CPU respectively. I wanted to add a flag to compile_tf_graph.py to specifically define a target device, but now I found that the current master does always produce NHWC.

**Comment by JackTemaki** [comment]
I tested this with an old config, so none.

**Comment by albertz** [comment]
#814 and #823 are probably related.

**Comment by albertz** [comment]
Ok, before those changes, the logic to make it NCHW was:
```
if tf_util.is_gpu_available_in_session() and use_channel_first:
 ...
```

**Comment by albertz** [comment]
Do you have `use_channel_first=True` set explicitly in your config on the pool layer options?

**Comment by JackTemaki** [comment]
I did not set `use_channel_first=True`, but still got the NCHW order.

**Comment by JackTemaki** [comment]
Okay so there is no bug here, I just updated RETURNN in the middle of your restructuring work. I will fix this manually in my Sisyphus Graph, and as this is only a testing setup it will re-run with another RETURNN commit and updated behavior version anyways.

**Comment by albertz** [comment]
Ah I see. Yea, first I thought it might make sense to always do this. Then I reconsidered that it should be maybe only be done automatically with new behavior version to not cause any troubles on older setups which depend on some specific order of axes.

But in any case, then what you need is just this flag for tf_compile_graph.
