### ISSUE TITLE
Axis option for per-step execution

### ISSUE THREAD

**Issue by albertz** [rwth-i6/returnn#847]
This probably needs some further extensions to #780.

- Also for `RecLayer`, in addition to `WindowLayer` and `CumsumLayer`. But also other rec layers.
- It should also be possible to operate on a single step without any outer rec layer (e.g. [here](https://github.com/rwth-i6/returnn_common/blob/6d263503989777157fd40409ca2f4492949411cb/nn/rec.py#L37)).
  - Specifying `axis=None` would maybe be the natural thing for this. Maybe just extending `is_axis_from_description_recurrent` for that case is enough?
  - Or otherwise I thought about a special placeholder object like `SingleStep`, and then `axis=SingleStep` (or `NoAxis` or sth like that).
  - Or otherwise maybe an extension (or similar mechanism) of what I introduced in #846.

_Originally posted by @albertz in https://github.com/rwth-i6/returnn/issues/780#issuecomment-988099158_

**Comment by Zettelkasten** [comment]
I think I would rather use `SingleStep`, my first thought when seeing `NoAxis` was that it meant "all axes" like numpys/TFs `np.sum(x, axis=None)` does (even though that doesn't make much sense for `RecLayer`).

For `CumsumLayer` and `WindowLayer`, such option would be quite useless, or not? Only for layers that have params?

**Comment by albertz** [comment]
Why useless? It would just imply that the layer should operate per step. If it is inside a rec layer, it would use the prev state (via `_rec_previous_layer`), otherwise it would use `RnnCellLayer.get_rec_initial_state` or so. Basically exactly like `RecLayer` is already doing it. So e.g. `WindowLayer` with `axis=SingleStep` would simply perform its operation for a single step, and use the prev state explicitly via `state=...` (via #732).

Why is it relevant that the layer has params?

Although, you are maybe right, that the functionality of `CumsumLayer` in this setting is trivial (just `state + input`) and there is no real point in using it. Maybe similar for `WindowLayer`.

This is mostly needed now for a clean way to implement [this](https://github.com/rwth-i6/returnn_common/blob/6d263503989777157fd40409ca2f4492949411cb/nn/rec.py#L37).

But e.g. for the `cumsum` example, a user would probably never think of it this way, and just write `state + x` or so. The downside we have with this is that it likely breaks recurrent optimization.

**Comment by Zettelkasten** [comment]
> Although, you are maybe right, that the functionality of `CumsumLayer` in this setting is trivial (just `state + input`) and there is no real point in using it. Maybe similar for `WindowLayer`.

Ah yeah this is what I meant. But okay sure, let's add it for all these layers - it does make sense.

> But e.g. for the `cumsum` example, a user would probably never think of it this way, and just write `state + x` or so. The downside we have with this is that it likely breaks recurrent optimization.

You mean in general, or in connection to `axis=SingleStep`? Because when using `axis=SingleStep` there is no real recurrency anyway (it's just a single step), so there is nothing to optimize right?

**Comment by albertz** [comment]
> > But e.g. for the `cumsum` example, a user would probably never think of it this way, and just write `state + x` or so. The downside we have with this is that it likely breaks recurrent optimization.
> 
> You mean in general, or in connection to `axis=SingleStep`? Because when using `axis=SingleStep` there is no real recurrency anyway (it's just a single step), so there is nothing to optimize right?

I meant when the user writes sth like:
```
cumsum: {class: combine, kind: add, from: ["prev:cumsum", "input"]}
```
Rec optimization cannot optimize this out of the loop.
This could even lead to further cases which can not be optimized, like:
```
...
cumsum1: {class: combine, kind: add, from: [prev:cumsum1, input]},
linear: {class: linear, from: cumsum1},
cumsum2: {class: combine, kind: add, from: [prev:cumsum2, linear]},
...
```
Now `linear` can never be moved out of the loop because it is between two layers which must be inside the loop.
If you would use `CumsumLayer` here instead of `CombineLayer`, it could optimize all out.

However, we could extend the rec optimization to cluster layers, so we don't just have those three nets we currently have.

Anyway, `CumsumLayer` with `axis=SingleStep` inside a rec layer should just behave like `axis="T"` or `axis=rec_time_dim`.
