### ISSUE TITLE
Assertion error during subnetwork template creation

### ISSUE THREAD

**Issue by patrick-wilken** [rwth-i6/returnn#85]
```
 File "/home/pwilken/src/returnn/TFNetworkRecLayer.py", line 2219, in get_dep_layers
    line: assert self.is_prev_time_frame
    locals:
      self = <local> <_TemplateLayer 'dec_01_self_att_att' uninitialized, construction stack 'dec_01_self_att_lin'>
      self.is_prev_time_frame = <local> False
AssertionError
```

The full log: https://gist.github.com/patrick-wilken/a4d7883b2fdbd18794b7aa7eb51195fd
A config to reproduce: https://gist.github.com/patrick-wilken/74fea715da921a155ccad0732ebdd85a
(use some dummy dataset)

This was introduced by 88db504. I tried to dig in a bit, it appears that get_dep_layers() fails, because init() was not called for the layer and thus neither is_data_template nor is_prev_time_frame is set.

@julian90 Can you confirm that your transformer setup does not work with the current code?
Although I realized that the error occurs somewhat randomly, e.g. it disappears when removing some transformer layers.

**Comment by nikita68** [comment]
With which settings did you get it to work? I'm getting the same error.

**Comment by patrick-wilken** [comment]
For now I'm just using an older version of the code (tagged v2.1.0-beta). As I said I did not figure out when exactly the error occurs. It e.g. disappeared after removing one of 6 transformer layers, which principally should not change anything.

**Comment by nikita68** [comment]
Hmm, interesting. Thanks for the info!

**Comment by albertz** [comment]
I pushed 0ef9562d36 which should hopefully fix this. Can you try?

**Comment by patrick-wilken** [comment]
Yep, looks good!
