### ISSUE TITLE
Speaker tags in SprintDataset

### ISSUE THREAD

**Issue by JackTemaki** [rwth-i6/returnn#927]
Currently there is no support to use speaker labels via the `ExternSprintDataset`.

In combination with 80d0a3845ca60ad78d49b25beeb5e22342b44ca7 I figured out that replacing
``` python
    self.num_outputs["speaker_name"] = (256, 1)
```
by
```python
    if "speaker_name" in self.target_maps:
      self.num_outputs["speaker_name"] = (len(self.target_maps["speaker_name"]), 1)
    else:
      self.num_outputs["speaker_name"] = (256, 1)
```
in https://github.com/rwth-i6/returnn/blob/master/returnn/datasets/sprint.py#L140
would be sufficient to get working embeddings.

However there are some issues here:
 - `speaker_name` is then containing indices instead of the utf8 string, which is counter-intuitive
 - It seems that `target_maps` can only be used for `speaker_name` and for nothing else, as the corresponding entry in `self.num_outputs` will always be wrong, thus causing a crash at some point. Also, there is no test case using `target_maps`.
 
 So my question would here be: should I simply proceed with the small fix (takes no time, would work for my use case) or should we refactor this to be better designed, meaning removing the possibly useless/broken `target_maps` parameter and code, and introducing a consistent and documented `speaker_map` parameter that will create a new output called `speaker_classes` (consistent naming with with `orth_classes`) based on the map file.

**Comment by albertz** [comment]
`target_maps` is probably also only rarely used. This seems to be very old code. I don't understand why you think this is only for `speaker_name`. This can be used for any data with fixed number of classes. But you are right that it might need some fixed depending on how this is used, e.g. fixing `num_outputs`.

But I wonder now, I think some people made use of this, e.g. Markus Kitza for speaker adaptation, or maybe also @vieting or Tobias Menne. How does their setup look like?

I'm quite sure that there are some setups using `target_maps`. Maybe only older ones.

But in any case, yes, the `len(self.target_maps["speaker_name"])` change should be pushed, and we could later just handle other cases.

**Comment by JackTemaki** [comment]
> I don't understand why you think this is only for `speaker_name`

No this is not what I meant, I meant after the fix it would work only for `speaker_name`, but for nothing else. So basically what you confirmed. At least from Markus setups I know that they did not use this (the i-vector extraction code is independent from RETURNN training).

Ok, I will push the change.

**Comment by vieting** [comment]
> But I wonder now, I think some people made use of this, e.g. Markus Kitza for speaker adaptation, or maybe also @vieting or Tobias Menne. How does their setup look like?

I don't remember having any setup which depends on the speaker name.

**Comment by albertz** [comment]
You pushed directly to master but your commit caused problems (failing tests). So I reverted this. Please make a PR instead.
