### ISSUE TITLE
Specified out dim tags potentially needs duplicated logic

### ISSUE THREAD

**Issue by albertz** [rwth-i6/returnn#955]
This is a follow-up to the introduction of out dim tag options for all layers (#597).

Take `ConvLayer` as an example, and the `out_spatial_dims` option.

How would you work with this in practice? Consider both the case where the user writes the config and net dict by hand, but also more importantly the case of returnn-common.

Some aspects:

* Consider padding="same", stride=1, i.e. the output spatial dim should be the same as the input spatial dim.
Now when the user provides some custom out spatial dim, what should happen? Should the `ConvLayer` automatically use `declare_same_as`? Already in `get_out_data_from_opts` or only in `__init__`? I'm a bit afraid that this could cause very nasty and hard to find bugs, or it might make debugging for the user difficult if some dim tags got merged which should not have been merged. The user might not expect such side effect.

* Consider a static spatial dimension, and stride > 1. Should the user calculate by hand the resulting dimension? Maybe actually this is not a bad idea, although sometimes it could also be annoying when you don't care about it exactly. But consider returnn-common. The out spatial dim tag would usually be automatically created. (See: https://github.com/rwth-i6/returnn_common/issues/17#issuecomment-1004026430) But this means we need to calculate the output dimension beforehand, and duplicate the same logic  `calc_out_dim` on returnn-common side (or maybe just call `ConvLayer.calc_out_dim`). In any case, this makes the logic on returnn-common side quite a bit more complicated, and also un-intuitive. This is bad. It should not be complicated and un-intuitive.

The same issue is for many layers, also e.g. `MergeDimsLayer` etc. See all the layers mentioned in #597.

Some potential solutions:

* We could allow `Dim.dimension == NotSpecified` or so (or introduce yet another flag to `Dim`), to mark the passed out spatial dim as not-yet-specified. This explicitly tells `get_out_data_from_opts` that it can fill in the details. E.g. call `declare_same_as` or define `dimension = ...`. This would not be so confusing because it is explicitly written down that there should be modifying side effects on this dim. One issue with this is that we would again need to go through all layers in #597 and extend the logic in all `get_out_data_from_opts`.

* On returnn-common side, we could not pass the out spatial dims at all. Due to https://github.com/rwth-i6/returnn_common/issues/47, we can just take whatever the layer creates in `get_out_data_from_opts`. We might set `auto_generated = False` then. This would be a very simple solution.

On returnn-common side, this is reported here: https://github.com/rwth-i6/returnn_common/issues/116

**Comment by Zettelkasten** [comment]
> * We could allow `Dim.dimension == NotSpecified` or so (or introduce yet another flag to `Dim`), to mark the passed out spatial dim as not-yet-specified. This explicitly tells `get_out_data_from_opts` that it can fill in the details. E.g. call `declare_same_as` or define `dimension = ...`. This would not be so confusing because it is explicitly written down that there should be modifying side effects on this dim. One issue with this is that we would again need to go through all layers in [Specify dim tags for layers that create new axes #597](https://github.com/rwth-i6/returnn/issues/597) and extend the logic in all `get_out_data_from_opts`.

We already have such logic for dim tags with dynamic sizes. E.g. when you declare some dim tag in your config (where it has `dyn_size_ext=None` by default), and it is used as `out_spatial_dim` by some layer, then it's `dyn_size_ext` is set implicitly via `declare_same_as`. So here we don't even use such special `NotSpecified` value.
I think the assumption so far was that whenever `dimension is None`, `dyn_size_ext` should be completed.
I think this is fine to also have for static dims, but then we should also change it such that exactly one of `Dim.dimension` and `Dim.dyn_size_ext` is always `None`, and the other never (either `NotSpecified`, or having an actual value).
Now it would also be nicer to actually sub-class `Dim` into some `StaticDim` and `DynamicDim`, where `StaticDim` only has one attribute `dimension` and not `dyn_size_ext` and vice-versa.

**Comment by Zettelkasten** [comment]
> * Consider padding="same", stride=1, i.e. the output spatial dim should be the same as the input spatial dim.
>   Now when the user provides some custom out spatial dim, what should happen? Should the `ConvLayer` automatically use `declare_same_as`? Already in `get_out_data_from_opts` or only in `__init__`? I'm a bit afraid that this could cause very nasty and hard to find bugs, or it might make debugging for the user difficult if some dim tags got merged which should not have been merged. The user might not expect such side effect.

I think RETURNN should never declare two dims equal that are both user defined, I think that is confusing and very implicit.
In the case that `out_spatial_dim` is not declared explicitly in such case, then I'm not sure what I'd like. Probably a more restrictive behavior, i.e. behavior that does not declare them as equal, is better in many cases but perhaps inconvenient.

**Comment by Zettelkasten** [comment]
> * On returnn-common side, we could not pass the out spatial dims at all. Due to [Make shape and dims available? returnn_common#47](https://github.com/rwth-i6/returnn_common/issues/47), we can just take whatever the layer creates in `get_out_data_from_opts`. We might set `auto_generated = False` then. This would be a very simple solution.

I think I would like it more if there would always be an `out_spatial_dim` arg, otherwise you would need to write something like this:
```
conv = Conv1d(...)
out, temp_out_spatial_dim = conv(...)
temp_out_spatial_dim.declare_same_as(my_actual_out_spatial_dim)
```
I dislike here that I need this temporary variable `temp_out_spatial_dim` which coincides with the actual dim I want.

**Comment by albertz** [comment]
> > * On returnn-common side, we could not pass the out spatial dims at all. Due to [Make shape and dims available? returnn_common#47](https://github.com/rwth-i6/returnn_common/issues/47), we can just take whatever the layer creates in `get_out_data_from_opts`. We might set `auto_generated = False` then. This would be a very simple solution.
> 
> I think I would like it more if there would always be an `out_spatial_dim` arg, otherwise you would need to write something like this:
> 
> ```
> conv = Conv1d(...)
> out, temp_out_spatial_dim = conv(...)
> temp_out_spatial_dim.declare_same_as(my_actual_out_spatial_dim)
> ```
> 
> I dislike here that I need this temporary variable `temp_out_spatial_dim` which coincides with the actual dim I want.

Why so complicated? Why not just:

```
conv = Conv1d(...)
out, my_actual_out_spatial_dim = conv(...)
```

But also, you are basically referring to https://github.com/rwth-i6/returnn_common/issues/115 here.

However, this is not what I meant. I meant, when the user calls `conv(...)` without specifying `out_spatial_dim`, how should this be implemented. We can either create a new default out spatial dim and pass it to `out_spatial_dims` to RETURNN. Or we could not pass any `out_spatial_dims` and then via https://github.com/rwth-i6/returnn_common/issues/47 get the out spatial dims from the resulting `Data`. Although maybe this is ambiguous in some cases, so not sure if this is a good solution.

**Comment by Zettelkasten** [comment]
> > ```
> > conv = Conv1d(...)
> > out, temp_out_spatial_dim = conv(...)
> > temp_out_spatial_dim.declare_same_as(my_actual_out_spatial_dim)
> > ```
> >
> > I dislike here that I need this temporary variable `temp_out_spatial_dim` which coincides with the actual dim I want.
> 
> Why so complicated? Why not just:
> 
> ```
> conv = Conv1d(...)
> out, my_actual_out_spatial_dim = conv(...)
> ```
> 
> But also, you are basically referring to [rwth-i6/returnn_common#115](https://github.com/rwth-i6/returnn_common/issues/115) here.
> 
> However, this is not what I meant. I meant, when the user calls `conv(...)` without specifying `out_spatial_dim`, how should this be implemented. We can either create a new default out spatial dim and pass it to `out_spatial_dims` to RETURNN. Or we could not pass any `out_spatial_dims` and then via [rwth-i6/returnn_common#47](https://github.com/rwth-i6/returnn_common/issues/47) get the out spatial dims from the resulting `Data`. Although maybe this is ambiguous in some cases, so not sure if this is a good solution.

Yes, I am referring to that issue. I thought there (in [rwth-i6/returnn_common#115](https://github.com/rwth-i6/returnn_common/issues/115)) you are arguing that maybe it is not even needed to ever have such explicit `out_spatial_dim` arg, because you can just use the default one in any case.
With my example, I meant that `my_actual_out_spatial_dim` already existed before, e.g. because I want to share it between two layers. But in general, that's also how I write my configs currently, at the top of the config, I declare some dim tags that I will use later, and then pass them to all layers via `out_spatial_dim` to set them. So you would argue that the user would in most cases just use the dim tag returned by the `conv(..)` call directly, and not specify their own with their own description? Then, your code snippet would work (at least if I only need to set this dim tag two the output of one layer, and not to twice).
So, if returnn-common's `conv` didn't take an `out_spatial_dim` arg, then I would have to do something like this:
```
my_spatial_dim = SpatialDim(...)
y1, tmp_dim1 = conv(...)
y2, tmp_dim2 = conv(...)
tmp_dim1.declare_same_as(my_spatial_dim)
tmp_dim2.declare_same_as(my_spatial_dim)
```
Or:
```
y1, my_spatial_dim = conv(...)
y2, tmp_dim = conv(...)
tmp_dim.declare_same_as(my_spatial_dim)
```
Right?

**Comment by Zettelkasten** [comment]
> > > * We could allow `Dim.dimension == NotSpecified` or so (or introduce yet another flag to `Dim`), to mark the passed out spatial dim as not-yet-specified. This explicitly tells `get_out_data_from_opts` that it can fill in the details. E.g. call `declare_same_as` or define `dimension = ...`. This would not be so confusing because it is explicitly written down that there should be modifying side effects on this dim. One issue with this is that we would again need to go through all layers in [Specify dim tags for layers that create new axes #597](https://github.com/rwth-i6/returnn/issues/597) and extend the logic in all `get_out_data_from_opts`.
> > 
> > 
> > We already have such logic for dim tags with dynamic sizes. E.g. when you declare some dim tag in your config (where it has `dyn_size_ext=None` by default), and it is used as `out_spatial_dim` by some layer, then it's `dyn_size_ext` is set implicitly via `declare_same_as`. So here we don't even use such special `NotSpecified` value. I think the assumption so far was that whenever `dimension is None`, `dyn_size_ext` should be completed.
> 
> For dynamic dims, this is clear because when `dimension is None` (meaning dynamic dim) and `dyn_size_ext` is not set, it is clear that it is not yet set.
> 
> For static dims, this is not clear. Should `dimension is None` have two meanings now, i.e. meaning either dynamic dim or static dim but not defined yet?
> 
> I don't like that `dimension is None` can have these two meanings. That is why I suggested to have `dimension is NotSpecified` to clearly distinguish it.
> 
> `dimension is NotSpecified` could also mean it is dynamic, or static, but in any case it is not specified yet. This would simplify the code on returnn-common most because in the case the user does not provide `out_spatial_dim`, we can simply create `out_spatial_dim = nn.SpatialDim(dimension=NotSpecified, ...)` and it will work for all cases, static or dynamic.
> 
> > I think this is fine to also have for static dims, but then we should also change it such that exactly one of `Dim.dimension` and `Dim.dyn_size_ext` is always `None`, and the other never (either `NotSpecified`, or having an actual value).
> 
> I'm not sure I understand. How exactly?
> 
> > Now it would also be nicer to actually sub-class `Dim` into some `StaticDim` and `DynamicDim`, where `StaticDim` only has one attribute `dimension` and not `dyn_size_ext` and vice-versa.

Okay, perhaps `NotSpecified` is not a good name for this, rather `InitializedLater` or so and maybe it's clearer then what I meant. Sorry, calling this `NotSpecified` probably implies something else.
I would propose that the contract of `Dim` is that at each time:
 * `Dim.dimension` is `InitializedLater` or `None` or just some int
 * `Dim.dyn_size_ext` is `InitializedLater` or `None` or just some `Data`
 * exactly one of `Dim.dimension` and `Dim.dyn_size_ext` is `None` at any point. Perhaps we can make this more explicit by adding a `is_static` attribute.
With this, it's always clear whether this dim tag is static or not.

> Remember, we had such discussion about subclassing `Dim` already for `SpatialDim` and `FeatureDim` and decided that this is not a good idea, for various reasons. I think mostly to not break old configs. I think the same applies here, right?

Yeah I remember, but I thought that we mainly decided on this for simplicity but that it didn't matter too much. I'm not sure about backwards compatibility.
Now here I would argue for having two subclasses because then we avoid that `Dim.dimension` or `Dim.dyn_size_ext` can ever be `None`. They just wouldn't exist as attribute at all, so there is less confusion.

**Comment by albertz** [comment]
> > > ```
> > > conv = Conv1d(...)
> > > out, temp_out_spatial_dim = conv(...)
> > > temp_out_spatial_dim.declare_same_as(my_actual_out_spatial_dim)
> > > ```
> > 
> > Why so complicated? Why not just:
> > ```
> > conv = Conv1d(...)
> > out, my_actual_out_spatial_dim = conv(...)
> > ```
> > 
> > But also, you are basically referring to [rwth-i6/returnn_common#115](https://github.com/rwth-i6/returnn_common/issues/115) here.
> > However, this is not what I meant. I meant, when the user calls `conv(...)` without specifying `out_spatial_dim`, how should this be implemented. We can either create a new default out spatial dim and pass it to `out_spatial_dims` to RETURNN. Or we could not pass any `out_spatial_dims` and then via [rwth-i6/returnn_common#47](https://github.com/rwth-i6/returnn_common/issues/47) get the out spatial dims from the resulting `Data`. Although maybe this is ambiguous in some cases, so not sure if this is a good solution.
> 
> Yes, I am referring to that issue. I thought there (in [rwth-i6/returnn_common#115](https://github.com/rwth-i6/returnn_common/issues/115)) you are arguing that maybe it is not even needed to ever have such explicit `out_spatial_dim` arg, because you can just use the default one in any case. With my example, I meant that `my_actual_out_spatial_dim` already existed before, e.g. because I want to share it between two layers.

What do you mean by share?

The out spatial dim is the same as the in spatial dim? Then you might only want to have this said explicitly for error checking / verification. This is a different use case. I'm not sure that I would mix this now here.

The out spatial dim will be the same as some other one where you e.g. do the same kind of conv or pool? Now here you explicitly want to mark them as same. But is this the most intuitive way? Also, in those cases for conv and pool, this is not needed, this will be automatic, due to the dim tag math logic.

> But in general, that's also how I write my configs currently, at the top of the config, I declare some dim tags that I will use later, and then pass them to all layers via `out_spatial_dim` to set them.

But you only do this because when writing the config and net dict by hand and not using returnn-common, you don't really have any other choice. When you look at what returnn-common creates, then this is actually exactly like this. It will first define all dim tags and then create the net dict.

> So you would argue that the user would in most cases just use the dim tag returned by the `conv(..)` call directly, and not specify their own with their own description?

I don't really know. I assume so.

If you just want to set a custom description, you can still do that with my code snippet, like:
```
conv = Conv1d(...)
out, my_actual_out_spatial_dim = conv(...)
my_actual_out_spatial_dim.description = "whatever"
```

> Then, your code snippet would work (at least if I only need to set this dim tag two the output of one layer, and not to twice). So, if returnn-common's `conv` didn't take an `out_spatial_dim` arg, then I would have to do something like this:
> 
> ```
> my_spatial_dim = SpatialDim(...)
> y1, tmp_dim1 = conv(...)
> y2, tmp_dim2 = conv(...)
> tmp_dim1.declare_same_as(my_spatial_dim)
> tmp_dim2.declare_same_as(my_spatial_dim)
> ```
>
> Or:
> 
> ```
> y1, my_spatial_dim = conv(...)
> y2, tmp_dim = conv(...)
> tmp_dim.declare_same_as(my_spatial_dim)
> ```
> 
> Right?

Why not like:
```python
y1, my_spatial_dim = conv(...)
y2, my_spatial_dim_ = conv(...)
assert my_spatial_dim == my_spatial_dim_
```

**Comment by Zettelkasten** [comment]
> > I think RETURNN should never declare two dims equal that are both user defined, I think that is confusing and very implicit.
> 
> Isn't this in contradiction to what you said later:
> 
> > E.g. when you declare some dim tag in your config (where it has `dyn_size_ext=None` by default), and it is used as `out_spatial_dim` by some layer, then it's `dyn_size_ext` is set implicitly via `declare_same_as`.
> 
> ?

I meant that I find this confusing if the dim tags are both user defined.
Most layers create some auto generated `out_spatial_dim` first, and then declare this as equal to the user-provided `out_spatial_dim` (this is how it is in RETURNN right now, in returnn-common it's maybe different, see below).
I don't love this, because it's also implicit, but I find this okay because the user never had a reference to the implicitly auto generated `out_spatial_dim`. So there is not that much confusion.

What I am talking about is:
```
a_dim = SpatialDim(..)
b_dim = SpatialDim(..)
x  # of shape [a_dim]
y = conv(x, padding=same, stride=1, out_spatial_dim=b_dim)  # of shape [b_dim]
# the shape of y and x should be different! I, the user, explicitly defined it to be different!
# e.g.:
c = x + y  # should require explicit broadcasting to [a_dim, b_dim]!
```

> > In the case that `out_spatial_dim` is not declared explicitly in such case, then I'm not sure what I'd like. Probably a more restrictive behavior, i.e. behavior that does not declare them as equal, is better in many cases but perhaps inconvenient.
> 
> In case of returnn-common, all dim tags are user defined (or rather, none will have `auto_generated=True`). It does not make a difference where exactly they are defined.
> 
> `auto_generated` so far also only has one meaning: that `description` is used for equality. I would not add too much behavior depending on this flag.

Oh okay, I didn't know that returnn-common doesn't use auto generated dims. So okay, above I meant with "auto generated" not the RETURNN flag, but the fact that the layer created the dim tag and not the input dim tag is used.

**Comment by albertz** [comment]
> > > I think RETURNN should never declare two dims equal that are both user defined, I think that is confusing and very implicit.
> > 
> > Isn't this in contradiction to what you said later:
> > > E.g. when you declare some dim tag in your config (where it has `dyn_size_ext=None` by default), and it is used as `out_spatial_dim` by some layer, then it's `dyn_size_ext` is set implicitly via `declare_same_as`.
> > 
> > 
> > ?
> 
> I meant that I find this confusing if the dim tags are both user defined. Most layers create some auto generated `out_spatial_dim` first, and then declare this as equal to the user-provided `out_spatial_dim` (this is how it is in RETURNN right now, in returnn-common it's maybe different, see below). I don't love this, because it's also implicit, but I find this okay because the user never had a reference to the implicitly auto generated `out_spatial_dim`. So there is not that much confusion.

But consider the case that the out-spatial-dim is the same as in-spatial-dim (stride 1, padding same). Then the implicitly auto generated `out_spatial_dim` is the same as the in-spatial-dim. The in-spatial-dim might be user generated, and the out-spatial-dim might be another user generate dim, and then this side effect would make them equal.

> What I am talking about is:
> 
> ```
> a_dim = SpatialDim(..)
> b_dim = SpatialDim(..)
> x  # of shape [a_dim]
> y = conv(x, padding=same, stride=1, out_spatial_dim=b_dim)  # of shape [b_dim]
> # the shape of y and x should be different! I, the user, explicitly defined it to be different!
> # e.g.:
> c = x + y  # should require explicit broadcasting to [a_dim, b_dim]!
> ```

But now you are mixing things. The `ConvLayer` is not supposed to make a new different copy of a dim tag. We have `ReinterpretDataLayer` with `set_dim_tags` specifically for this use case. This is what we use for self-attention. I don't think that other layers should also do this.

Also, why would you ever want this here? I think the cases where you really want to introduce a new separate copy of a dim tag is sth like self attention. And it is good that we have one explicit layer for it (`ReinterpretDataLayer`), and not as a side effect from some other unrelated layer.

In your example, I'm actually not sure what I would expect to happen. Maybe `conv` internally would have some `assert in_spatial_dim == out_spatial_dim`. Or I would expect `out_spatial_dim.declare_same_as(in_spatial_dim)` here. You seem to disagree on the second point, and I also don't like it too much. Except when it is explicitly marked as not-specified / initialized-later, then it is ok. When it is not marked as such, I think I would disallow this. I would be confused if `a_dim != b_dim` in this example.

**Comment by albertz** [comment]
> I think we are really talking about different use cases. Perhaps I don't really understand the main concept here, and perhaps my experience with dim tags is also quite specific and not so much how you would use it on a everyday basis. So I'll just share a list of use cases where I like dim tags, and love that they are explicit:
> 
> * For self attention, I want to have a `key_dim` and `value_dim`. They usually have the same static dimension, but I don't want to mix them up, because they are conceptually incomparable. So I don't want `key_dim` to be the same as `value_dim`.
> * The `key_dim` is created in the output of multiple different layers: I have some layer creating a list of keys and a list of queries, both using `key_dim` as feature dim. So, if in returnn-common or so both these layers would create different dims by default, then I would need to explicitly declare them as the same, right? (or is this not the case because this is the feature dim, and it works differently?)

No, the feature dim (`out_dim` in most modules, like `Linear`, `Conv`) is (obviously) a required argument.

This issue here is only about any implicit new dim tags by a module or function, such as out spatial dims in `Conv`, `pool`, or also like `merge_dims`, etc.

> * Similarly to this I had a spatial time axis, `key-time` or so, which I want to sort my tensor along. So the output of this operation still has exactly the same sequence lengths, but I want to give this a new dim tag (`sorted-key-time` or so). Here, it is super important for me that `key-time` and `sorted-key-time` are entirely different, and that RETURNN prevents me from combining a sorted and unsorted version of a tensor accidentally (via the explicit broadcasting). Errors like this would be difficult to catch because everything would still run without error but lead to wrong results. I had a few of these problems before and then having these different dim tags was really helpful.

Yes, and for this, we have the `ReinterpretDataLayer` with `set_dim_tags` to make this very explicit. This is the same in returnn-common.

The implementation of self-attention is:
```python
self.key_dim_total = key_dim_total
self.key_dim_per_head = key_dim_total.div_left(num_heads)
self.value_dim_total = value_dim_total
self.value_dim_per_head = value_dim_total.div_left(num_heads)
self.num_heads = num_heads
self.qkv_dim_total = 2 * key_dim_total + value_dim_total
self.qkv_dim_per_head = 2 * self.key_dim_per_head + self.value_dim_per_head
self.qkv = nn.Linear(self.qkv_dim_total)

...

hist_dim = nn.SpatialDim(f"{nn.NameCtx.current_ctx().layer_abs_name_scope}:history")
qkv = self.qkv(source)
qkv = nn.split_dims(
  qkv, axis=self.qkv_dim_total, dims=(self.num_heads, self.qkv_dim_per_head), name="qkv_split_dims")
q, k, v = nn.split(
  qkv, axis=self.qkv_dim_per_head,
  out_dims=(self.key_dim_per_head, self.key_dim_per_head, self.value_dim_per_head),
  name="qkv_split")
if axis == nn.single_step_dim:
  assert causal is None or causal
  assert state
  new_state = nn.LayerState()
  k, _, new_state.k_accum = nn.cum_concat_step(k, state=state.k_accum, out_spatial_dim=hist_dim, name="k_accum")
  v, _, new_state.v_accum = nn.cum_concat_step(v, state=state.v_accum, out_spatial_dim=hist_dim, name="v_accum")
else:
  new_state = None
  assert not state
  if causal:
    raise NotImplementedError(
      "Causal attention on sequence level not implemented. "
      "We can easily extend CumConcatLayer on RETURNN side for this, to accept any axis argument. "
      "However, normally any causal attention should always be inside a loop and this should never be needed.")
  k, _ = nn.reinterpret_new_dim(k, in_dim=axis, out_dim=hist_dim, name="k_new_dim")
  v, _ = nn.reinterpret_new_dim(v, in_dim=axis, out_dim=hist_dim, name="v_new_dim")
att = dot_attention(q, k, v, key_dim=self.key_dim_per_head, axis=hist_dim, att_dropout=self.att_dropout)
output, _ = nn.merge_dims(
  att, axes=(self.num_heads, self.value_dim_per_head), out_dim=self.value_dim_total, name="output")
return output, new_state
```

> * When I talked about `conv` in my examples, I thought thought about this conceptually like my `sort` layer, where when I as the user specify `out_spatial_dim` explicitly, I want to do this to be sure that I cannot accidentally combine it with some tensor where I didn't apply the convolution on before. So I wanted to get an entirely new, independent dim tag as the input.
>   But I never used convolutions actually. So, in the case of `conv`, this is maybe not what users want. I guess my use case (with the `sort`), is quite different from normal usage.
>   Also I wasn't aware that (if I understand correctly) `conv` currently always marks my input dim equal to the output dim if they share the same seq lengths.

I still think, when the user really wants explicitly that after `conv`, or whatever other op, it is assigned a new separate dim tag, this should be explicit via a separate function. This is `nn.reinterpret_new_dim` in the code above.

When there is `conv` which would actually yield the same spatial dim, I would not expect it to be different at that point. Similar as I would not expect that `Linear` would give me a new spatial dim.

**Comment by Zettelkasten** [comment]
Okay, I see now. Sorry for my confusion. I wasn't aware about what e.g. `conv` would do, but okay, I agree now that `conv` with same padding, no stride should always require `in_spatial_dim == out_spatial_dim`. And as you said, I think I would just enforce this and not have it automatically declare them as same.
I think for returnn-common, it does indeed make sense that `conv` does not take a `out_spatial_dim` arg then (https://github.com/rwth-i6/returnn_common/issues/115) and instead just returns it.
For `conv` in particular I would even find it a little confusing if I had to specify it when it has to be the same as the input dim.

So okay, I understand now. Sorry that this is mixing up a lot of issues now, also on returnn-commons' side.

About this issue: Yes, I would find some explicit "`InitializedLater`/`InferredAutomatically`/etc." placeholder for both `Dim.dimension` and `Dim.dyn_size_ext` helpful. We already have this for `Dim.dyn_size_ext`, but it's very implicit there and I'd like it more if it was more explicit there too. And then we can do the same for `Dim.dimension`.
I still think sub-classing `Dim` into `DynamicDim` and `StaticDim` could clean this up, but I'm not entirely aware how much existing code that breaks.

**Comment by albertz** [comment]
Well, this is still a novel feature of RETURNN (`out_spatial_dims` and related options, #597) and I think not much people are really using it so far. Maybe no-one actually, not sure. returnn-common now is a first use case where it is consistently used all the time. But returnn-common is also still experimental and we need to figure out the best way. It's really not so clear what's best. I guess we will only really see after some experience.

You are raising the right concerns. It should not lead to unexpected behavior, and be explicit. And it should not be confusing. And it should also be simple and straightforward to use.

Btw, instead of `InitializedLater`/`InferredAutomatically`, I think `NotSpecified` is actually ok.

Btw, regarding implicit logic to fill in details in `out_spatial_dims`, what we have now for `ConvLayer.__init__`, `RangeLayer.get_out_data_from_opts`, `CumConcatLayer.__init__`, etc, this is also how `ReinterpretDataLayer.__init__` works for the `set_dims` option.

We need to differentiate the cases:
- where the out dim tag would become the same as some input dim tag (`declare_same_as`),
- where the out dim tag gets completed by setting `dyn_size_ext` or `dimension but this would be a new dim tag, not equal to any existing.

We probably should make it a bit more consistent. If possible, I think both cases should be covered in `get_out_data_from_opts` of a layer and not only later in `__init__`.

We also should not break existing code. So we might accept `dimension is None and dyn_size_ext is None` also as not being specified yet. All examples for self attention using `ReinterpretDataLayer` `set_dims` or `CumConcatLayer` are like this. Although maybe such code is still rare yet.

If we interpret `dimension is None and dyn_size_ext is None` as not being specified, maybe we don't actually need any new behavior? Currently `dimension is None and dyn_size_ext is None` also assumes that the dimension is dynamic then (because `dimension is None`). Earlier I argued that we should not allow for a different interpretation here but maybe we don't really have a choice now to not break old code, and maybe it's not such a big deal when checked together with `dyn_size_ext`.
