### ISSUE TITLE
`InvalidArgumentError: Retval[0] does not have value` in loss computation

### ISSUE THREAD

**Issue by mmz33** [rwth-i6/returnn#962]
I am getting a strange error related to loss computation i think. This also happen when computing loss scores on dev.

Example:
- Error with CTC loss: https://gist.github.com/mmz33/b40fb4099790f0048ece9553c1fab6ea
- Error with CL loss: https://gist.github.com/mmz33/96cb48cc034c1221add2aa4c542c6019

Config with CTC loss: https://gist.github.com/mmz33/17ff9794a98ab0fee02d341e48411cb1

Error:
```
InvalidArgumentError: Retval[0] does not have value
```
Looks related to this: https://github.com/tensorflow/tensorflow/issues/32106

If I checkout RETURNN with older version before this commit below, the issue does not occur:

```
commit e819b63be89fd6dae77e7d40950a8d990031b6a3
Author: Albert Zeyer <albzey@gmail.com>
Date:   Fri Feb 11 11:16:48 2022 +0100

    flatten_with_seq_len_mask cache (#944)
```

**Comment by albertz** [comment]
It’s really strange. It's probably non-deterministic and this change (#944) might just have introduced it randomly. Not sure if this i really related to the loss. From other similar reports, it sounds like it is an issue with TF variables + control flow logic.

In #961, I try to update to control flow V2. In some other error reports (https://github.com/tensorflow/tensorflow/issues/32106) it is reported that this should fix such errors.

**Comment by albertz** [comment]
Introducing control flow V2 has its own problems (see the process in #961) and I'm not really sure about it anymore.

I wonder if there is another way to fix this problem here.

**Comment by albertz** [comment]
Can you share the exact config? For the simpler case (CTC only).

**Comment by mmz33** [comment]
Config with CTC loss: https://gist.github.com/mmz33/17ff9794a98ab0fee02d341e48411cb1
