### ISSUE TITLE
support new librosa version 0.9.1

### ISSUE THREAD

**Issue by michelwi** [rwth-i6/returnn#969]
Setting up a new environment I noticed that the latest version of librosa is not working currently with returnn.

One example (I did not check all functions) would be 
https://github.com/rwth-i6/returnn/blob/a86ba33e1ade77c4a4994b9b8a7cca529128d1a3/returnn/datasets/util/feature_extraction.py#L309-L312
where `audio` is given as a positional argument, but `librosa.feature.mfcc` expects keyword-only arguments now:
https://librosa.org/doc/0.9.1/generated/librosa.feature.mfcc.html

Alternatively I would also be happy if you add the min/max supported version to `requirements.txt`.

**Comment by albertz** [comment]
So, just using `y=audio`... is the only change we need?
PR is welcome.

**Comment by michelwi** [comment]
This is the change needed for the one problem that I encountered. I do not oversee if
a) there are additional problems/changes needed in other parts of returnn, or
b) this change breaks compatibility with some older version.

**Comment by JackTemaki** [comment]
I tried to experiment with "extra" requirements to also include librosa there, but was not successful so far...

**Comment by michelwi** [comment]
resolved by #973
