### ISSUE TITLE
MaskedComputationLayer broken name scope for subnetwork

### ISSUE THREAD

**Issue by albertz** [rwth-i6/returnn#986]
In case of a subnetwork inside the `MaskedComputationLayer`, the name scope seems to include the name twice, like `output/rec/lm_masked/lm_masked` (reported by @robin-p-schmitt). (Related #985)

This is not expected and I think should not be like that.

Together with #985, this should be just `output/lm_masked`.

Again, just like #985, this would break checkpoints. However, again like #985, I think this can be detected and fixed in `CustomCheckpointLoader`.

**Comment by albertz** [comment]
@robin-p-schmitt I'm trying to reproduce this but in my tests, I can't. It looks correct. Can you share the config where you got `output/rec/lm_masked/lm_masked`?

**Comment by robin-p-schmitt** [comment]
> @robin-p-schmitt I'm trying to reproduce this but in my tests, I can't. It looks correct. Can you share the config where you got `output/rec/lm_masked/lm_masked`?

Here is the config: https://gist.github.com/robin-p-schmitt/63aa622ec73bbd7571c7c95b61b652b4
And here the corresponding graph: https://gist.github.com/robin-p-schmitt/912126fe41b1c55755e7c8e5d5e643d7

In the graph, some nodes start with `output/rec/lm_masked/lm_masked`

**Comment by albertz** [comment]
> > @robin-p-schmitt I'm trying to reproduce this but in my tests, I can't. It looks correct. Can you share the config where you got `output/rec/lm_masked/lm_masked`?
> 
> Here is the config: https://gist.github.com/robin-p-schmitt/63aa622ec73bbd7571c7c95b61b652b4 And here the corresponding graph: https://gist.github.com/robin-p-schmitt/912126fe41b1c55755e7c8e5d5e643d7
> 
> In the graph, some nodes start with `output/rec/lm_masked/lm_masked`

This is the wrong config. You explicitly set `name_scope` here, so obviously it uses whatever `name_scope` you specified.

**Comment by robin-p-schmitt** [comment]
Oops, my bad. I updated the gist to the correct config

**Comment by albertz** [comment]
> In the graph, some nodes start with `output/rec/lm_masked/lm_masked`

However, those are all not relevant. Relevant are the variable node names. And they look correct. E.g.:
```
  node {
    name: "output/rec/lm_masked/lm/b"
    op: "VarHandleOp"
```

When the variable names are correct, there is no real issue here.

**Comment by robin-p-schmitt** [comment]
> > In the graph, some nodes start with `output/rec/lm_masked/lm_masked`
> 
> However, those are all not relevant. Relevant are the variable node names. And they look correct. E.g.:
> 
> ```
>   node {
>     name: "output/rec/lm_masked/lm/b"
>     op: "VarHandleOp"
> ```
> 
> When the variable names are correct, there is no real issue here.

Okay, I was not aware of that.

**Comment by albertz** [comment]
The variable names (node names) are relevant for the checkpoint. Those are really important, and when they are somehow wrong (unexpected), that would be a serious problem.

All other node names are just cosmetic. For inspection in TensorBoard etc.

So, if they are somehow unexpected, we maybe should fix this, but this is not really important or relevant.
