### ISSUE TITLE
Switch to PyTest

### ISSUE THREAD

**Issue by albertz** [rwth-i6/returnn#987]
Currently we use nosetests.

I think [PyTest](https://docs.pytest.org/) has become much more popular.

I'm also not exactly happy with the error reporting of nosetests. E.g. I would like some nice summary at the end which lists the failing test cases. Not sure if PyTest has that though.

But in any case, it is often a good idea to use whatever is more widely used, as this is better supported. And this should probably be simple to switch.

**Comment by albertz** [comment]
Any opinions? @curufinwe @patrick-wilken @Zettelkasten ?

**Comment by JackTemaki** [comment]
I missed this one, yeah I also saw that nosetests is no longer maintained and people should switch to something else. So I guess switching to PyTest is not a bad idea.
