### ISSUE TITLE
Simple question: What does config.value('task', 'train') mean?

### ISSUE THREAD

**Issue by mjhanphd** [rwth-i6/returnn#99]
I think that 'task' has to be one among 'train', 'eval', 'forward, etc.
But in the code I often come across checking config.value('task', 'train'), comparing it to one of 'theano_graph', 'server', or anything.
And this doesn't make sense to me.
What is the return value of config.value('task', 'train'), e.g. what if we suppose "task = train" in the config file.
Thanks in advance :)

**Comment by albertz** [comment]
You closed this yourself, so I guess it became clear? But otherwise, just look at the documentation:
```
class Config:
  ...

  def value(self, key, default, index=None, list_join_str=","):
    """
    :type key: str
    :type default: T
    :type index: int | None
    :rtype: str | T
    """
    ...
```
