### ISSUE TITLE
ConvLayer.transform_input

### ISSUE THREAD

**Issue by vieting** [rwth-i6/returnn#998]
The newly added `StftLayer` uses `ConvLayer.get_out_data_from_opts`. I have a case with an additional speaker dim, so the input is
```
<SplitDimsLayer 'target_signals_split' out_type=Data{[B,T|'waveform_time_dim'[B],F'speaker_dim'(2),F|F'waveform_feature_dim'(1)], available_for_inference=False}>
```
`ConvLayer.get_out_data_from_opts` returns
```
Data{'target_signals_stft_new_output', [B,T|'target_signals_stft_new:conv:s0'[?],F|F'target_signals_stft_new:channel'(257)]}
```
so the speaker dim is ignored. @albertz, you suspected the problem is likely in `ConvLayer.transform_input` in the last `else` branch.

**Comment by albertz** [comment]
Just as a side node, in your config, this somehow depends on sth which is not available at inference time, thus you have `available_for_inference=False` here.

**Comment by albertz** [comment]
I just checked the code. Having an extra unrelated dim is only really supported when you use a recent behavior version, and/or when you explicitly provide `in_spatial_dims`.
